/* ─── THE COUNTRY ROOM ───────────────────────────────────────────────
   Ayser: "خلي في حاجات عن تعلم اللغات و الثقافه و الأكل أفلام أغاني
   خليه بسكشن للبلاد لو ده ممكن ذي الي في memories و bussu"

   ── WHY THIS IS NOT A LANGUAGE COURSE ─────────────────────────────
   Busuu and Memrise are large staffed products with written pedagogy,
   native-speaker recordings and years of spaced-repetition research
   behind them. A one-person imitation of that would be thin, and a
   thin language course is worse than none: people compare it to the
   real thing within a minute and stop trusting the rest of the app.

   What this app has that they do not is that it knows where you are,
   who else is there, and what you are about to do. So this room is not
   lesson one of Greek. It is the twelve things you will actually need
   to say in Greece in your first week, in the order a person needs
   them: meeting somebody, ordering, getting around, and the sentence
   you need when something has gone wrong. Somebody who lands in Athens
   knowing those twelve arrives differently. Somebody who did lesson
   one of a course knows how to say "the boy has an apple".

   ── AND WHY FOOD AND CUSTOMS SIT NEXT TO THE WORDS ────────────────
   Because they are the same knowledge. Knowing the word for the bill
   is useless if you do not know that in Greece nobody will bring it
   until you ask, and that the small dessert that arrives with it is a
   gift and not a mistake. That is the part no phrasebook prints and
   the part that makes somebody feel like a guest instead of a tourist.

   ── NOTHING HERE BELONGS TO ANYBODY ───────────────────────────────
   A phrase is not property. A dish is not property. A custom is not
   property. The films come from our own real catalogue, filtered by
   the language they are in — we host nothing and stream nothing, the
   same rule as everywhere else in this app. The music section names
   real artists and opens a real search on a real service; not one byte
   of anybody's recording is copied, cached or played by us.

   ── WHAT IS DELIBERATELY MISSING ──────────────────────────────────
   Audio. The right way to teach how a word sounds is a native speaker
   saying it, and we do not have those recordings and will not fake
   them with a robot voice that teaches somebody a wrong accent. The
   pronunciation line is written the way an Arabic or English reader
   would sound it out, and it says so.                                */

/* `how` is written to be read aloud by somebody who reads English —
   capitals are the stressed part. It is not IPA and does not pretend
   to be; it is the line a friend writes on a napkin. */

export const COUNTRY_ROOMS = [
  {
    code: 'GR', name: 'Greece', nameAr: 'اليونان',
    lang: 'Greek', langAr: 'اليونانية', filmLang: 'el',
    hello: {
      native: 'Γειά σου', how: 'YAH-soo',
      means: 'Literally "health to you". The Greek word for health, υγεία, is sitting inside the hello — you are wishing somebody well every time you say it.',
      meansAr: 'حرفياً "الصحة ليك". كلمة الصحة اليونانية υγεία جوّه كلمة السلام نفسها — يعني إنت بتتمنى للناس الخير كل مرة تقولها.',
      bye: { native: 'Αντίο', how: 'ah-DEE-oh',
             means: 'The formal goodbye. Between friends, γειά σου works on the way out as well as on the way in.',
             meansAr: 'الوداع الرسمي. بين الأصحاب، γειά σου بتنفع وانت خارج زي ما بتنفع وانت داخل.' },
    },
    warm: [
      { native: 'Χάρηκα', how: 'HA-ree-ka', en: 'Nice to meet you — literally "I was glad"', ar: 'تشرفنا — حرفياً "أنا اتبسطت"', when: 'At the end of a first meeting', whenAr: 'في آخر أول لقاء' },
      { native: 'Στην υγειά σου!', how: 'stin ee-YAH-soo', en: 'Cheers — "to your health" again', ar: 'في صحتك — "لصحتك" برضه', when: 'Raising a glass', whenAr: 'وانت رافع الكباية' },
      { native: 'Καλή όρεξη', how: 'ka-LEE O-rek-see', en: 'Good appetite', ar: 'بالهنا والشفا', when: 'Before anyone eats', whenAr: 'قبل ما حد ياكل' },
      { native: 'Παρακαλώ', how: 'pah-rah-kah-LOH', en: 'You are welcome — and also "please", and also "go ahead"', ar: 'العفو — وكمان "من فضلك"، وكمان "اتفضل"', when: 'It does a lot of work', whenAr: 'بتعمل حاجات كتير' },
    ],
    say: [
      { g: 'first', native: 'Γειά σου',    how: 'YAH-soo',            en: 'Hi — to one person, casually',   ar: 'أهلاً — لشخص واحد، بشكل ودّي' },
      { g: 'first', native: 'Γειά σας',    how: 'YAH-sas',            en: 'Hello — polite, or to more than one', ar: 'أهلاً — رسمي، أو لأكتر من واحد' },
      { g: 'first', native: 'Ευχαριστώ',   how: 'ef-hah-ree-STOH',    en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Συγγνώμη',    how: 'see-GHNO-mee',       en: 'Sorry / excuse me',              ar: 'آسف / لو سمحت' },
      { g: 'eat',   native: 'Έναν καφέ, παρακαλώ', how: 'EH-nan kah-FEH pah-rah-kah-LOH', en: 'One coffee, please', ar: 'قهوة واحدة، من فضلك' },
      { g: 'eat',   native: 'Νερό',        how: 'neh-ROH',            en: 'Water',                          ar: 'مياه' },
      { g: 'eat',   native: 'Χωρίς κρέας', how: 'ho-REES KREH-as',    en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Τον λογαριασμό, παρακαλώ', how: 'ton lo-ghar-yaz-MOH pah-rah-kah-LOH', en: 'The bill, please', ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Πού είναι…;', how: 'POO EE-neh',         en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Πόσο κάνει;', how: 'POH-so KAH-nee',     en: 'How much is it?',                ar: 'بكام؟' },
      { g: 'help',  native: 'Μιλάτε αγγλικά;', how: 'mee-LAH-teh ang-glee-KAH', en: 'Do you speak English?', ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Βοήθεια!',    how: 'vo-EE-thee-ah',      en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Fasolada', nameAr: 'فاصوليا يونانية',
        what: 'White beans slow-cooked with tomato, carrot and a lot of olive oil. Greeks will tell you it is the real national dish, not moussaka.',
        whatAr: 'فاصوليا بيضا مطبوخة على نار هادية بطماطم وجزر وزيت زيتون كتير. اليونانيين نفسهم بيقولوا دي الأكلة الوطنية الحقيقية مش المسقعة.' },
      { name: 'Horiatiki', nameAr: 'سلطة قروية',
        what: 'The village salad. Tomato, cucumber, onion, olives and a whole slab of feta on top — no lettuce, ever.',
        whatAr: 'السلطة القروية. طماطم وخيار وبصل وزيتون وقطعة جبنة فيتا كاملة فوق — ومفيش خس أبداً.' },
      { name: 'Souvlaki', nameAr: 'سوفلاكي',
        what: 'Grilled meat on a skewer, or wrapped in pita with tomato, onion and chips inside. The late-night food of every Greek city.',
        whatAr: 'لحمة مشوية على سيخ، أو ملفوفة في عيش بطماطم وبصل وبطاطس محمرة جوّه. أكلة آخر الليل في كل مدينة يونانية.' },
      { name: 'Loukoumades', nameAr: 'لقمة القاضي',
        what: 'Small fried dough balls in honey and cinnamon. If you know زلابية, you already know these.',
        whatAr: 'كور عجين مقلية صغيرة بعسل وقرفة. لو تعرف الزلابية، فأنت تعرفها.' },
    ],
    know: [
      { title: 'Nobody brings the bill until you ask',
        titleAr: 'محدش هيجيبلك الحساب غير لما تطلبه',
        body: 'Sitting a long time after eating is not rude, it is the point. Bringing the bill unasked would be telling you to leave.',
        bodyAr: 'إنك تقعد كتير بعد ما تخلص أكل مش قلة ذوق، ده أصل الفكرة. لو جابلك الحساب من غير ما تطلبه يبقى بيقولك امشي.' },
      { title: 'The small dessert at the end is a gift',
        titleAr: 'الحلو الصغير في الآخر ده هدية',
        body: 'It is called kerasma. It is free, it is not a mistake, and refusing it is a small insult.',
        bodyAr: 'اسمه kerasma. ببلاش، ومش غلطة، ورفضه إهانة صغيرة.' },
      { title: 'Your name day matters more than your birthday',
        titleAr: 'يوم اسمك أهم من عيد ميلادك',
        body: 'Most Greeks are named after a saint and celebrate that saint’s day. The person with the name buys the drinks, not the guests.',
        bodyAr: 'أغلب اليونانيين متسمّيين على اسم قديس وبيحتفلوا بيوم القديس ده. وصاحب الاسم هو اللي بيدفع، مش الضيوف.' },
    ],
    hear: [
      { title: 'Zorba’s Dance', artist: 'Mikis Theodorakis', year: '1964',
        why: 'Written for the film. The tune the rest of the world hears as Greece.',
        whyAr: 'اتكتبت لفيلم. اللحن اللي الدنيا كلها بتسمعه وتقول ده اليونان.' },
      { title: 'Rebetiko', artist: 'Stelios Kazantzidis', year: '1950s–60s',
        why: 'The voice of the post-war generation — refugee music that became everybody’s music.',
        whyAr: 'صوت جيل ما بعد الحرب — موسيقى اللاجئين اللي بقت موسيقى الكل.' },
      { title: 'Anything of hers', artist: 'Haris Alexiou', year: 'since 1975',
        why: 'The best-known living voice in Greek song. Start anywhere.',
        whyAr: 'أشهر صوت حيّ في الأغنية اليونانية. ابدأ من أي حتة.' },
    ],
  },
  {
    code: 'IT', name: 'Italy', nameAr: 'إيطاليا',
    lang: 'Italian', langAr: 'الإيطالية', filmLang: 'it',
    hello: {
      native: 'Ciao', how: 'chow',
      means: 'From the Venetian s-ciào vostro — "I am your servant". A promise of service, worn down over centuries into hello. Use it with people you know; buongiorno with people you do not.',
      meansAr: 'من الڤينيسي s-ciào vostro يعني "أنا خادمك". وعد بالخدمة اتآكل على مدى قرون لحد ما بقى "أهلاً". استعملها مع اللي تعرفهم، وbuongiorno مع اللي ما تعرفهمش.',
      bye: { native: 'Arrivederci', how: 'ar-ree-veh-DAIR-chee',
             means: 'Literally "until we see each other again".',
             meansAr: 'حرفياً "لحد ما نتشاف تاني".' },
    },
    warm: [
      { native: 'Piacere', how: 'pya-CHEH-reh', en: 'Pleased to meet you — literally "a pleasure"', ar: 'تشرفنا — حرفياً "متعة"', when: 'Shaking hands the first time', whenAr: 'أول سلام بالإيد' },
      { native: 'Salute!', how: 'sa-LOO-teh', en: 'Cheers — "health". Also what you say when someone sneezes', ar: 'في صحتك — "صحة". وبتتقال كمان لما حد يعطس', when: 'Glasses, and sneezes', whenAr: 'مع الكبايات، ومع العطس' },
      { native: 'Buon appetito', how: 'bwon ap-peh-TEE-toh', en: 'Good appetite — nobody starts eating without it', ar: 'بالهنا والشفا — محدش بيبدأ ياكل من غيرها', when: 'Before the first forkful', whenAr: 'قبل أول لقمة' },
      { native: 'Figurati', how: 'fee-GOO-rah-tee', en: 'Don\u2019t mention it — literally "imagine that"', ar: 'ولا يهمك — حرفياً "تخيّل"', when: 'When they thank you', whenAr: 'لما يشكروك' },
    ],
    say: [
      { g: 'first', native: 'Buongiorno',  how: 'bwon-JOR-no',      en: 'Good morning — until about 4pm', ar: 'صباح الخير — لحد الرابعة العصر تقريباً' },
      { g: 'first', native: 'Buonasera',   how: 'bwo-na-SEH-ra',    en: 'Good evening — after that',      ar: 'مساء الخير — بعد كده' },
      { g: 'first', native: 'Grazie',      how: 'GRAH-tsyeh',       en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Scusi',       how: 'SKOO-zee',         en: 'Excuse me — to a stranger',      ar: 'لو سمحت — لشخص ما تعرفوش' },
      { g: 'eat',   native: 'Un caffè, per favore', how: 'oon kaf-FEH per fa-VO-reh', en: 'One coffee, please — that means an espresso', ar: 'قهوة واحدة من فضلك — ودي معناها إسبريسو' },
      { g: 'eat',   native: 'Acqua del rubinetto', how: 'AH-kwa del roo-bee-NET-to', en: 'Tap water',      ar: 'مياه الحنفية' },
      { g: 'eat',   native: 'Senza carne', how: 'SEN-tsa KAR-neh',  en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Il conto, per favore', how: 'eel KON-to per fa-VO-reh', en: 'The bill, please', ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Dov’è…?',     how: 'do-VEH',           en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Quanto costa?', how: 'KWAN-to KOS-ta', en: 'How much is it?',                ar: 'بكام؟' },
      { g: 'help',  native: 'Parla inglese?', how: 'PAR-la een-GLEH-zeh', en: 'Do you speak English?',    ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Aiuto!',      how: 'ah-YOO-to',        en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Cacio e pepe', nameAr: 'كاتشو إي بيبي',
        what: 'Pasta with sheep’s cheese and black pepper. Three ingredients, and Romans argue about it endlessly.',
        whatAr: 'مكرونة بجبنة غنم وفلفل أسود. تلات مكونات بس، والرومان بيتخانقوا عليها من غير نهاية.' },
      { name: 'Pizza al taglio', nameAr: 'بيتزا بالقطعة',
        what: 'Pizza sold by weight from a tray, cut with scissors. Lunch, standing up, cheap.',
        whatAr: 'بيتزا بتتباع بالوزن من صينية وبتتقص بمقص. غدا، واقف، ورخيصة.' },
      { name: 'Arancini', nameAr: 'أرانتشيني',
        what: 'Sicilian fried rice balls with ragù or cheese inside. Street food, eaten hot.',
        whatAr: 'كور رز مقلية صقلية جواها لحمة أو جبنة. أكل شارع، بتتاكل سخنة.' },
      { name: 'Gelato', nameAr: 'جيلاتو',
        what: 'Not ice cream — less fat, less air, served warmer so you taste more. Look for one where the pistachio is dull green, not bright.',
        whatAr: 'مش آيس كريم — دهون أقل وهوا أقل وبيتقدم أدفى عشان تحس بالطعم أكتر. دوّر على محل الفستق فيه أخضر باهت مش فاقع.' },
    ],
    know: [
      { title: 'A cappuccino after 11am marks you out',
        titleAr: 'كابتشينو بعد الحداشر بيفضحك',
        body: 'Milky coffee is a breakfast thing. Nobody will stop you — they will simply know exactly where you are from.',
        bodyAr: 'القهوة باللبن حاجة فطار. محدش هيمنعك — بس هيعرفوا انت جاي منين بالظبط.' },
      { title: 'You pay more to sit down',
        titleAr: 'القعدة بتخليك تدفع أكتر',
        body: 'Standing at the bar is the cheap price and it is on the wall. The same coffee at a table can be three times as much, legally.',
        bodyAr: 'إنك تقف على البار ده السعر الرخيص ومكتوب على الحيطة. نفس القهوة على ترابيزة ممكن تبقى بتلات أضعاف، وده قانوني.' },
      { title: 'Coperto is not a scam',
        titleAr: 'الـ coperto مش نصب',
        body: 'A small per-person charge for the table and bread. It is printed on the menu and it is normal. Tipping on top is not expected.',
        bodyAr: 'مبلغ صغير للفرد مقابل الترابيزة والعيش. مكتوب في المنيو وطبيعي. والبقشيش فوقه مش متوقع.' },
    ],
    hear: [
      { title: 'Nel blu, dipinto di blu (Volare)', artist: 'Domenico Modugno', year: '1958',
        why: 'The song that made Italian pop travel. Everybody over forty knows every word.',
        whyAr: 'الأغنية اللي خلت البوب الإيطالي يسافر. أي حد فوق الأربعين حافظ كل كلمة فيها.' },
      { title: 'La donna è mobile', artist: 'Giuseppe Verdi', year: '1851',
        why: 'From Rigoletto. Opera is not a museum here; this one is sung in kitchens.',
        whyAr: 'من أوبرا ريجوليتو. الأوبرا هنا مش متحف؛ دي بتتغنى في المطابخ.' },
      { title: 'Anything of his', artist: 'Lucio Battisti', year: '1969–1980',
        why: 'The songwriter Italians measure the rest against.',
        whyAr: 'المؤلف اللي الإيطاليين بيقيسوا عليه أي حد تاني.' },
    ],
  },
  {
    code: 'ES', name: 'Spain', nameAr: 'إسبانيا',
    lang: 'Spanish', langAr: 'الإسبانية', filmLang: 'es',
    hello: {
      native: 'Hola', how: 'OH-la',
      means: 'The h is silent — say it "ola". Spaniards greet loudly and early; walking into a small shop without one is the thing that marks you out.',
      meansAr: 'الـ h ما بتتنطقش — قولها "أولا". الإسبان بيسلموا بصوت عالي وبدري؛ ودخولك محل صغير من غير سلام هو اللي بيفضحك.',
      bye: { native: 'Hasta luego', how: 'AH-sta LWEH-go',
             means: 'Literally "until later" — used even with people you will never see again.',
             meansAr: 'حرفياً "لحد بعدين" — بتتقال حتى لناس عمرك ما هتشوفهم تاني.' },
    },
    warm: [
      { native: 'Mucho gusto', how: 'MOO-cho GOOS-toh', en: 'Pleased to meet you — literally "much pleasure"', ar: 'تشرفنا — حرفياً "متعة كبيرة"', when: 'A first introduction', whenAr: 'أول تعارف' },
      { native: '¡Salud!', how: 'sa-LOOD', en: 'Cheers — "health"', ar: 'في صحتك — "صحة"', when: 'Every toast', whenAr: 'كل نخب' },
      { native: 'Buen provecho', how: 'bwen pro-VEH-cho', en: 'Enjoy your meal — said to strangers at the next table', ar: 'بالهنا والشفا — بتتقال لناس ما تعرفهمش على الترابيزة اللي جنبك', when: 'Passing anyone eating', whenAr: 'وانت عدّي على حد بياكل' },
      { native: 'De nada', how: 'deh NAH-da', en: 'You are welcome — literally "of nothing"', ar: 'العفو — حرفياً "من لا شيء"', when: 'After a thank you', whenAr: 'بعد الشكر' },
    ],
    say: [
      { g: 'first', native: 'Hola',        how: 'OH-la',            en: 'Hi',                             ar: 'أهلاً' },
      { g: 'first', native: 'Buenos días', how: 'BWEH-nos DEE-as',  en: 'Good morning',                   ar: 'صباح الخير' },
      { g: 'first', native: 'Gracias',     how: 'GRAH-thyas',       en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Perdona',     how: 'per-DOH-na',       en: 'Excuse me / sorry',              ar: 'لو سمحت / آسف' },
      { g: 'eat',   native: 'Un café con leche', how: 'oon ka-FEH kon LEH-cheh', en: 'A coffee with milk', ar: 'قهوة باللبن' },
      { g: 'eat',   native: 'Agua del grifo', how: 'AH-gwa del GREE-fo', en: 'Tap water',                 ar: 'مياه الحنفية' },
      { g: 'eat',   native: 'Sin carne',   how: 'seen KAR-neh',     en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'La cuenta, por favor', how: 'la KWEN-ta por fa-VOR', en: 'The bill, please',  ar: 'الحساب، من فضلك' },
      { g: 'go',    native: '¿Dónde está…?', how: 'DON-deh es-TAH', en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: '¿Cuánto es?', how: 'KWAN-to es',       en: 'How much is it?',                ar: 'بكام؟' },
      { g: 'help',  native: '¿Hablas inglés?', how: 'AH-blas een-GLES', en: 'Do you speak English?',      ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: '¡Socorro!',   how: 'so-KOR-ro',        en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Tortilla de patatas', nameAr: 'تورتييا البطاطس',
        what: 'A thick potato and egg omelette, served at any temperature. The one dish in every bar in the country.',
        whatAr: 'عجة بيض وبطاطس تخينة، بتتقدم على أي درجة حرارة. الأكلة الوحيدة الموجودة في كل بار في البلد.' },
      { name: 'Jamón', nameAr: 'خامون',
        what: 'Cured ham, sliced paper-thin. It is pork — worth knowing if that matters to you, because it is in almost everything.',
        whatAr: 'لحمة مملحة مقطعة رفيع جداً. دي لحم خنزير — مهم تعرف لو ده يفرق معاك، لأنها في كل حاجة تقريباً.' },
      { name: 'Pan con tomate', nameAr: 'خبز بالطماطم',
        what: 'Bread rubbed with a cut tomato, olive oil, salt. Breakfast in Catalonia and half of Spain.',
        whatAr: 'عيش مدعوك بطماطم مقطوعة وزيت زيتون وملح. الفطار في كتالونيا ونص إسبانيا.' },
      { name: 'Churros con chocolate', nameAr: 'تشوروس بالشوكولاتة',
        what: 'Fried dough dipped in thick drinking chocolate. Eaten at 7am on the way home, not as a dessert.',
        whatAr: 'عجين مقلي بيتغمس في شوكولاتة تقيلة. بتتاكل الساعة سبعة الصبح وانت راجع البيت، مش كحلو بعد الأكل.' },
    ],
    know: [
      { title: 'Dinner starts at nine, or later',
        titleAr: 'العشا بيبدأ الساعة تسعة، أو بعدها',
        body: 'A kitchen at 7pm is often closed. Eat something small in the afternoon or you will be very hungry by the time anywhere opens.',
        bodyAr: 'المطبخ الساعة سبعة بالليل غالباً مقفول. كُل حاجة خفيفة بعد الضهر وإلا هتبقى جعان جداً لحد ما حاجة تفتح.' },
      { title: 'The tapa can be free, and it depends where you are',
        titleAr: 'التابا ممكن تكون ببلاش، وده بيختلف من مكان لمكان',
        body: 'In Granada and León a drink comes with food included. In Madrid or Barcelona you are usually paying for it.',
        bodyAr: 'في غرناطة وليون المشروب بييجي معاه أكل مجاناً. في مدريد وبرشلونة غالباً بتدفع تمنه.' },
      { title: 'Two kisses, and it starts on their left cheek',
        titleAr: 'بوستين، والبداية من خدهم الشمال',
        body: 'Between women, and between a woman and a man. Men usually shake hands. Getting the side wrong is a running joke, not a problem.',
        bodyAr: 'بين الستات، وبين ست وراجل. الرجالة بيسلموا بالإيد عادةً. ولو غلطت في الناحية دي نكتة متكررة مش مشكلة.' },
    ],
    hear: [
      { title: 'Entre dos aguas', artist: 'Paco de Lucía', year: '1973',
        why: 'The guitarist who took flamenco out of Andalusia and into the world.',
        whyAr: 'العازف اللي طلّع الفلامنكو من الأندلس للعالم.' },
      { title: 'Anything of hers', artist: 'Rosalía', year: 'since 2017',
        why: 'Flamenco rebuilt for people born after 2000. Deeply divisive, hugely popular.',
        whyAr: 'فلامنكو متعمل من أول وجديد لناس اتولدت بعد ٢٠٠٠. مثيرة للخلاف جداً ومشهورة جداً.' },
      { title: 'Mediterráneo', artist: 'Joan Manuel Serrat', year: '1971',
        why: 'Voted the best Spanish song of the century by Spaniards themselves.',
        whyAr: 'الإسبان نفسهم اختاروها أحسن أغنية إسبانية في القرن.' },
    ],
  },
  {
    code: 'FR', name: 'France', nameAr: 'فرنسا',
    lang: 'French', langAr: 'الفرنسية', filmLang: 'fr',
    hello: {
      native: 'Bonjour', how: 'bon-ZHOOR',
      means: 'Literally "good day" — bon jour, two ordinary words. Plain, and the single most load-bearing word in the country: nothing else works until it has been said.',
      meansAr: 'حرفياً "نهار كويس" — bon jour، كلمتين عاديين. بسيطة، وهي أهم كلمة في البلد كلها: مفيش حاجة بتمشي قبل ما تتقال.',
      bye: { native: 'Au revoir', how: 'oh ruh-VWAR',
             means: 'Literally "until the re-seeing". Say it on the way out of a shop even if you bought nothing.',
             meansAr: 'حرفياً "لحد الشوفة الجاية". قولها وانت خارج من المحل حتى لو ما اشتريتش حاجة.' },
    },
    warm: [
      { native: 'Enchanté', how: 'on-shon-TEH', en: 'Pleased to meet you — literally "enchanted"', ar: 'تشرفنا — حرفياً "مسحور"', when: 'A first handshake', whenAr: 'أول سلام' },
      { native: 'Santé!', how: 'son-TEH', en: 'Cheers — "health"', ar: 'في صحتك — "صحة"', when: 'Every glass, eyes up', whenAr: 'كل كباية، وعينك في عينه' },
      { native: 'Bon appétit', how: 'bon ap-eh-TEE', en: 'Good appetite', ar: 'بالهنا والشفا', when: 'Before eating, without fail', whenAr: 'قبل الأكل، من غير استثناء' },
      { native: 'Je vous en prie', how: 'zhuh voo zon PREE', en: 'You are welcome — the warm, polite one', ar: 'العفو — الصيغة الدافية المهذبة', when: 'After a thank you', whenAr: 'بعد الشكر' },
    ],
    say: [
      { g: 'first', native: 'Bonjour',     how: 'bon-ZHOOR',        en: 'Hello — say it before anything else, always', ar: 'أهلاً — قولها قبل أي حاجة تانية، دايماً' },
      { g: 'first', native: 'Merci',       how: 'mer-SEE',          en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Pardon',      how: 'par-DON',          en: 'Sorry / excuse me',              ar: 'آسف / لو سمحت' },
      { g: 'first', native: 'Au revoir',   how: 'oh ruh-VWAR',      en: 'Goodbye — say this on the way out too', ar: 'مع السلامة — قولها وانت خارج كمان' },
      { g: 'eat',   native: 'Un café, s’il vous plaît', how: 'an ka-FEH seel voo PLEH', en: 'One coffee, please — an espresso', ar: 'قهوة واحدة من فضلك — إسبريسو' },
      { g: 'eat',   native: 'Une carafe d’eau', how: 'oon ka-RAF DOH', en: 'A jug of tap water — free, and your right', ar: 'شفشق مياه من الحنفية — ببلاش، وده حقك' },
      { g: 'eat',   native: 'Sans viande', how: 'son VYAND',        en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'L’addition, s’il vous plaît', how: 'la-dee-SYON seel voo PLEH', en: 'The bill, please', ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Où est…?',    how: 'oo EH',            en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'C’est combien?', how: 'seh kom-BYAN',  en: 'How much is it?',                ar: 'بكام؟' },
      { g: 'help',  native: 'Vous parlez anglais?', how: 'voo par-LEH on-GLEH', en: 'Do you speak English?', ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Au secours!',  how: 'oh suh-KOOR',     en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Jambon-beurre', nameAr: 'جامبون-بور',
        what: 'Ham and butter in a baguette. The most-sold sandwich in France by a distance, and it is pork.',
        whatAr: 'لحمة وزبدة في باجيت. أكتر ساندوتش بيتباع في فرنسا بفارق كبير، وهو لحم خنزير.' },
      { name: 'Galette', nameAr: 'جاليت',
        what: 'A savoury buckwheat crêpe from Brittany, usually with egg and cheese. Naturally wheat-free.',
        whatAr: 'كريب حنطة سوداء مالح من بريتاني، غالباً ببيضة وجبنة. خالي من القمح بطبيعته.' },
      { name: 'Ratatouille', nameAr: 'راتاتوي',
        what: 'Aubergine, courgette, pepper and tomato cooked down in olive oil. A poor man’s dish from Nice that went global.',
        whatAr: 'باذنجان وكوسة وفلفل وطماطم متطبخين في زيت زيتون. أكلة الغلابة من نيس اللي بقت عالمية.' },
      { name: 'Tarte tatin', nameAr: 'تارت تاتان',
        what: 'An upside-down caramelised apple tart, invented by accident. Eaten warm.',
        whatAr: 'تارت تفاح مقلوبة بكراميل، اتخترعت بالغلط. بتتاكل دافية.' },
    ],
    know: [
      { title: 'Say bonjour first or nothing else works',
        titleAr: 'قول bonjour الأول وإلا مفيش حاجة هتمشي',
        body: 'Walking into a shop and starting with a question reads as rude in a way that is hard to overstate. One word fixes it.',
        bodyAr: 'إنك تدخل محل وتبدأ بسؤال ده بيتقري قلة ذوق بشكل صعب توصفه. كلمة واحدة بتصلّح ده كله.' },
      { title: 'Tap water is free and you can ask for it',
        titleAr: 'مياه الحنفية ببلاش وتقدر تطلبها',
        body: 'A restaurant must give you a carafe d’eau at no charge. Bottled water on the table is a choice, not the only option.',
        bodyAr: 'المطعم لازم يديك شفشق مياه ببلاش. المياه المعدنية على الترابيزة اختيار، مش الحل الوحيد.' },
      { title: 'Service is already included',
        titleAr: 'الخدمة أصلاً محسوبة',
        body: 'By law. Rounding up a euro or two is kind; fifteen percent is not expected and marks you as a visitor.',
        bodyAr: 'بالقانون. إنك تقرّب يورو أو اتنين ده لطف؛ خمستاشر في المية مش متوقعة وبتبيّن إنك زائر.' },
    ],
    hear: [
      { title: 'Non, je ne regrette rien', artist: 'Édith Piaf', year: '1960',
        why: 'The voice France exports. Recorded two years before she died.',
        whyAr: 'الصوت اللي فرنسا بتصدّره. اتسجلت قبل وفاتها بسنتين.' },
      { title: 'Ne me quitte pas', artist: 'Jacques Brel', year: '1959',
        why: 'Belgian, sung in French, and the most covered song in the language.',
        whyAr: 'بلجيكي، بيغني بالفرنساوي، وأكتر أغنية اتعادت في اللغة دي.' },
      { title: 'Anything of his', artist: 'Georges Brassens', year: '1952–1976',
        why: 'The songwriter French people quote the way Arabs quote poetry.',
        whyAr: 'المؤلف اللي الفرنسيين بيستشهدوا بيه زي ما العرب بيستشهدوا بالشعر.' },
    ],
  },
  {
    code: 'DE', name: 'Germany', nameAr: 'ألمانيا',
    lang: 'German', langAr: 'الألمانية', filmLang: 'de',
    hello: {
      native: 'Hallo', how: 'HAH-lo',
      means: 'Fine everywhere. But Bavaria says Servus, Hamburg says Moin, and Moin works at any hour of the day despite sounding like "morning".',
      meansAr: 'بتنفع في كل مكان. بس بافاريا بتقول Servus، وهامبورج بتقول Moin — وMoin بتنفع في أي وقت في اليوم رغم إنها شبه كلمة "صباح".',
      bye: { native: 'Tschüss', how: 'chooss',
             means: 'Said to have travelled from the Spanish adiós, through the Walloon adjuus, into the north German ports and out across the country.',
             meansAr: 'بيقولوا إنها سافرت من الإسبانية adiós، عن طريق الوالونية adjuus، لموانئ شمال ألمانيا وبعدين للبلد كلها.' },
    },
    warm: [
      { native: 'Freut mich', how: 'froyt mikh', en: 'Pleased to meet you — literally "it pleases me"', ar: 'تشرفنا — حرفياً "ده بيسعدني"', when: 'A first handshake', whenAr: 'أول سلام' },
      { native: 'Prost!', how: 'prohst', en: 'Cheers — and you must make eye contact, or the superstition says seven years of bad luck', ar: 'في صحتك — ولازم تبص في عينه، وإلا الخرافة بتقول سبع سنين نحس', when: 'Every single glass', whenAr: 'كل كباية من غير استثناء' },
      { native: 'Guten Appetit', how: 'GOO-ten ah-peh-TEET', en: 'Good appetite', ar: 'بالهنا والشفا', when: 'Before eating', whenAr: 'قبل الأكل' },
      { native: 'Gern geschehen', how: 'gairn geh-SHEH-en', en: 'You are welcome — literally "gladly done"', ar: 'العفو — حرفياً "اتعمل بكل سرور"', when: 'After a thank you', whenAr: 'بعد الشكر' },
    ],
    say: [
      { g: 'first', native: 'Hallo',       how: 'HAH-lo',           en: 'Hi',                             ar: 'أهلاً' },
      { g: 'first', native: 'Guten Tag',   how: 'GOO-ten TAHK',     en: 'Good day — the safe polite one', ar: 'نهارك سعيد — الرسمية المضمونة' },
      { g: 'first', native: 'Danke',       how: 'DAN-keh',          en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Entschuldigung', how: 'ent-SHOOL-dee-goong', en: 'Sorry / excuse me',        ar: 'آسف / لو سمحت' },
      { g: 'eat',   native: 'Einen Kaffee, bitte', how: 'EYE-nen KAH-feh BIT-teh', en: 'One coffee, please', ar: 'قهوة واحدة، من فضلك' },
      { g: 'eat',   native: 'Leitungswasser', how: 'LYE-toongs-vas-ser', en: 'Tap water — you often have to ask by name', ar: 'مياه الحنفية — غالباً لازم تطلبها بالاسم' },
      { g: 'eat',   native: 'Ohne Fleisch', how: 'OH-neh FLYSH',    en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Zahlen, bitte', how: 'TSAH-len BIT-teh', en: 'The bill, please',             ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Wo ist…?',    how: 'vo IST',           en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Was kostet das?', how: 'vas KOS-tet das', en: 'How much is it?',             ar: 'بكام؟' },
      { g: 'help',  native: 'Sprechen Sie Englisch?', how: 'SHPREH-khen zee ENG-lish', en: 'Do you speak English?', ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Hilfe!',      how: 'HIL-feh',          en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Döner', nameAr: 'دونر',
        what: 'Invented in Berlin by Turkish workers in the 1970s. It is the national fast food now, and there is a lamb or chicken version everywhere.',
        whatAr: 'اتخترع في برلين على إيد عمال أتراك في السبعينات. بقى الأكل السريع الوطني، وفيه نسخة لحمة ضاني أو فراخ في كل مكان.' },
      { name: 'Brot', nameAr: 'العيش الألماني',
        what: 'Germany takes bread more seriously than almost anywhere: hundreds of registered kinds, dark, sour and dense.',
        whatAr: 'ألمانيا بتاخد العيش بجدية أكتر من أي مكان تقريباً: مئات الأنواع المسجلة، غامق وحامض وتقيل.' },
      { name: 'Spätzle', nameAr: 'شبيتسله',
        what: 'Soft egg noodles from the south, usually with cheese and fried onion. The comfort food.',
        whatAr: 'مكرونة بيض طرية من الجنوب، غالباً بجبنة وبصل محمر. أكلة الراحة.' },
      { name: 'Apfelschorle', nameAr: 'أبفلشورله',
        what: 'Apple juice cut with sparkling water. Ordered more than beer in the daytime and nobody thinks it is odd.',
        whatAr: 'عصير تفاح مخلوط بمياه غازية. بيتطلب أكتر من البيرة في النهار ومحدش شايفها غريبة.' },
    ],
    know: [
      { title: 'Sunday, almost everything is shut',
        titleAr: 'يوم الأحد كل حاجة تقريباً مقفولة',
        body: 'Supermarkets, most shops, by law. Shop on Saturday or your Sunday is a petrol-station sandwich.',
        bodyAr: 'السوبر ماركت وأغلب المحلات، بالقانون. اتسوّق السبت وإلا أحدك هيبقى ساندوتش من محطة بنزين.' },
      { title: 'Cash still wins in a lot of places',
        titleAr: 'الكاش لسه هو الأساس في أماكن كتير',
        body: 'Small bars, bakeries and even some restaurants are cash-only. Carry some; "card only" is not a safe assumption here.',
        bodyAr: 'البارات الصغيرة والمخابز وحتى بعض المطاعم كاش بس. خلي معاك فلوس؛ "بالكارت بس" مش افتراض آمن هنا.' },
      { title: 'Do not cross on a red light',
        titleAr: 'ما تعديش على الإشارة الحمرا',
        body: 'Even with no car in sight. Someone will tell you off, usually on behalf of a child who is watching.',
        bodyAr: 'حتى لو مفيش عربية في الأفق. حد هيلومك، وغالباً باسم طفل واقف بيتفرج.' },
    ],
    hear: [
      { title: 'Autobahn', artist: 'Kraftwerk', year: '1974',
        why: 'Four men from Düsseldorf who quietly invented most of electronic music.',
        whyAr: 'أربع رجالة من دوسلدورف اخترعوا في هدوء أغلب الموسيقى الإلكترونية.' },
      { title: '99 Luftballons', artist: 'Nena', year: '1983',
        why: 'A Cold War protest song that became a global hit by accident.',
        whyAr: 'أغنية احتجاج من الحرب الباردة بقت هيت عالمي بالصدفة.' },
      { title: 'Anything of his', artist: 'Herbert Grönemeyer', year: 'since 1984',
        why: 'The best-selling German-language artist there has ever been.',
        whyAr: 'أكتر فنان باللغة الألمانية بيع في التاريخ.' },
    ],
  },
  {
    code: 'PT', name: 'Portugal', nameAr: 'البرتغال',
    lang: 'Portuguese', langAr: 'البرتغالية', filmLang: 'pt',
    hello: {
      native: 'Olá', how: 'oh-LAH',
      means: 'The everyday hello. Portuguese also greets by time of day far more than English does — bom dia, boa tarde, boa noite, and people notice which one you pick.',
      meansAr: 'السلام اليومي. والبرتغالية بتسلم حسب وقت اليوم أكتر بكتير من الإنجليزية — bom dia وboa tarde وboa noite، والناس بتلاحظ إنت اخترت أنهي واحدة.',
      bye: { native: 'Adeus', how: 'ah-DEH-oosh',
             means: 'Literally "to God" — a dele. It carries some finality; até logo, "until soon", is the lighter one.',
             meansAr: 'حرفياً "لله". وفيها إحساس بالنهاية؛ وaté logo يعني "لحد قريب" وهي الأخف.' },
    },
    warm: [
      { native: 'Muito prazer', how: 'MOOY-toh pra-ZAIR', en: 'Pleased to meet you — literally "much pleasure"', ar: 'تشرفنا — حرفياً "متعة كبيرة"', when: 'A first meeting', whenAr: 'أول لقاء' },
      { native: 'Saúde!', how: 'sah-OO-deh', en: 'Cheers — "health"', ar: 'في صحتك — "صحة"', when: 'A toast, or a sneeze', whenAr: 'نخب، أو عطسة' },
      { native: 'Bom apetite', how: 'bom ah-peh-TEE-teh', en: 'Good appetite', ar: 'بالهنا والشفا', when: 'Before eating', whenAr: 'قبل الأكل' },
      { native: 'De nada', how: 'deh NAH-da', en: 'You are welcome — "of nothing"', ar: 'العفو — "من لا شيء"', when: 'After a thank you', whenAr: 'بعد الشكر' },
    ],
    say: [
      { g: 'first', native: 'Olá',         how: 'oh-LAH',           en: 'Hi',                             ar: 'أهلاً' },
      { g: 'first', native: 'Bom dia',     how: 'bom DEE-ah',       en: 'Good morning',                   ar: 'صباح الخير' },
      { g: 'first', native: 'Obrigado / Obrigada', how: 'oh-bree-GAH-doo / -dah', en: 'Thank you — the first if you are male, the second if female', ar: 'شكراً — الأولى لو انت راجل والتانية لو ست' },
      { g: 'first', native: 'Desculpe',    how: 'desh-KOOL-peh',    en: 'Sorry / excuse me',              ar: 'آسف / لو سمحت' },
      { g: 'eat',   native: 'Um café, por favor', how: 'oom kah-FEH poor fah-VOR', en: 'One coffee, please — an espresso, called a bica in Lisbon', ar: 'قهوة واحدة من فضلك — إسبريسو، واسمها bica في لشبونة' },
      { g: 'eat',   native: 'Água da torneira', how: 'AH-gwa da tor-NAY-ra', en: 'Tap water',              ar: 'مياه الحنفية' },
      { g: 'eat',   native: 'Sem carne',   how: 'seng KAR-neh',     en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'A conta, por favor', how: 'ah KON-ta poor fah-VOR', en: 'The bill, please',   ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Onde é…?',    how: 'ON-deh EH',        en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Quanto custa?', how: 'KWAN-too KOOSH-ta', en: 'How much is it?',             ar: 'بكام؟' },
      { g: 'help',  native: 'Fala inglês?', how: 'FAH-la een-GLESH', en: 'Do you speak English?',         ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Socorro!',    how: 'soo-KOR-roo',      en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Bacalhau', nameAr: 'باكالياو',
        what: 'Salt cod. Portugal claims a way to cook it for every day of the year and is only slightly exaggerating.',
        whatAr: 'سمك قد مملح. البرتغال بتقول إن عندها طريقة لطبخه لكل يوم في السنة، وبتبالغ شوية بس.' },
      { name: 'Pastel de nata', nameAr: 'باستيل دي ناتا',
        what: 'A custard tart with a burnt top, eaten warm with cinnamon. Invented by monks in Belém.',
        whatAr: 'تارت كاسترد بوش محروق، بتتاكل دافية بقرفة. اخترعها رهبان في بيليم.' },
      { name: 'Francesinha', nameAr: 'فرانسيزينيا',
        what: 'A Porto sandwich of several meats under melted cheese and a beer sauce. Enormous, and not a light lunch.',
        whatAr: 'ساندوتش من بورتو بأنواع لحوم تحت جبنة سايحة وصوص بيرة. ضخم، ومش غدا خفيف.' },
      { name: 'Caldo verde', nameAr: 'كالدو فيردي',
        what: 'Potato soup with shredded kale and a slice of sausage. What is served at every wedding and every festival.',
        whatAr: 'شوربة بطاطس بكرنب مقطع ورقة سجق. بتتقدم في كل فرح وكل مهرجان.' },
    ],
    know: [
      { title: 'The starters you did not order are not free',
        titleAr: 'المقبلات اللي ما طلبتهاش مش ببلاش',
        body: 'Bread, olives and cheese arrive unasked — couvert. Eat them and they go on the bill. Send them back and nobody minds.',
        bodyAr: 'العيش والزيتون والجبنة بييجوا من غير ما تطلب — اسمها couvert. لو أكلتها هتتحسب عليك. ولو رجعتها محدش هيزعل.' },
      { title: 'Coffee is standing up and quick',
        titleAr: 'القهوة واقف وبسرعة',
        body: 'Order at the counter, drink it in a minute, pay, leave. The whole thing costs about a euro.',
        bodyAr: 'اطلب من الكاونتر، اشربها في دقيقة، ادفع، امشي. الحكاية كلها بحوالي يورو.' },
      { title: 'Saudade is a real word and they will use it',
        titleAr: 'saudade كلمة حقيقية وهيستعملوها',
        body: 'Longing for something that is gone, or that never was. It explains the music, and people mean it seriously.',
        bodyAr: 'حنين لحاجة راحت، أو لحاجة ماكانتش أصلاً. بتفسر الموسيقى، والناس بتقصدها بجد.' },
    ],
    hear: [
      { title: 'Fado', artist: 'Amália Rodrigues', year: '1940s–1990s',
        why: 'She is the reason fado is on the UNESCO list. Start with her and go anywhere after.',
        whyAr: 'هي السبب إن الفادو في قايمة اليونسكو. ابدأ بيها وبعدها روح فين ما تحب.' },
      { title: 'Anything of hers', artist: 'Mariza', year: 'since 1999',
        why: 'Fado now — the same ache, a modern room.',
        whyAr: 'الفادو دلوقتي — نفس الوجع، في غرفة عصرية.' },
      { title: 'Grândola, Vila Morena', artist: 'José Afonso', year: '1971',
        why: 'The song broadcast as the signal to start the 1974 revolution. Still sung at protests.',
        whyAr: 'الأغنية اللي اتذاعت كإشارة لبدء ثورة ١٩٧٤. لسه بتتغنى في المظاهرات.' },
    ],
  },
  {
    code: 'NL', name: 'Netherlands', nameAr: 'هولندا',
    lang: 'Dutch', langAr: 'الهولندية', filmLang: 'nl',
    hello: {
      native: 'Hoi', how: 'hoy',
      means: 'The short, friendly one. Hallo is fine too, and goedemorgen is what you say to a shopkeeper before nine.',
      meansAr: 'القصيرة الودّية. وHallo كويسة برضه، وgoedemorgen هي اللي بتقولها لصاحب المحل قبل التسعة.',
      bye: { native: 'Tot ziens', how: 'tot ZEENS',
             means: 'Literally "until seeing". Doei is the casual one and sounds like "doo-ee".',
             meansAr: 'حرفياً "لحد الشوفة". وDoei هي الودّية وبتتنطق "دووي".' },
    },
    warm: [
      { native: 'Aangenaam', how: 'AHN-kheh-nahm', en: 'Pleased to meet you — literally "agreeable"', ar: 'تشرفنا — حرفياً "مستحبّ"', when: 'A first handshake', whenAr: 'أول سلام' },
      { native: 'Proost!', how: 'prohst', en: 'Cheers', ar: 'في صحتك', when: 'Raising a glass', whenAr: 'وانت رافع الكباية' },
      { native: 'Eet smakelijk', how: 'ayt SMAH-keh-luk', en: 'Enjoy your meal — literally "eat tastily"', ar: 'بالهنا والشفا — حرفياً "كُل بطعم"', when: 'Before eating', whenAr: 'قبل الأكل' },
      { native: 'Geen probleem', how: 'khayn pro-BLAYM', en: 'No problem — the everyday you-are-welcome', ar: 'ولا يهمك — العفو اليومية', when: 'After a thank you', whenAr: 'بعد الشكر' },
    ],
    say: [
      { g: 'first', native: 'Hoi',         how: 'hoy',              en: 'Hi',                             ar: 'أهلاً' },
      { g: 'first', native: 'Goedemorgen', how: 'KHOO-deh-mor-khen', en: 'Good morning',                  ar: 'صباح الخير' },
      { g: 'first', native: 'Dank je wel', how: 'dank yuh VEL',     en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Sorry',       how: 'SOR-ry',           en: 'Sorry — the Dutch use the English word', ar: 'آسف — الهولنديين بيستعملوا الكلمة الإنجليزية' },
      { g: 'eat',   native: 'Een koffie, alsjeblieft', how: 'un KOF-fee AL-shuh-bleeft', en: 'One coffee, please', ar: 'قهوة واحدة، من فضلك' },
      { g: 'eat',   native: 'Kraanwater',  how: 'KRAHN-vah-ter',    en: 'Tap water',                      ar: 'مياه الحنفية' },
      { g: 'eat',   native: 'Zonder vlees', how: 'ZON-der VLAYS',   en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Mag ik afrekenen?', how: 'makh ik AF-ray-ken-en', en: 'Can I pay?',           ar: 'ممكن أدفع؟' },
      { g: 'go',    native: 'Waar is…?',   how: 'vahr is',          en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Hoeveel kost het?', how: 'HOO-vayl kost het', en: 'How much is it?',         ar: 'بكام؟' },
      { g: 'help',  native: 'Spreekt u Engels?', how: 'spraykt oo ENG-els', en: 'Do you speak English? — they almost all do', ar: 'بتتكلم إنجليزي؟ — كلهم تقريباً بيتكلموا' },
      { g: 'help',  native: 'Help!',       how: 'help',             en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Stroopwafel', nameAr: 'ستروبفافل',
        what: 'Two thin waffles glued with caramel syrup. Buy them warm off a market stall, not in a packet.',
        whatAr: 'وافلتين رفيعين ملزوقين بشيرة كراميل. اشتريها سخنة من عربية في السوق، مش معلبة.' },
      { name: 'Haring', nameAr: 'هارينج',
        what: 'Raw salted herring with onion, held by the tail and eaten in one go. A test you can pass.',
        whatAr: 'سمك رنجة نيّة مملحة ببصل، بتمسكها من ديلها وتاكلها مرة واحدة. اختبار تقدر تنجح فيه.' },
      { name: 'Bitterballen', nameAr: 'بيترباللن',
        what: 'Crunchy fried balls of beef ragù, served with mustard. What arrives with the first round of drinks.',
        whatAr: 'كور مقلية مقرمشة محشية لحمة، بتتقدم بمسطردة. بتيجي مع أول جولة مشروبات.' },
      { name: 'Kapsalon', nameAr: 'كابسالون',
        what: 'Chips, shawarma, cheese and salad in one tray. Invented in Rotterdam by a barber, hence the name.',
        whatAr: 'بطاطس وشاورما وجبنة وسلطة في صينية واحدة. اخترعها حلاق في روتردام، ومن هنا الاسم.' },
    ],
    know: [
      { title: 'The bike lane is not the pavement',
        titleAr: 'حارة العجل مش الرصيف',
        body: 'Standing in it is the single fastest way to be shouted at in this country. The red asphalt is theirs.',
        bodyAr: 'إنك تقف فيها أسرع طريقة تتزعق لك في البلد دي. الأسفلت الأحمر بتاعهم.' },
      { title: 'Directness is not rudeness',
        titleAr: 'الصراحة مش قلة أدب',
        body: 'You will be told plainly that your idea is bad. It is not personal and it is not an argument; it is the culture.',
        bodyAr: 'هيقولولك بصراحة إن فكرتك وحشة. مش شخصي ومش خناقة؛ دي ثقافة البلد.' },
      { title: 'Going Dutch is literal',
        titleAr: '"كل واحد يدفع" هنا حرفية',
        body: 'Splitting a bill to the cent is completely normal, including on a date, and there is an app everyone uses for it.',
        bodyAr: 'تقسيم الحساب للقرش الأخير طبيعي تماماً، حتى في الخروجة، وفيه تطبيق الكل بيستعمله لكده.' },
    ],
    hear: [
      { title: 'Radar Love', artist: 'Golden Earring', year: '1973',
        why: 'The Dutch rock song the whole world knows without knowing it is Dutch.',
        whyAr: 'أغنية الروك الهولندية اللي الدنيا كلها تعرفها من غير ما تعرف إنها هولندية.' },
      { title: 'Anything of his', artist: 'André Hazes', year: '1976–2004',
        why: 'Levenslied — the working-class Dutch song. Sung in football stadiums to this day.',
        whyAr: 'الـ levenslied — أغنية الطبقة الشعبية الهولندية. لسه بتتغنى في استادات الكورة لحد النهاردة.' },
      { title: 'Anything of theirs', artist: 'Focus', year: '1970s',
        why: 'Progressive rock with yodelling. Strange, brilliant, and entirely Dutch.',
        whyAr: 'روك تقدمي مع تهليل. غريبة وعبقرية وهولندية تماماً.' },
    ],
  },
  {
    code: 'RO', name: 'Romania', nameAr: 'رومانيا',
    lang: 'Romanian', langAr: 'الرومانية', filmLang: 'ro',
    hello: {
      native: 'Salut', how: 'sa-LOOT',
      means: 'Straight from the Latin salus — health, safety, wellbeing. Romanian kept the Latin word where most of its neighbours did not.',
      meansAr: 'جاية على طول من اللاتينية salus — صحة وأمان وعافية. الرومانية احتفظت بالكلمة اللاتينية في وقت جيرانها ما احتفظوش بيها.',
      bye: { native: 'La revedere', how: 'la reh-veh-DEH-reh',
             means: 'Literally "until the re-seeing" — the same idea as the French au revoir, from the same Latin root.',
             meansAr: 'حرفياً "لحد الشوفة الجاية" — نفس فكرة au revoir الفرنسية، ومن نفس الأصل اللاتيني.' },
    },
    warm: [
      { native: 'Îmi pare bine', how: 'uhm PAH-reh BEE-neh', en: 'Pleased to meet you — literally "it seems good to me"', ar: 'تشرفنا — حرفياً "ده باين لي كويس"', when: 'A first meeting', whenAr: 'أول لقاء' },
      { native: 'Noroc!', how: 'no-ROK', en: 'Cheers — literally "luck"', ar: 'في صحتك — حرفياً "حظ"', when: 'Every glass', whenAr: 'كل كباية' },
      { native: 'Poftă bună', how: 'POF-tuh BOO-nuh', en: 'Good appetite', ar: 'بالهنا والشفا', when: 'Before eating', whenAr: 'قبل الأكل' },
      { native: 'Cu plăcere', how: 'koo pluh-CHEH-reh', en: 'You are welcome — "with pleasure"', ar: 'العفو — "بكل سرور"', when: 'After a thank you', whenAr: 'بعد الشكر' },
    ],
    say: [
      { g: 'first', native: 'Bună',        how: 'BOO-nuh',          en: 'Hi',                             ar: 'أهلاً' },
      { g: 'first', native: 'Bună ziua',   how: 'BOO-nuh ZEE-wa',   en: 'Good day — the polite one',      ar: 'نهارك سعيد — الرسمية' },
      { g: 'first', native: 'Mulțumesc',   how: 'mool-tsoo-MESK',   en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Scuze',       how: 'SKOO-zeh',         en: 'Sorry',                          ar: 'آسف' },
      { g: 'eat',   native: 'O cafea, vă rog', how: 'oh ka-FYA vuh ROG', en: 'One coffee, please',        ar: 'قهوة واحدة، من فضلك' },
      { g: 'eat',   native: 'Apă de la robinet', how: 'AH-puh deh la ro-bee-NET', en: 'Tap water',         ar: 'مياه الحنفية' },
      { g: 'eat',   native: 'Fără carne',  how: 'FUH-ruh KAR-neh',  en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Nota, vă rog', how: 'NO-ta vuh ROG',   en: 'The bill, please',               ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Unde este…?', how: 'OON-deh YES-teh',  en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Cât costă?',  how: 'kuht KOS-tuh',     en: 'How much is it?',                ar: 'بكام؟' },
      { g: 'help',  native: 'Vorbiți engleză?', how: 'vor-BEETS en-GLEH-zuh', en: 'Do you speak English?', ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Ajutor!',     how: 'ah-zhoo-TOR',      en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Sarmale', nameAr: 'محشي ورق عنب/كرنب',
        what: 'Cabbage or vine leaves rolled around minced meat and rice. If you know محشي, this is the same idea, cooked slower.',
        whatAr: 'ورق كرنب أو عنب ملفوف على لحمة مفرومة ورز. لو تعرف المحشي، دي نفس الفكرة بس بتتطبخ أبطأ.' },
      { name: 'Mămăligă', nameAr: 'مامالِيجا',
        what: 'Cornmeal porridge, served instead of bread, usually with sour cream and salty cheese.',
        whatAr: 'عصيدة دقيق ذرة، بتتقدم بدل العيش، غالباً بقشدة حامضة وجبنة مالحة.' },
      { name: 'Ciorbă', nameAr: 'تشوربا',
        what: 'A sour soup, sharpened with fermented wheat bran. Eaten before almost every main meal.',
        whatAr: 'شوربة حامضة، بتتحمّض بنخالة قمح مخمرة. بتتاكل قبل كل وجبة رئيسية تقريباً.' },
      { name: 'Papanași', nameAr: 'بابانَش',
        what: 'Fried cheese doughnuts with sour cream and jam. Ordered by two people and finished by neither.',
        whatAr: 'دوناتس جبنة مقلية بقشدة حامضة ومربى. اتنين بيطلبوها وولا واحد فيهم بيخلصها.' },
    ],
    know: [
      { title: 'Take your shoes off at the door',
        titleAr: 'اقلع جزمتك عند الباب',
        body: 'Always, in every home. Slippers will be handed to you and refusing them is odd.',
        bodyAr: 'دايماً، في كل بيت. هيدولك شبشب ورفضه حاجة غريبة.' },
      { title: 'Never give an even number of flowers',
        titleAr: 'ما تديش عدد زوجي من الورد',
        body: 'Even numbers are for funerals. Odd numbers for everything else, and it matters.',
        bodyAr: 'الأعداد الزوجية للجنازات. الفردية لأي حاجة تانية، والحكاية دي بتفرق.' },
      { title: 'Romanian is a Latin language',
        titleAr: 'الرومانية لغة لاتينية',
        body: 'Not Slavic. If you have any Italian, Spanish or French, you will understand more than you expect.',
        bodyAr: 'مش سلافية. لو معاك أي إيطالي أو إسباني أو فرنساوي هتفهم أكتر مما تتخيل.' },
    ],
    hear: [
      { title: 'Doina', artist: 'Maria Tănase', year: '1930s–1960s',
        why: 'The voice of Romanian folk song, and the reason much of it was written down at all.',
        whyAr: 'صوت الأغنية الشعبية الرومانية، والسبب إن كتير منها اتكتب أصلاً.' },
      { title: 'Ciocârlia (The Lark)', artist: 'traditional, pan flute',
        year: 'trad.',
        why: 'A folk showpiece that imitates a skylark. Every Romanian musician can play it.',
        whyAr: 'قطعة شعبية استعراضية بتقلد صوت عصفور. كل موسيقي روماني بيعرف يعزفها.' },
      { title: 'Dragostea din tei', artist: 'O-Zone', year: '2003',
        why: 'Moldovan, sung in Romanian, and briefly the most-heard song on earth.',
        whyAr: 'مولدوفية، متغنية بالروماني، وكانت لفترة أكتر أغنية اتسمعت على الأرض.' },
    ],
  },
  {
    code: 'PL', name: 'Poland', nameAr: 'بولندا',
    lang: 'Polish', langAr: 'البولندية', filmLang: 'pl',
    hello: {
      native: 'Cześć', how: 'cheshch',
      means: 'The same word as cześć meaning honour or reverence — you are literally saying "honour" to somebody. Hard to pronounce and worth the try; people light up when a foreigner attempts it.',
      meansAr: 'نفس كلمة cześć اللي معناها شرف أو إجلال — يعني إنت حرفياً بتقول "شرف" لحد. صعبة في النطق وتستاهل المحاولة؛ الناس بتفرح لما أجنبي يحاول.',
      bye: { native: 'Do widzenia', how: 'do vee-DZEH-nya',
             means: 'Literally "until the seeing". The polite one; cześć works on the way out between friends.',
             meansAr: 'حرفياً "لحد الشوفة". دي الرسمية؛ وcześć بتنفع وانت خارج بين الأصحاب.' },
    },
    warm: [
      { native: 'Miło mi', how: 'MEE-wo mee', en: 'Pleased to meet you — literally "it is pleasant to me"', ar: 'تشرفنا — حرفياً "ده لطيف بالنسبة لي"', when: 'A first handshake', whenAr: 'أول سلام' },
      { native: 'Na zdrowie!', how: 'na ZDRO-vyeh', en: 'Cheers — "to health". Also what you say when someone sneezes', ar: 'في صحتك — "للصحة". وبتتقال كمان لما حد يعطس', when: 'Toasts and sneezes', whenAr: 'النخب والعطس' },
      { native: 'Smacznego', how: 'smach-NEH-go', en: 'Enjoy your meal', ar: 'بالهنا والشفا', when: 'Before eating', whenAr: 'قبل الأكل' },
      { native: 'Nie ma za co', how: 'nyeh ma za tso', en: 'You are welcome — "there is nothing to thank for"', ar: 'العفو — "مفيش حاجة تستاهل الشكر"', when: 'After a thank you', whenAr: 'بعد الشكر' },
    ],
    say: [
      { g: 'first', native: 'Cześć',       how: 'cheshch',          en: 'Hi',                             ar: 'أهلاً' },
      { g: 'first', native: 'Dzień dobry', how: 'jane DOB-ry',      en: 'Good day — use this with strangers', ar: 'نهارك سعيد — استعملها مع الغرب' },
      { g: 'first', native: 'Dziękuję',    how: 'jen-KOO-yeh',      en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Przepraszam', how: 'psheh-PRAH-sham',  en: 'Sorry / excuse me',              ar: 'آسف / لو سمحت' },
      { g: 'eat',   native: 'Kawa, proszę', how: 'KAH-va PRO-sheh', en: 'Coffee, please',                 ar: 'قهوة، من فضلك' },
      { g: 'eat',   native: 'Woda z kranu', how: 'VO-da z KRA-noo', en: 'Tap water',                      ar: 'مياه الحنفية' },
      { g: 'eat',   native: 'Bez mięsa',   how: 'bez MYEN-sa',      en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Rachunek, proszę', how: 'ra-HOO-nek PRO-sheh', en: 'The bill, please',       ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Gdzie jest…?', how: 'g-jeh yest',      en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Ile to kosztuje?', how: 'EE-leh to kosh-TOO-yeh', en: 'How much is it?',     ar: 'بكام؟' },
      { g: 'help',  native: 'Mówisz po angielsku?', how: 'MOO-vish po an-GYEL-skoo', en: 'Do you speak English?', ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Pomocy!',     how: 'po-MO-tsy',        en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Pierogi', nameAr: 'بيروجي',
        what: 'Filled dumplings — potato and cheese, meat, or cabbage and mushroom. Boiled, then fried if you are lucky.',
        whatAr: 'عجينة محشية — بطاطس وجبنة، أو لحمة، أو كرنب وعيش غراب. بتتسلق، وبتتحمر لو انت محظوظ.' },
      { name: 'Żurek', nameAr: 'جوريك',
        what: 'Sour rye soup, often served in a hollowed loaf with egg and sausage. Strange the first time, then not.',
        whatAr: 'شوربة شيلم حامضة، غالباً بتتقدم في رغيف مفرّغ ببيضة وسجق. غريبة أول مرة، وبعدين خلاص.' },
      { name: 'Bigos', nameAr: 'بيجوس',
        what: 'Hunter’s stew of sauerkraut, cabbage and several meats, better every time it is reheated.',
        whatAr: 'يخنة الصيادين من كرنب مخلل وكرنب وأنواع لحوم، وبتبقى أحسن كل ما تتسخن.' },
      { name: 'Zapiekanka', nameAr: 'زابيكانكا',
        what: 'Half a baguette with mushrooms and cheese under the grill. The late-night food of Kraków.',
        whatAr: 'نص باجيت بعيش غراب وجبنة تحت الشوّاية. أكلة آخر الليل في كراكوف.' },
    ],
    know: [
      { title: 'Dzień dobry is not optional',
        titleAr: 'Dzień dobry مش اختيارية',
        body: 'You greet the whole room when you walk into a small shop, a waiting room or a lift. Silence reads as hostile.',
        bodyAr: 'بتسلم على الأوضة كلها لما تدخل محل صغير أو غرفة انتظار أو أسانسير. السكوت بيتفهم عدائي.' },
      { title: 'Milk bars are real and very cheap',
        titleAr: 'بارات اللبن حقيقية ورخيصة جداً',
        body: 'Bar mleczny — subsidised canteens left from the communist era, still serving a full plate for a couple of euros.',
        bodyAr: 'Bar mleczny — مطاعم مدعومة باقية من الحقبة الشيوعية، لسه بتقدم طبق كامل بيورو أو اتنين.' },
      { title: 'Name days again, and vodka is a toast not a drink',
        titleAr: 'أيام الأسماء برضه، والفودكا نخب مش مشروب',
        body: 'It is drunk in one, together, with a reason said out loud first. Sipping it alone is what a tourist does.',
        bodyAr: 'بتتشرب مرة واحدة، مع بعض، وبعد ما حد يقول السبب بصوت عالي. اللي بيرشفها لوحده ده سايح.' },
    ],
    hear: [
      { title: 'Nocturnes', artist: 'Fryderyk Chopin', year: '1830s',
        why: 'Poland’s most exported human being. There are free public concerts in Warsaw all summer.',
        whyAr: 'أكتر إنسان بولندا صدّرته. وفيه حفلات مجانية في وارسو طول الصيف.' },
      { title: 'Anything of hers', artist: 'Anna Maria Jopek', year: 'since 1997',
        why: 'Polish jazz and folk together; she recorded a whole album with Pat Metheny.',
        whyAr: 'جاز بولندي وفولكلور مع بعض؛ عملت ألبوم كامل مع بات ميثيني.' },
      { title: 'Anything of theirs', artist: 'Myslovitz', year: '1990s–2000s',
        why: 'The band a whole Polish generation grew up on.',
        whyAr: 'الفرقة اللي جيل بولندي كامل اتربى عليها.' },
    ],
  },
  {
    code: 'CZ', name: 'Czechia', nameAr: 'التشيك',
    lang: 'Czech', langAr: 'التشيكية', filmLang: 'cs',
    hello: {
      native: 'Ahoj', how: 'AH-hoy',
      means: 'The sailors\u2019 hail — the same word as the English "ahoy". A landlocked country greets each other like sailors, and Czechs enjoy that about themselves: it is said to have come off the river, from the rowers and canoeists on the Vltava a century ago.',
      meansAr: 'نداء البحارة — نفس كلمة "ahoy" الإنجليزية. بلد مالهاش بحر بتسلم على بعضها زي البحارة، والتشيك بيستظرفوا ده في نفسهم: بيقولوا إنها جات من النهر، من المجدّفين على نهر الفلتافا من حوالي قرن.',
      bye: { native: 'Na shledanou', how: 'nas-KHLEH-da-noh',
             means: 'Literally "until the seeing again". Say ahoj on the way out too if you are being casual.',
             meansAr: 'حرفياً "لحد ما نتشاف تاني". وتقدر تقول ahoj وانت خارج كمان لو الجو ودّي.' },
    },
    warm: [
      { native: 'Těší mě', how: 'TYEH-shee myeh', en: 'Pleased to meet you — literally "it pleases me"', ar: 'تشرفنا — حرفياً "ده بيسعدني"', when: 'The first time you shake a hand', whenAr: 'أول مرة تسلم على حد' },
      { native: 'Na zdraví!', how: 'na ZDRA-vee', en: 'Cheers — literally "to health". Look them in the eye, or it does not count', ar: 'في صحتك — حرفياً "للصحة". بصله في عينه وإلا مش محسوبة', when: 'Every glass, every time', whenAr: 'مع كل كباية، كل مرة' },
      { native: 'Dobrou chuť', how: 'DOB-roh khoot', en: 'Good appetite — said to anyone about to eat, even a stranger', ar: 'بالهنا والشفا — بتتقال لأي حد رايح ياكل، حتى لو ما تعرفوش', when: 'Before the first bite, always', whenAr: 'قبل أول لقمة، دايماً' },
      { native: 'Není zač', how: 'NEH-nee zach', en: 'You are welcome — literally "there is nothing to thank for"', ar: 'العفو — حرفياً "مفيش حاجة تستاهل الشكر"', when: 'When they thank you', whenAr: 'لما يشكروك' },
      { native: 'Jak se máš?', how: 'yak seh MAASH', en: 'How are you? — and they will answer honestly, which surprises people', ar: 'إزيك؟ — وهيردوا عليك بصراحة، وده بيفاجئ الناس', when: 'With someone you already know', whenAr: 'مع حد تعرفه' },
    ],
    say: [
      { g: 'first', native: 'Ahoj',        how: 'AH-hoy',           en: 'Hi — yes, like the sailors',     ar: 'أهلاً — أيوه زي البحارة' },
      { g: 'first', native: 'Dobrý den',   how: 'DOB-ree den',      en: 'Good day — the polite one',      ar: 'نهارك سعيد — الرسمية' },
      { g: 'first', native: 'Děkuji',      how: 'DYEH-koo-yee',     en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'Promiňte',    how: 'PRO-min-teh',      en: 'Sorry / excuse me',              ar: 'آسف / لو سمحت' },
      { g: 'eat',   native: 'Kávu, prosím', how: 'KAH-voo PRO-seem', en: 'Coffee, please',                ar: 'قهوة، من فضلك' },
      { g: 'eat',   native: 'Vodu z kohoutku', how: 'VO-doo z KO-hoot-koo', en: 'Tap water',              ar: 'مياه الحنفية' },
      { g: 'eat',   native: 'Bez masa',    how: 'bez MA-sa',        en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Zaplatím, prosím', how: 'ZAP-la-teem PRO-seem', en: 'The bill, please',      ar: 'الحساب، من فضلك' },
      { g: 'go',    native: 'Kde je…?',    how: 'g-deh yeh',        en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Kolik to stojí?', how: 'KO-leek to STO-yee', en: 'How much is it?',          ar: 'بكام؟' },
      { g: 'help',  native: 'Mluvíte anglicky?', how: 'MLOO-vee-teh AN-glits-kee', en: 'Do you speak English?', ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'Pomoc!',      how: 'PO-mots',          en: 'Help!',                          ar: 'إلحقوني!' },
      { g: 'eat',   native: 'Jedno pivo, prosím', how: 'YED-no PEE-vo PRO-seem', en: 'One beer, please — and it will arrive before you finish asking', ar: 'بيرة واحدة من فضلك — وهتوصل قبل ما تخلص كلامك' },
      { g: 'eat',   native: 'Ještě jedno',  how: 'YESH-tyeh YED-no', en: 'One more — the two words that keep a Czech evening going', ar: 'كمان واحدة — الكلمتين اللي بيمشوا الليلة التشيكية' },
      { g: 'go',    native: 'Jízdenku, prosím', how: 'YEEZ-den-koo PRO-seem', en: 'A ticket, please — and validate it in the machine or it is not a ticket', ar: 'تذكرة من فضلك — واختمها في الماكينة وإلا مش تذكرة' },
      { g: 'go',    native: 'Kolik je hodin?', how: 'KO-leek yeh HO-deen', en: 'What time is it?',            ar: 'الساعة كام؟' },
      { g: 'help',  native: 'Nerozumím',   how: 'NEH-ro-zoo-meem',  en: 'I do not understand — more useful than any other sentence in week one', ar: 'مش فاهم — أنفع من أي جملة تانية في أول أسبوع' },
      { g: 'help',  native: 'Můžete to napsat?', how: 'MOO-zheh-teh to NAP-sat', en: 'Could you write it down? — Czech is easier to read than to hear', ar: 'ممكن تكتبها؟ — التشيكي أسهل في القراية من السمع' },
    ],
    eat: [
      { name: 'Svíčková', nameAr: 'سفيتشكوفا',
        what: 'Beef in a creamy root-vegetable sauce with bread dumplings, cranberry and a spoon of cream. The Sunday dish.',
        whatAr: 'لحمة بقري في صوص خضار جذرية بالكريمة مع كور عيش وتوت بري وملعقة قشدة. أكلة يوم الأحد.' },
      { name: 'Knedlíky', nameAr: 'كنِدليكي',
        what: 'Steamed bread dumplings, sliced. They are there to carry the sauce, and Czechs are serious about them.',
        whatAr: 'كور عيش متسوية على البخار ومقطعة شرايح. موجودة عشان تشيل الصوص، والتشيك جادين بخصوصها.' },
      { name: 'Smažený sýr', nameAr: 'جبنة مقلية',
        what: 'A slab of fried cheese in a bun with tartare sauce. What a Czech eats at two in the morning.',
        whatAr: 'قطعة جبنة مقلية في عيش بصوص تارتار. اللي التشيكي بياكله الساعة اتنين بالليل.' },
      { name: 'Trdelník', nameAr: 'ترْدِلنيك',
        what: 'The sugar chimney sold to tourists in Prague. Worth knowing it is not actually a Czech tradition.',
        whatAr: 'مدخنة السكر اللي بتتباع للسياح في براغ. تستاهل تعرف إنها مش تقليد تشيكي أصلاً.' },
      { name: 'Guláš', nameAr: 'جولاش',
        what: 'Thicker and darker than the Hungarian one, and served with dumplings rather than as a soup. The dish a Czech orders when they are not thinking.',
        whatAr: 'أتخن وأغمق من المجري، وبتتقدم مع الكنيدليكي مش كشوربة. الأكلة اللي التشيكي بيطلبها من غير ما يفكر.' },
      { name: 'Bramborák', nameAr: 'برامبوراك',
        what: 'A fried potato pancake with garlic and marjoram. Cheap, hot, and sold from a window at a Christmas market.',
        whatAr: 'فطيرة بطاطس مقلية بتوم وبردقوش. رخيصة وسخنة وبتتباع من شباك في سوق الكريسماس.' },
      { name: 'Utopenec', nameAr: 'أوتوبينيتس',
        what: 'A pickled sausage, and the name means "the drowned man". Czechs will hand you one to see what you do.',
        whatAr: 'سجق مخلل، والاسم معناه "الغريق". التشيك هيدولك واحدة عشان يشوفوا هتعمل إيه.' },
    ],
    know: [
      { title: 'Beer is cheaper than water and that is not a joke',
        titleAr: 'البيرة أرخص من المياه، ودي مش نكتة',
        body: 'Czechs drink more beer per person than anyone on earth. If you do not drink, order a kofola — nobody blinks.',
        bodyAr: 'التشيك بيشربوا بيرة للفرد أكتر من أي حد في العالم. لو انت ما بتشربش، اطلب kofola — محدش هيستغرب.' },
      { title: 'Someone will join your table',
        titleAr: 'حد ممكن يقعد على ترابيزتك',
        body: 'In a busy pub, sharing a table with strangers is normal. They will ask "je tu volno?" — is this free.',
        bodyAr: 'في بار مزحوم، مشاركة الترابيزة مع غرب حاجة عادية. هيسألوا "je tu volno؟" يعني ده فاضي؟' },
      { title: 'Prague is not Czechia',
        titleAr: 'براغ مش التشيك',
        body: 'Prices in the centre are three times the rest of the country. Go one tram stop out and everything changes.',
        bodyAr: 'الأسعار في وسط البلد بتلات أضعاف باقي البلد. اطلع محطة ترام واحدة برة وكل حاجة تتغير.' },
      { title: 'Look them in the eye when you toast',
        titleAr: 'بصله في عينه وانت بتقول نخب',
        body: 'Na zdraví, glass touched, eyes met, glass down on the table before you drink. Miss the eyes and somebody will make you do it again.',
        bodyAr: 'Na zdraví، والكباية تلمس، والعين في العين، وتنزّل الكباية على الترابيزة قبل ما تشرب. لو ما بصتش في عينه حد هيخليك تعيدها.' },
      { title: 'The beer mat is the bill',
        titleAr: 'الفوطة اللي تحت الكباية دي الحساب',
        body: 'Every round is a pencil mark on the paper mat under your glass. Do not throw it away, and do not add marks to it.',
        bodyAr: 'كل جولة بتتحط كشخطة بالقلم على الفوطة الورق اللي تحت كبايتك. ما ترميهاش، وما تزوّدش عليها خطوط.' },
      { title: 'A new beer arrives without being ordered',
        titleAr: 'البيرة الجديدة بتيجي من غير ما تطلبها',
        body: 'That is service, not a trick. Put the beer mat on top of the empty glass and it stops.',
        bodyAr: 'دي خدمة مش حيلة. حط الفوطة فوق الكباية الفاضية وهتقف.' },
    ],
    hear: [
      { title: 'Má vlast (Vltava)', artist: 'Bedřich Smetana', year: '1874',
        why: 'The river running through Prague, written as music. It opens the Prague Spring festival every year.',
        whyAr: 'النهر اللي بيعدي في براغ، متكتوب كموسيقى. بيفتح بيها مهرجان ربيع براغ كل سنة.' },
      { title: 'Anything of hers', artist: 'Marta Kubišová', year: '1960s',
        why: 'Her song became the anthem of 1968 and she was banned from singing for twenty years.',
        whyAr: 'أغنيتها بقت نشيد ١٩٦٨ واتمنعت من الغنا عشرين سنة.' },
      { title: 'Anything of theirs', artist: 'Čechomor', year: 'since 1988',
        why: 'Moravian folk songs played by a rock band. The bridge between the village and the city.',
        whyAr: 'أغاني شعبية مورافية بتعزفها فرقة روك. الجسر بين القرية والمدينة.' },
      { title: 'Symphony No. 9, From the New World', artist: 'Antonín Dvořák', year: '1893',
        why: 'Written in America and homesick for Bohemia the whole way through. It went to the moon with Apollo 11.',
        whyAr: 'اتكتبت في أمريكا وهو مشتاق لبوهيميا طول الوقت. وراحت القمر مع أبولو ١١.' },
      { title: 'Anything of theirs', artist: 'The Plastic People of the Universe', year: '1968–1988',
        why: 'The band whose arrest started Charter 77, and with it the movement that ended the regime.',
        whyAr: 'الفرقة اللي القبض عليها بدأ "ميثاق ٧٧"، ومعاه الحركة اللي أنهت النظام.' },
    ],
  },
  {
    code: 'TR', name: 'Türkiye', nameAr: 'تركيا',
    lang: 'Turkish', langAr: 'التركية', filmLang: 'tr',
    hello: {
      native: 'Merhaba', how: 'MER-ha-ba',
      means: 'Borrowed straight from the Arabic مرحبا — so an Arabic speaker already knows the Turkish hello, and Turks notice when you say it properly.',
      meansAr: 'مستعارة على طول من العربية "مرحبا" — يعني اللي بيتكلم عربي عارف السلام التركي أصلاً، والأتراك بيلاحظوا لما تقولها صح.',
      bye: { native: 'Güle güle', how: 'gyoo-LEH gyoo-LEH',
             means: 'Literally "smilingly, smilingly" — and it is only said by the person staying to the person leaving. The one leaving says hoşça kal, "stay well".',
             meansAr: 'حرفياً "وانت بتضحك، وانت بتضحك" — وبيقولها بس اللي فاضل للي ماشي. واللي ماشي بيقول hoşça kal يعني "ابقى بخير".' },
    },
    warm: [
      { native: 'Memnun oldum', how: 'mem-NOON ol-DOOM', en: 'Pleased to meet you — literally "I became pleased"', ar: 'تشرفنا — حرفياً "أنا اتبسطت"', when: 'A first meeting', whenAr: 'أول لقاء' },
      { native: 'Şerefe!', how: 'sheh-reh-FEH', en: 'Cheers — literally "to honour"', ar: 'في صحتك — حرفياً "للشرف"', when: 'Raising a glass', whenAr: 'وانت رافع الكباية' },
      { native: 'Afiyet olsun', how: 'ah-fee-YET ol-SOON', en: 'Good appetite — and also said after the meal, meaning "may it do you good"', ar: 'بالهنا والشفا — وبتتقال كمان بعد الأكل، بمعنى "يهنيك"', when: 'Before and after eating', whenAr: 'قبل الأكل وبعده' },
      { native: 'Eline sağlık', how: 'eh-lee-NEH sah-LUK', en: 'Health to your hands — said to whoever cooked, and it means a great deal', ar: 'تسلم إيديك — بتتقال للي طبخ، ومعناها كبير عندهم', when: 'To the cook, always', whenAr: 'للي طبخ، دايماً' },
    ],
    say: [
      { g: 'first', native: 'Merhaba',     how: 'MER-ha-ba',        en: 'Hello',                          ar: 'مرحبا' },
      { g: 'first', native: 'Günaydın',    how: 'gyoo-nigh-DUHN',   en: 'Good morning',                   ar: 'صباح الخير' },
      { g: 'first', native: 'Teşekkürler', how: 'teh-shek-kyoor-LER', en: 'Thank you',                    ar: 'شكراً' },
      { g: 'first', native: 'Pardon',      how: 'par-DON',          en: 'Excuse me',                      ar: 'لو سمحت' },
      { g: 'eat',   native: 'Bir çay, lütfen', how: 'beer CHAI LOOT-fen', en: 'One tea, please — you will be offered it constantly', ar: 'شاي واحد من فضلك — هيعرضوه عليك على طول' },
      { g: 'eat',   native: 'Su',          how: 'soo',              en: 'Water',                          ar: 'مياه' },
      { g: 'eat',   native: 'Etsiz',       how: 'ET-siz',           en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'Hesap, lütfen', how: 'heh-SAP LOOT-fen', en: 'The bill, please',             ar: 'الحساب، من فضلك' },
      { g: 'go',    native: '…nerede?',    how: 'NEH-reh-deh',      en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'Ne kadar?',   how: 'neh ka-DAR',       en: 'How much is it?',                ar: 'بكام؟' },
      { g: 'help',  native: 'İngilizce biliyor musunuz?', how: 'in-gi-LIZ-jeh bi-li-YOR moo-soo-nooz', en: 'Do you speak English?', ar: 'بتتكلم إنجليزي؟' },
      { g: 'help',  native: 'İmdat!',      how: 'im-DAT',           en: 'Help!',                          ar: 'إلحقوني!' },
    ],
    eat: [
      { name: 'Kahvaltı', nameAr: 'الفطار التركي',
        what: 'Not a dish, a table: cheeses, olives, tomato, cucumber, eggs, honey and cream, and tea that never stops. It takes two hours.',
        whatAr: 'مش أكلة، ده ترابيزة: أجبان وزيتون وطماطم وخيار وبيض وعسل وقشطة، وشاي ما بيقفش. بتاخد ساعتين.' },
      { name: 'Lahmacun', nameAr: 'لحم بعجين',
        what: 'A very thin base with spiced minced meat, rolled around parsley and lemon. Eaten with your hands.',
        whatAr: 'عجينة رفيعة جداً عليها لحمة مفرومة متبلة، بتتلف على بقدونس وليمون. بتتاكل بإيدك.' },
      { name: 'Menemen', nameAr: 'مِنِمِن',
        what: 'Eggs cooked into tomato, green pepper and onion. Breakfast, and the argument is whether onion belongs in it.',
        whatAr: 'بيض متطبخ في طماطم وفلفل أخضر وبصل. فطار، والخناقة على البصل هو ينفع فيها ولا لأ.' },
      { name: 'Künefe', nameAr: 'كنافة',
        what: 'Shredded pastry over stretchy cheese, soaked in syrup, served hot. Southern Turkey argues with Nablus over who owns it.',
        whatAr: 'عجينة مبرومة على جبنة مطاطة، مسقية شربات، بتتقدم سخنة. جنوب تركيا بتتخانق مع نابلس على مين صاحبها.' },
    ],
    know: [
      { title: 'Tea will be offered, and refusing is a whole negotiation',
        titleAr: 'الشاي هيتعرض عليك، ورفضه مفاوضات كاملة',
        body: 'In a shop, before any business. Accepting does not mean you have to buy anything, and both of you know that.',
        bodyAr: 'في المحل، قبل أي بيزنس. قبولك مش معناه إنك لازم تشتري، وانتوا الاتنين عارفين ده.' },
      { title: 'Fighting to pay is the norm',
        titleAr: 'الخناقة على الدفع حاجة عادية',
        body: 'Whoever invited pays, and the other person is expected to argue about it properly first.',
        bodyAr: 'اللي عزم هو اللي بيدفع، والتاني المفروض يتخانق على كده الأول بجد.' },
      { title: 'Take your shoes off, and expect to be fed',
        titleAr: 'اقلع جزمتك، واستعد إنك تتأكّل',
        body: 'Turning down food in a Turkish home is heard as turning down the host. Take a little of everything.',
        bodyAr: 'رفضك الأكل في بيت تركي بيتسمع كإنك رافض صاحب البيت. خد شوية من كل حاجة.' },
    ],
    hear: [
      { title: 'Anything of hers', artist: 'Sezen Aksu', year: 'since 1975',
        why: 'Called the Queen of Turkish pop; she wrote much of what everyone else sings.',
        whyAr: 'بيسموها ملكة البوب التركي؛ هي اللي كتبت أغلب اللي بيغنيه الباقيين.' },
      { title: 'Anything of his', artist: 'Barış Manço', year: '1970s–1990s',
        why: 'Anatolian rock — Turkish folk instruments with a rock band, and he is beloved.',
        whyAr: 'روك أناضولي — آلات شعبية تركية مع فرقة روك، والناس بتحبه جداً.' },
      { title: 'Anything of his', artist: 'Neşet Ertaş', year: '1960s–2012',
        why: 'The last great âşık — a wandering poet-singer with a saz. Folk in its purest form.',
        whyAr: 'آخر عاشق كبير — شاعر مغني رحّال بالساز. الفولكلور في أنقى صوره.' },
    ],
  },
  {
    code: 'MA', name: 'Morocco', nameAr: 'المغرب',
    lang: 'Darija & French', langAr: 'الدارجة والفرنسية', filmLang: 'ar',
    hello: {
      native: 'السلام عليكم', how: 'as-salaamu alaykum',
      means: 'Peace be upon you — and the reply gives it back with more: وعليكم السلام. It works in every Arabic-speaking country and it is never wrong.',
      meansAr: 'وبيرد عليك بأكتر: وعليكم السلام. بتنفع في كل بلد عربي وعمرها ما بتبقى غلط.',
      bye: { native: 'بسلامة', how: 'b-sla-MA',
             means: 'Literally "with safety" — go in safety. The same idea as the Egyptian مع السلامة.',
             meansAr: 'حرفياً "بأمان" — روح بالسلامة. نفس فكرة "مع السلامة" المصرية.' },
    },
    warm: [
      { native: 'متشرفين', how: 'mut-shar-ri-FEEN', en: 'Honoured to meet you', ar: 'تشرفنا', when: 'A first meeting', whenAr: 'أول لقاء' },
      { native: 'بصحتك', how: 'b-seh-HAK', en: 'To your health — said for a drink, a meal, a haircut, a new shirt', ar: 'بصحتك — بتتقال للمشروب والأكل والحلاقة والقميص الجديد', when: 'Almost anything good', whenAr: 'أي حاجة حلوة تقريباً' },
      { native: 'الله يعطيك الصحة', how: 'allah y-3a-TEEK s-seh-HA', en: 'May God give you health — the thank-you that means the most here', ar: 'الله يعطيك الصحة — الشكر اللي معناه أكبر حاجة هنا', when: 'To anyone who did work for you', whenAr: 'لأي حد عمل حاجة لك' },
      { native: 'بسّاحة', how: 'b-SSA-ha', en: 'Take your time / no rush — the opposite of what a tourist expects', ar: 'على مهلك — عكس اللي السايح متوقعه', when: 'When someone apologises for being slow', whenAr: 'لما حد يعتذر إنه بطيء' },
    ],
    say: [
      { g: 'first', native: 'السلام عليكم', how: 'as-salaamu alaykum', en: 'Peace be upon you — works everywhere', ar: 'بتنفع في كل مكان' },
      { g: 'first', native: 'لاباس؟',      how: 'la-BAAS',          en: 'How are you? — literally "no harm?"', ar: 'إزيك؟ — حرفياً "لا بأس؟"' },
      { g: 'first', native: 'شكرا / بارك الله فيك', how: 'shukran / baarak allaahu feek', en: 'Thank you — the second is warmer', ar: 'التانية أدفى' },
      { g: 'first', native: 'سمح ليا',     how: 'smeh LEE-ya',      en: 'Excuse me / sorry',              ar: 'اعذرني / آسف' },
      { g: 'eat',   native: 'أتاي',        how: 'a-TAY',            en: 'Mint tea — the centre of everything', ar: 'الشاي بالنعناع — مركز كل حاجة' },
      { g: 'eat',   native: 'الما',        how: 'l-MA',             en: 'Water',                          ar: 'المية' },
      { g: 'eat',   native: 'بلا لحم',     how: 'bla LHAM',         en: 'Without meat',                   ar: 'من غير لحمة' },
      { g: 'eat',   native: 'الحساب عافاك', how: 'l-hsaab 3a-FAAK', en: 'The bill, please',               ar: 'الحساب لو سمحت' },
      { g: 'go',    native: 'فين كاين…؟',  how: 'feen KAAYN',       en: 'Where is…?',                     ar: 'فين…؟' },
      { g: 'go',    native: 'بشحال؟',      how: 'b-sh-HAAL',        en: 'How much? — and then you bargain', ar: 'بكام؟ — وبعدين تفاصل' },
      { g: 'help',  native: 'كتهضر بالإنجليزية؟', how: 'kat-had-dar bl-in-gli-ZEE-ya', en: 'Do you speak English? — French often works better', ar: 'بتتكلم إنجليزي؟ — الفرنساوي غالباً بيمشي أحسن' },
      { g: 'help',  native: 'عاوني!',      how: '3aw-NEE',          en: 'Help me!',                       ar: 'ساعدني!' },
    ],
    eat: [
      { name: 'Tagine', nameAr: 'طاجين',
        what: 'Named after the clay pot, not the food. Lamb with prunes, chicken with preserved lemon and olives, or vegetables. Slow.',
        whatAr: 'اسمه على القدرة الفخار، مش على الأكل. ضاني بالبرقوق، أو فراخ بالليمون المخلل والزيتون، أو خضار. على نار هادية.' },
      { name: 'Couscous', nameAr: 'كسكس',
        what: 'Friday food, after prayer, in a family house. Steamed three times, and the broth goes on at the table.',
        whatAr: 'أكل الجمعة، بعد الصلاة، في بيت العيلة. بيتسوى على البخار تلات مرات، والمرق بيتحط على الترابيزة.' },
      { name: 'Harira', nameAr: 'حريرة',
        what: 'Tomato, lentil and chickpea soup with a squeeze of lemon. What Ramadan is broken with, and sold all year.',
        whatAr: 'شوربة طماطم وعدس وحمص بعصير ليمون. اللي بيتفطر عليه في رمضان، وبتتباع طول السنة.' },
      { name: 'Msemen', nameAr: 'مسمّن',
        what: 'A square folded flatbread, fried in layers, eaten with honey or cheese for breakfast.',
        whatAr: 'خبز مسطح مربع مطوي، بيتقلي طبقات، وبيتاكل بعسل أو جبنة على الفطار.' },
    ],
    know: [
      { title: 'The first price is not the price',
        titleAr: 'أول سعر مش هو السعر',
        body: 'In the souk, bargaining is expected and friendly. Walk away once; it is part of the conversation, not the end of it.',
        bodyAr: 'في السوق، الفصال متوقع وودّي. امشي مرة؛ دي جزء من الكلام مش نهايته.' },
      { title: 'Tea is poured from a height on purpose',
        titleAr: 'الشاي بيتصب من فوق عن قصد',
        body: 'It airs the tea and makes the foam. Three glasses is the tradition, and each one tastes different.',
        bodyAr: 'ده بيهوّي الشاي ويعمل الرغوة. تلات كاسات هو التقليد، وكل واحدة طعمها مختلف.' },
      { title: 'Ask before photographing a person',
        titleAr: 'استأذن قبل ما تصوّر حد',
        body: 'Especially in Jemaa el-Fnaa, where performers make their living from it and expect to be paid.',
        bodyAr: 'خصوصاً في جامع الفنا، حيث الفنانين بياكلوا عيش من ده وبيتوقعوا يتدفعلهم.' },
    ],
    hear: [
      { title: 'Gnawa', artist: 'Mahmoud Guinia', year: '1970s–2015',
        why: 'Trance music descended from West African slavery, played on a guembri all night.',
        whyAr: 'موسيقى وجْد جاية من العبودية في غرب أفريقيا، بتتعزف على الكمبري طول الليل.' },
      { title: 'Anything of theirs', artist: 'Nass El Ghiwane', year: 'since 1971',
        why: 'Scorsese called them the Rolling Stones of Africa. Poetry, protest and drums.',
        whyAr: 'سكورسيزي سماهم رولينج ستونز أفريقيا. شعر واحتجاج وطبول.' },
      { title: 'Chaabi', artist: 'Najat Aatabou', year: 'since 1983',
        why: 'She sang about women’s lives in Darija when that was not done, and filled stadiums doing it.',
        whyAr: 'غنت عن حياة الستات بالدارجة في وقت ماكانش ده بيتعمل، وملت استادات وهي بتعمل كده.' },
    ],
  },
  {
    code: 'EG', name: 'Egypt', nameAr: 'مصر',
    lang: 'Egyptian Arabic', langAr: 'المصري', filmLang: 'ar',
    hello: {
      native: 'السلام عليكم', how: 'as-salaamu alaykum',
      means: 'Peace be upon you. أهلاً is the lighter one and comes from أهل — family: "you are family here".',
      meansAr: 'و"أهلاً" هي الأخف وجاية من "أهل" — يعني "إنت من أهل البيت هنا".',
      bye: { native: 'مع السلامة', how: 'ma3a s-sa-LAA-ma',
             means: 'Literally "with safety" — go with safety. The one staying says it; the one leaving often says أستأذن, "I take my leave".',
             meansAr: 'حرفياً "روح بالأمان". اللي فاضل بيقولها؛ واللي ماشي غالباً بيقول "أستأذن".' },
    },
    warm: [
      { native: 'تشرفنا', how: 'ta-shar-RAF-na', en: 'Honoured to meet you — literally "we were honoured"', ar: 'حرفياً "اتشرفنا"', when: 'A first meeting', whenAr: 'أول لقاء' },
      { native: 'تسلم إيدك', how: 'tis-lam EE-dak', en: 'Bless your hands — to whoever cooked, built, fixed or carried something', ar: 'للي طبخ أو بنى أو صلّح أو شال حاجة', when: 'After anyone does anything for you', whenAr: 'بعد ما حد يعمل لك أي حاجة' },
      { native: 'ربنا يخليك', how: 'RAB-be-na yi-KHAL-leek', en: 'May God keep you — the warmest thank you there is', ar: 'أدفى شكر ممكن', when: 'When somebody has really helped', whenAr: 'لما حد يساعدك بجد' },
      { native: 'ولا يهمك', how: 'wa-la yi-hem-MAK', en: 'Don\u2019t worry about it — the everyday you-are-welcome', ar: 'العفو اليومية', when: 'After a thank you, or an apology', whenAr: 'بعد الشكر، أو بعد اعتذار' },
    ],
    say: [
      { g: 'first', native: 'إزيك',        how: 'iz-ZAY-yak',       en: 'How are you? — to a man; إزيك is izzayyik to a woman', ar: 'للراجل؛ وللست إزيّك' },
      { g: 'first', native: 'أهلاً',        how: 'AH-lan',           en: 'Welcome / hi',                   ar: 'ترحيب' },
      { g: 'first', native: 'شكراً',        how: 'SHOK-ran',         en: 'Thank you',                      ar: 'شكراً' },
      { g: 'first', native: 'لو سمحت',     how: 'law sa-MAHT',      en: 'Please / excuse me',             ar: 'من فضلك' },
      { g: 'eat',   native: 'قهوة سادة',   how: 'AH-wa SAA-da',     en: 'Coffee with no sugar — ask for مظبوط for medium', ar: 'من غير سكر — واطلب مظبوط للمتوسط' },
      { g: 'eat',   native: 'ميّة',        how: 'MAY-ya',           en: 'Water',                          ar: 'مياه' },
      { g: 'eat',   native: 'من غير لحمة', how: 'min gheer LAH-ma', en: 'Without meat',                   ar: 'بدون لحم' },
      { g: 'eat',   native: 'الحساب لو سمحت', how: 'il-hi-SAAB law sa-MAHT', en: 'The bill, please',      ar: 'الحساب من فضلك' },
      { g: 'go',    native: 'فين…؟',       how: 'feen',             en: 'Where is…?',                     ar: 'أين…؟' },
      { g: 'go',    native: 'بكام؟',       how: 'bi-KAAM',          en: 'How much is it?',                ar: 'بكم؟' },
      { g: 'help',  native: 'بتتكلم إنجليزي؟', how: 'bit-it-KAL-lim in-gi-LEE-zi', en: 'Do you speak English?', ar: 'هل تتحدث الإنجليزية؟' },
      { g: 'help',  native: 'الحقني!',     how: 'il-HAA-ni',        en: 'Help me!',                       ar: 'ساعدني!' },
    ],
    eat: [
      { name: 'Koshari', nameAr: 'كشري',
        what: 'Rice, lentils, macaroni, chickpeas, fried onion, tomato sauce and vinegar-garlic. Egypt’s national dish, and it is vegetarian.',
        whatAr: 'رز وعدس ومكرونة وحمص وبصل محمر وصلصة ودقة. الأكلة الوطنية المصرية، وهي نباتية.' },
      { name: 'Ful & taameya', nameAr: 'فول وطعمية',
        what: 'Slow-cooked fava beans and fava-bean falafel. Breakfast for most of the country, from a cart, before work.',
        whatAr: 'فول مدمّس وطعمية من الفول. فطار أغلب البلد، من عربية، قبل الشغل.' },
      { name: 'Molokhia', nameAr: 'ملوخية',
        what: 'Jute leaf cooked to a green soup with garlic and coriander. Loved with an intensity outsiders find funny.',
        whatAr: 'ورق الملوخية متطبخ لشوربة خضرا بتوم وكزبرة. محبوبة بشكل بيضحّك الأجانب.' },
      { name: 'Om Ali', nameAr: 'أم علي',
        what: 'Pastry baked in sweet milk with nuts and coconut. The dessert that ends a family dinner.',
        whatAr: 'عجين متخبز في لبن محلي بمكسرات وجوز هند. الحلو اللي بينهي عشا العيلة.' },
    ],
    know: [
      { title: 'Refusing food twice is polite, three times is real',
        titleAr: 'رفض الأكل مرتين ذوق، وتلاتة بجد',
        body: 'You will be pressed. That pressing is the hospitality; take a little the third time and everyone is happy.',
        bodyAr: 'هيلحّوا عليك. اللحّ ده هو الكرم؛ خد شوية في التالتة والكل هيبقى مبسوط.' },
      { title: 'Everything is negotiable except in a shop with prices',
        titleAr: 'كل حاجة قابلة للفصال إلا المحل اللي فيه أسعار مكتوبة',
        body: 'Taxis, markets, workshops — agree the number before it starts. In a supermarket the sticker is the sticker.',
        bodyAr: 'التاكسي والأسواق والورش — اتفق على الرقم قبل ما تبدأ. في السوبر ماركت السعر المكتوب هو السعر.' },
      { title: 'Bread is called aish — life',
        titleAr: 'العيش اسمه عيش — يعني حياة',
        body: 'Not khubz. Dropping it on the floor and leaving it there is genuinely shocking to people.',
        bodyAr: 'مش خبز. ولو وقع على الأرض وسبته، ده بيصدم الناس بجد.' },
    ],
    hear: [
      { title: 'Anything of hers', artist: 'Umm Kulthum', year: '1930s–1973',
        why: 'The first Thursday of the month, the Arab world stopped to listen. Songs run an hour and nobody minds.',
        whyAr: 'أول خميس في الشهر، العالم العربي كان بيقف عشان يسمع. الأغنية ساعة ومحدش بيزهق.' },
      { title: 'Anything of his', artist: 'Mohamed Abdel Wahab', year: '1920s–1980s',
        why: 'The composer who put the orchestra into Arabic music, and wrote the anthem.',
        whyAr: 'الملحّن اللي دخّل الأوركسترا في الموسيقى العربية، وكتب النشيد الوطني.' },
      { title: 'Mahraganat', artist: 'street sound of Cairo', year: 'since 2007',
        why: 'Autotuned electro-shaabi made on cheap laptops in Salam City. Banned, then everywhere.',
        whyAr: 'شعبي إلكتروني بالأوتوتيون متعمل على لابتوبات رخيصة في مدينة السلام. اتمنع، وبعدين بقى في كل مكان.' },
    ],
  },
];
