/* ── CURATED DESTINATIONS · real places, real coordinates ──────────
   Hand-picked adventure & culture spots across Egypt, Romania, Spain
   and France. Every pin sits at the place's true GPS position; tapping
   one opens the guide sheet (description, community reviews, Uber,
   directions). */

export const DESTINATIONS = [
  // ── 🇪🇬 EGYPT ──
  { id: 'eg_cave_church', country: 'Egypt', flag: '🇪🇬', emoji: '⛪', name: 'St. Simon Cave Church', area: 'Mokattam, Cairo',
    lat: 30.0329, lng: 31.2757, tags: ['Culture', 'Calm'],
    desc: 'A breathtaking monastery carved straight into Mokattam mountain. Vast rock-hewn halls, a deeply peaceful vibe, and one of Cairo\'s most surreal escapes from the noise.' },
  { id: 'eg_mario_ropes', country: 'Egypt', flag: '🇪🇬', emoji: '🧗', name: 'Mario High Ropes', area: 'Mokattam, Cairo',
    lat: 30.0341, lng: 31.2744, tags: ['Adrenaline', 'Groups'],
    desc: 'Ropes courses and ziplines strung between the rocky heights next to the Cave Church. Physical challenges for every fitness level — perfect for a crew day out.' },
  { id: 'eg_giza_complex', country: 'Egypt', flag: '🇪🇬', emoji: '🐫', name: 'Giza Pyramids Plateau', area: 'Giza',
    lat: 29.9773, lng: 31.1325, tags: ['Culture', 'Hiking'],
    desc: 'The legendary plateau — open desert paths for long walks between the monuments and panoramic views where ancient history meets the horizon.' },
  { id: 'eg_khufu', country: 'Egypt', flag: '🇪🇬', emoji: '🔺', name: 'Great Pyramid of Khufu', area: 'Giza',
    lat: 29.9792, lng: 31.1342, tags: ['Adventure', 'Culture'],
    desc: 'The last ancient wonder still standing. Descend through the narrow passages into its inner chambers — a real physical and mental mini-expedition.' },
  { id: 'eg_khafre', country: 'Egypt', flag: '🇪🇬', emoji: '⛰️', name: 'Pyramid of Khafre', area: 'Giza',
    lat: 29.9761, lng: 31.1308, tags: ['Culture', 'Photo'],
    desc: 'Second tallest, still crowned with its original casing stones. The most photogenic angle on the plateau and the visual anchor of the whole complex.' },
  { id: 'eg_queens', country: 'Egypt', flag: '🇪🇬', emoji: '👑', name: 'Queens\' Pyramids', area: 'Giza',
    lat: 29.9785, lng: 31.1365, tags: ['Calm', 'Culture'],
    desc: 'The smaller pyramids on the eastern side — quieter, less crowded, and perfect for slowly taking in the fine architectural details of the ancient necropolis.' },
  { id: 'eg_giza_pass', country: 'Egypt', flag: '🇪🇬', emoji: '🎫', name: 'Giza Pyramids Entrance', area: 'Giza',
    lat: 29.9814, lng: 31.1329, tags: ['Meet point'],
    desc: 'The official gate and ticket point — the natural meetup spot for your squad before heading into the plateau together.' },
  { id: 'eg_coloured_canyon', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Coloured Canyon', area: 'Nuweiba, Sinai',
    lat: 29.0400, lng: 34.5630, tags: ['Hiking', 'Wellbeing'],
    desc: 'Hike through winding rock corridors painted in unreal colours. Camping, silence, and the best kind of digital detox — Sinai at its most magical.' },

  // ── 🇷🇴 ROMANIA ──
  { id: 'ro_transfagarasan', country: 'Romania', flag: '🇷🇴', emoji: '🛣️', name: 'Transfăgărășan', area: 'Carpathians',
    lat: 45.6036, lng: 24.6173, tags: ['Adventure', 'Hiking'],
    desc: 'One of the most spectacular mountain roads on Earth, winding past glacial lakes and green cliffs. A paradise for camping and high-altitude trail days.' },
  { id: 'ro_cheile_turzii', country: 'Romania', flag: '🇷🇴', emoji: '🏞️', name: 'Cheile Turzii Gorge', area: 'Cluj',
    lat: 46.5628, lng: 23.6817, tags: ['Hiking', 'Adrenaline'],
    desc: 'A deep natural gorge with stream crossings, hanging bridges and cave detours. Intense, beautiful, and pure wild nature from start to finish.' },
  { id: 'ro_bran', country: 'Romania', flag: '🇷🇴', emoji: '🏰', name: 'Bran Castle', area: 'Transylvania',
    lat: 45.5152, lng: 25.3672, tags: ['Culture', 'Mystery'],
    desc: 'The cliff-edge castle behind the Dracula legend. Secret passages, narrow stairways, and a panoramic view over Transylvania\'s dense forests.' },

  // ── 🇪🇸 SPAIN ──
  { id: 'es_caminito_north', country: 'Spain', flag: '🇪🇸', emoji: '🥾', name: 'Caminito del Rey · North', area: 'Málaga',
    lat: 36.9370, lng: -4.8040, tags: ['Adrenaline', 'Hiking'],
    desc: 'The northern gateway to the world\'s most famous cliff-side walkway — boardwalks pinned to a sheer canyon wall. A serious adrenaline dose with jaw-dropping views.' },
  { id: 'es_caminito_tickets', country: 'Spain', flag: '🇪🇸', emoji: '🎟️', name: 'Caminito del Rey · Tickets', area: 'El Chorro',
    lat: 36.9155, lng: -4.7616, tags: ['Meet point'],
    desc: 'The visitor reception — tickets, safety briefing and gear. The meetup point for groups before the walkway adventure begins.' },
  { id: 'es_caminito_playa', country: 'Spain', flag: '🇪🇸', emoji: '🏖️', name: 'Caminito del Rey · Playa', area: 'Ardales',
    lat: 36.9430, lng: -4.8010, tags: ['Calm', 'Swim'],
    desc: 'A turquoise lake beach right by the trailheads — the perfect wind-down after the cliff walk. Balance the adrenaline with pure calm.' },
  { id: 'es_portaventura', country: 'Spain', flag: '🇪🇸', emoji: '🎢', name: 'PortAventura World', area: 'Tarragona',
    lat: 41.0870, lng: 1.1560, tags: ['Adrenaline', 'Fun'],
    desc: 'A massive theme park with some of Europe\'s fastest coasters, live shows and full-day energy. Maximum adrenaline, zero hiking boots required.' },

  // ── 🇫🇷 FRANCE ──
  { id: 'fr_verdon', country: 'France', flag: '🇫🇷', emoji: '🛶', name: 'Verdon Gorge', area: 'Provence',
    lat: 43.7496, lng: 6.3285, tags: ['Rafting', 'Hiking'],
    desc: '"Europe\'s Grand Canyon" — turquoise rapids between towering cliffs. Rafting, advanced trails and climbing routes for the truly brave.' },
  { id: 'fr_chamonix', country: 'France', flag: '🇫🇷', emoji: '🏔️', name: 'Chamonix', area: 'French Alps',
    lat: 45.9237, lng: 6.8694, tags: ['Climbing', 'Adventure'],
    desc: 'The iconic Alpine town at the foot of Mont Blanc. Cable cars, climbing routes and long-distance trails — the absolute dream base for mountain people.' },
  { id: 'fr_eiffel', country: 'France', flag: '🇫🇷', emoji: '🗼', name: 'Eiffel Tower', area: 'Paris',
    lat: 48.8584, lng: 2.2945, tags: ['Culture', 'Photo'],
    desc: 'The classic — but take the stairs and it becomes a workout with the best panoramic reward in Paris. Iron-lattice engineering meets serious altitude.' },
  { id: 'fr_calanques', country: 'France', flag: '🇫🇷', emoji: '⛰️', name: 'Calanques National Park', area: 'Marseille',
    lat: 43.2100, lng: 5.4450, tags: ['Hiking', 'Swim'],
    desc: 'White limestone cliffs plunging into turquoise coves. Tough coastal hikes down to hidden bays — raw effort rewarded with the Mediterranean\'s best swim.' },
  { id: 'fr_gavarnie', country: 'France', flag: '🇫🇷', emoji: '🏞️', name: 'Cirque de Gavarnie', area: 'Pyrénées',
    lat: 42.6953, lng: -0.0113, tags: ['Hiking', 'Wellbeing'],
    desc: 'A colossal natural amphitheatre with towering waterfalls. The walk in puts you face-to-face with the mountains\' full scale — deep-recharge territory.' },

  // ── 🇪🇬 EGYPT · Sinai, Fayoum & Siwa (camping + culture) ──
  { id: 'eg_mount_sinai', country: 'Egypt', flag: '🇪🇬', emoji: '🌄', name: 'Mount Sinai (Jabal Musa)', area: 'Saint Catherine',
    lat: 28.5394, lng: 33.9750, tags: ['Hiking', 'Camping', 'Culture'],
    desc: 'The legendary night hike that ends with sunrise from the summit. Bedouin guides, campfire circles, and one of the most soul-resetting experiences in Egypt.' },
  { id: 'eg_wadi_hitan', country: 'Egypt', flag: '🇪🇬', emoji: '🐋', name: 'Wadi El-Hitan (Whale Valley)', area: 'Fayoum',
    lat: 29.2703, lng: 30.0410, tags: ['Camping', 'Calm'],
    desc: 'A UNESCO desert valley scattered with 40-million-year-old whale fossils. Walking trails between the rock formations and star-drenched camping silence.' },
  { id: 'eg_cleopatra_spring', country: 'Egypt', flag: '🇪🇬', emoji: '♨️', name: 'Cleopatra Spring', area: 'Siwa Oasis',
    lat: 29.2077, lng: 25.5528, tags: ['Swim', 'Culture'],
    desc: 'A natural stone spring in the heart of Siwa — warm water, palm groves, and eco-cafés where you actually talk with the locals. Healing in every sense.' },
  { id: 'eg_siwa_salt', country: 'Egypt', flag: '🇪🇬', emoji: '🧂', name: 'Siwa Salt Lakes', area: 'Siwa Oasis',
    lat: 29.2211, lng: 25.6390, tags: ['Wellbeing', 'Photo'],
    desc: 'Impossibly turquoise pools ringed by white salt crystals — so salty you float without trying. Otherworldly to see, genuinely therapeutic to swim.' },
  { id: 'eg_shali', country: 'Egypt', flag: '🇪🇬', emoji: '🏯', name: 'Shali Fortress', area: 'Siwa Oasis',
    lat: 29.2032, lng: 25.5196, tags: ['Culture', 'Sunset'],
    desc: 'A melting salt-and-mud citadel rising from the oasis. Climb its winding paths at sunset for the full palm-grove panorama and real Siwan heritage.' },
  { id: 'eg_wadi_rayan', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Wadi El Rayan', area: 'Fayoum',
    lat: 29.2036, lng: 30.4106, tags: ['Camping', 'Hiking'],
    desc: 'Twin desert lakes wrapped in golden dunes. Vast open freedom — long walks, dune lines to the horizon, and pure escape from the city.' },
  { id: 'eg_rayan_falls', country: 'Egypt', flag: '🇪🇬', emoji: '💦', name: 'Wadi El Rayan Waterfalls', area: 'Fayoum',
    lat: 29.2069, lng: 30.4084, tags: ['Photo', 'Fun'],
    desc: 'Waterfalls in the middle of the desert — the water-on-sand contrast is unreal. Wooden boat rides between the lakes seal the day.' },
  { id: 'eg_magic_lake', country: 'Egypt', flag: '🇪🇬', emoji: '✨', name: 'Magic Lake Camp', area: 'Fayoum',
    lat: 29.2278, lng: 30.4438, tags: ['Camping', 'Adrenaline'],
    desc: 'The lake that changes colour with the sun. Sandboarding down the surrounding dunes by day, campfires under the stars by night.' },
  { id: 'eg_blue_hole', country: 'Egypt', flag: '🇪🇬', emoji: '🤿', name: 'The Blue Hole', area: 'Dahab',
    lat: 28.5720, lng: 34.5370, tags: ['Diving', 'Adrenaline'],
    desc: 'One of the most famous dive sites on Earth. Deep-blue abyss, world-class reef, and laid-back cliffside cafés full of divers swapping stories.' },
  { id: 'eg_nayzak', country: 'Egypt', flag: '🇪🇬', emoji: '💠', name: 'Al-Nayzak Pool', area: 'Marsa Alam',
    lat: 25.2494, lng: 34.7996, tags: ['Swim', 'Calm'],
    desc: 'A meteor-shaped natural rock pool open to the Red Sea — glass-clear turquoise water in untouched surroundings. Swim, float, reset.' },
  { id: 'eg_wadi_gemal', country: 'Egypt', flag: '🇪🇬', emoji: '🐪', name: 'Wadi el Gemal Reserve', area: 'Marsa Alam',
    lat: 24.6833, lng: 35.0833, tags: ['Safari', 'Culture'],
    desc: 'Mountains meeting mangrove beaches. Deep safari trails, migrating birds, hidden bays — and the living culture of the Ababda tribes.' },
  { id: 'eg_ras_mohamed', country: 'Egypt', flag: '🇪🇬', emoji: '🪸', name: 'Ras Mohamed', area: 'Sharm El-Sheikh',
    lat: 27.7373, lng: 34.2455, tags: ['Hiking', 'Diving'],
    desc: 'Where the two gulfs meet: cliff walks to hidden beaches, a mysterious salt lake, and reef walls with colours you won\'t believe from above.' },

  // ── 🇪🇬 CAIRO · historic streets (El-Moez energy) ──
  { id: 'eg_khan_khalili', country: 'Egypt', flag: '🇪🇬', emoji: '🏮', name: 'Khan el-Khalili', area: 'Historic Cairo',
    lat: 30.0477, lng: 31.2622, tags: ['Culture', 'Photo'],
    desc: 'One of the oldest bazaars on Earth — alleys of light, colour and craft. Cinematic at every corner, and every shopkeeper has a story.' },
  { id: 'eg_wekalet_ghouri', country: 'Egypt', flag: '🇪🇬', emoji: '🎭', name: 'Wekalet El-Ghouri', area: 'Al-Azhar, Cairo',
    lat: 30.0455, lng: 31.2610, tags: ['Culture', 'Shows'],
    desc: 'A jewel of Mamluk architecture steps from Al-Azhar — dramatic light and symmetry, home of the whirling Tanoura shows.' },
  { id: 'eg_azhar_park', country: 'Egypt', flag: '🇪🇬', emoji: '🌳', name: 'Al-Azhar Park', area: 'Cairo',
    lat: 30.0409, lng: 31.2657, tags: ['Calm', 'Sunset'],
    desc: 'A green hill above Historic Cairo\'s minarets. Wide lawns for unwinding, playing music, and the city\'s best sunset panorama.' },
  { id: 'eg_religions', country: 'Egypt', flag: '🇪🇬', emoji: '🕌', name: 'Religious Complex', area: 'Old Cairo',
    lat: 30.0059, lng: 31.2300, tags: ['Culture', 'Calm'],
    desc: 'Churches, mosques and a synagogue woven into narrow ancient stone lanes. Deeply spiritual, quiet, and made for slow exploration.' },
  { id: 'eg_pottery', country: 'Egypt', flag: '🇪🇬', emoji: '🏺', name: 'Fustat Pottery Village', area: 'Old Cairo',
    lat: 30.0089, lng: 31.2379, tags: ['Culture', 'Craft'],
    desc: 'Watch master potters shape clay with their hands. Warm earthy colours, real interaction with the makers — a content-creation goldmine.' },

  // ── 🇷🇴 ROMANIA · deep-nature hikes ──
  { id: 'ro_bucegi', country: 'Romania', flag: '🇷🇴', emoji: '🗻', name: 'Bucegi Mountains', area: 'Carpathians',
    lat: 45.4453, lng: 25.4567, tags: ['Hiking', 'Camping'],
    desc: 'A massive range with endless trails and wild camping in cool mountain air. Sweeping views at every ridge — made for crews who live outdoors.' },
  { id: 'ro_piatra', country: 'Romania', flag: '🇷🇴', emoji: '🌲', name: 'Piatra Craiului', area: 'National Park',
    lat: 45.5297, lng: 25.2320, tags: ['Climbing', 'Hiking'],
    desc: 'Romania\'s knife-edge ridge — rock climbing, narrow crest walks and dense forests full of wildlife. Teamwork territory, physically and mentally.' },
  { id: 'ro_piatra_visitor', country: 'Romania', flag: '🇷🇴', emoji: '🛖', name: 'Piatra Craiului Visitor Center', area: 'Zărnești',
    lat: 45.5665, lng: 25.3167, tags: ['Meet point'],
    desc: 'The first stop before the park — maps, wildlife info, safe camping zones, and the natural meetup spot before the group heads in.' },

  // ── 🇪🇸 SPAIN · mountain + spirit ──
  { id: 'es_picos', country: 'Spain', flag: '🇪🇸', emoji: '🏔️', name: 'Picos de Europa', area: 'Northern Spain',
    lat: 43.1938, lng: -4.8514, tags: ['Hiking', 'Culture'],
    desc: 'Deep gorges, dense forests and tiny mountain villages. Long trail days that end in rural Spanish culture — adventure with a soul.' },
  { id: 'es_montserrat', country: 'Spain', flag: '🇪🇸', emoji: '⛰️', name: 'Montserrat', area: 'near Barcelona',
    lat: 41.5955, lng: 1.8382, tags: ['Hiking', 'Wellbeing'],
    desc: 'Surreal sculpted rock spires an hour from Barcelona. Winding ascents, breath-stealing horizons, and a stillness that clears the head.' },
];
