/* ── CURATED DESTINATIONS · real places, real coordinates ──────────
   Hand-picked adventure & culture spots across Egypt, Romania, Spain
   and France. Every pin sits at the place's true GPS position; tapping
   one opens the guide sheet (description, community reviews, Uber,
   directions). */

export const DESTINATIONS = [
  // ── 🇪🇬 EGYPT ──
  { id: 'eg_cave_church', country: 'Egypt', flag: '🇪🇬', emoji: '⛪', name: 'St. Simon Cave Church', area: 'Mokattam, Cairo',
    lat: 30.0329, lng: 31.2757, tags: ['Culture', 'Calm'],
    desc: 'A breathtaking monastery carved straight into Mokattam mountain. Vast rock-hewn halls, a deeply peaceful vibe, and one of Cairo\'s most surreal escapes from the noise.' },
  { id: 'eg_mario_ropes', country: 'Egypt', flag: '🇪🇬', emoji: '🧗', name: 'Mario High Ropes', area: 'Mokattam, Cairo',
    lat: 30.0341, lng: 31.2744, tags: ['Adrenaline', 'Groups'],
    desc: 'Ropes courses and ziplines strung between the rocky heights next to the Cave Church. Physical challenges for every fitness level — perfect for a crew day out.' },
  { id: 'eg_giza_complex', country: 'Egypt', flag: '🇪🇬', emoji: '🐫', name: 'Giza Pyramids Plateau', area: 'Giza',
    lat: 29.9773, lng: 31.1325, tags: ['Culture', 'Hiking'],
    desc: 'The legendary plateau — open desert paths for long walks between the monuments and panoramic views where ancient history meets the horizon.' },
  { id: 'eg_khufu', country: 'Egypt', flag: '🇪🇬', emoji: '🔺', name: 'Great Pyramid of Khufu', area: 'Giza',
    lat: 29.9792, lng: 31.1342, tags: ['Adventure', 'Culture'],
    desc: 'The last ancient wonder still standing. Descend through the narrow passages into its inner chambers — a real physical and mental mini-expedition.' },
  { id: 'eg_khafre', country: 'Egypt', flag: '🇪🇬', emoji: '⛰️', name: 'Pyramid of Khafre', area: 'Giza',
    lat: 29.9761, lng: 31.1308, tags: ['Culture', 'Photo'],
    desc: 'Second tallest, still crowned with its original casing stones. The most photogenic angle on the plateau and the visual anchor of the whole complex.' },
  { id: 'eg_queens', country: 'Egypt', flag: '🇪🇬', emoji: '👑', name: 'Queens\' Pyramids', area: 'Giza',
    lat: 29.9785, lng: 31.1365, tags: ['Calm', 'Culture'],
    desc: 'The smaller pyramids on the eastern side — quieter, less crowded, and perfect for slowly taking in the fine architectural details of the ancient necropolis.' },
  { id: 'eg_giza_pass', country: 'Egypt', flag: '🇪🇬', emoji: '🎫', name: 'Giza Pyramids Entrance', area: 'Giza',
    lat: 29.9814, lng: 31.1329, tags: ['Meet point'],
    desc: 'The official gate and ticket point — the natural meetup spot for your squad before heading into the plateau together.' },
  { id: 'eg_coloured_canyon', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Coloured Canyon', area: 'Nuweiba, Sinai',
    lat: 29.0400, lng: 34.5630, tags: ['Hiking', 'Wellbeing'],
    desc: 'Hike through winding rock corridors painted in unreal colours. Camping, silence, and the best kind of digital detox — Sinai at its most magical.' },

  // ── 🇷🇴 ROMANIA ──
  { id: 'ro_transfagarasan', country: 'Romania', flag: '🇷🇴', emoji: '🛣️', name: 'Transfăgărășan', area: 'Carpathians',
    lat: 45.6036, lng: 24.6173, tags: ['Adventure', 'Hiking'],
    desc: 'One of the most spectacular mountain roads on Earth, winding past glacial lakes and green cliffs. A paradise for camping and high-altitude trail days.' },
  { id: 'ro_cheile_turzii', country: 'Romania', flag: '🇷🇴', emoji: '🏞️', name: 'Cheile Turzii Gorge', area: 'Cluj',
    lat: 46.5628, lng: 23.6817, tags: ['Hiking', 'Adrenaline'],
    desc: 'A deep natural gorge with stream crossings, hanging bridges and cave detours. Intense, beautiful, and pure wild nature from start to finish.' },
  { id: 'ro_bran', country: 'Romania', flag: '🇷🇴', emoji: '🏰', name: 'Bran Castle', area: 'Transylvania',
    lat: 45.5152, lng: 25.3672, tags: ['Culture', 'Mystery'],
    desc: 'The cliff-edge castle behind the Dracula legend. Secret passages, narrow stairways, and a panoramic view over Transylvania\'s dense forests.' },

  // ── 🇪🇸 SPAIN ──
  { id: 'es_caminito_north', country: 'Spain', flag: '🇪🇸', emoji: '🥾', name: 'Caminito del Rey · North', area: 'Málaga',
    lat: 36.9370, lng: -4.8040, tags: ['Adrenaline', 'Hiking'],
    desc: 'The northern gateway to the world\'s most famous cliff-side walkway — boardwalks pinned to a sheer canyon wall. A serious adrenaline dose with jaw-dropping views.' },
  { id: 'es_caminito_tickets', country: 'Spain', flag: '🇪🇸', emoji: '🎟️', name: 'Caminito del Rey · Tickets', area: 'El Chorro',
    lat: 36.9155, lng: -4.7616, tags: ['Meet point'],
    desc: 'The visitor reception — tickets, safety briefing and gear. The meetup point for groups before the walkway adventure begins.' },
  { id: 'es_caminito_playa', country: 'Spain', flag: '🇪🇸', emoji: '🏖️', name: 'Caminito del Rey · Playa', area: 'Ardales',
    lat: 36.9430, lng: -4.8010, tags: ['Calm', 'Swim'],
    desc: 'A turquoise lake beach right by the trailheads — the perfect wind-down after the cliff walk. Balance the adrenaline with pure calm.' },
  { id: 'es_portaventura', country: 'Spain', flag: '🇪🇸', emoji: '🎢', name: 'PortAventura World', area: 'Tarragona',
    lat: 41.0870, lng: 1.1560, tags: ['Adrenaline', 'Fun'],
    desc: 'A massive theme park with some of Europe\'s fastest coasters, live shows and full-day energy. Maximum adrenaline, zero hiking boots required.' },

  // ── 🇫🇷 FRANCE ──
  { id: 'fr_verdon', country: 'France', flag: '🇫🇷', emoji: '🛶', name: 'Verdon Gorge', area: 'Provence',
    lat: 43.7496, lng: 6.3285, tags: ['Rafting', 'Hiking'],
    desc: '"Europe\'s Grand Canyon" — turquoise rapids between towering cliffs. Rafting, advanced trails and climbing routes for the truly brave.' },
  { id: 'fr_chamonix', country: 'France', flag: '🇫🇷', emoji: '🏔️', name: 'Chamonix', area: 'French Alps',
    lat: 45.9237, lng: 6.8694, tags: ['Climbing', 'Adventure'],
    desc: 'The iconic Alpine town at the foot of Mont Blanc. Cable cars, climbing routes and long-distance trails — the absolute dream base for mountain people.' },
  { id: 'fr_eiffel', country: 'France', flag: '🇫🇷', emoji: '🗼', name: 'Eiffel Tower', area: 'Paris',
    lat: 48.8584, lng: 2.2945, tags: ['Culture', 'Photo'],
    desc: 'The classic — but take the stairs and it becomes a workout with the best panoramic reward in Paris. Iron-lattice engineering meets serious altitude.' },
  { id: 'fr_calanques', country: 'France', flag: '🇫🇷', emoji: '⛰️', name: 'Calanques National Park', area: 'Marseille',
    lat: 43.2100, lng: 5.4450, tags: ['Hiking', 'Swim'],
    desc: 'White limestone cliffs plunging into turquoise coves. Tough coastal hikes down to hidden bays — raw effort rewarded with the Mediterranean\'s best swim.' },
  { id: 'fr_gavarnie', country: 'France', flag: '🇫🇷', emoji: '🏞️', name: 'Cirque de Gavarnie', area: 'Pyrénées',
    lat: 42.6953, lng: -0.0113, tags: ['Hiking', 'Wellbeing'],
    desc: 'A colossal natural amphitheatre with towering waterfalls. The walk in puts you face-to-face with the mountains\' full scale — deep-recharge territory.' },

  // ── 🇪🇬 EGYPT · Sinai, Fayoum & Siwa (camping + culture) ──
  { id: 'eg_mount_sinai', country: 'Egypt', flag: '🇪🇬', emoji: '🌄', name: 'Mount Sinai (Jabal Musa)', area: 'Saint Catherine',
    lat: 28.5394, lng: 33.9750, tags: ['Hiking', 'Camping', 'Culture'],
    desc: 'The legendary night hike that ends with sunrise from the summit. Bedouin guides, campfire circles, and one of the most soul-resetting experiences in Egypt.' },
  { id: 'eg_wadi_hitan', country: 'Egypt', flag: '🇪🇬', emoji: '🐋', name: 'Wadi El-Hitan (Whale Valley)', area: 'Fayoum',
    lat: 29.2703, lng: 30.0410, tags: ['Camping', 'Calm'],
    desc: 'A UNESCO desert valley scattered with 40-million-year-old whale fossils. Walking trails between the rock formations and star-drenched camping silence.' },
  { id: 'eg_cleopatra_spring', country: 'Egypt', flag: '🇪🇬', emoji: '♨️', name: 'Cleopatra Spring', area: 'Siwa Oasis',
    lat: 29.2077, lng: 25.5528, tags: ['Swim', 'Culture'],
    desc: 'A natural stone spring in the heart of Siwa — warm water, palm groves, and eco-cafés where you actually talk with the locals. Healing in every sense.' },
  { id: 'eg_siwa_salt', country: 'Egypt', flag: '🇪🇬', emoji: '🧂', name: 'Siwa Salt Lakes', area: 'Siwa Oasis',
    lat: 29.2211, lng: 25.6390, tags: ['Wellbeing', 'Photo'],
    desc: 'Impossibly turquoise pools ringed by white salt crystals — so salty you float without trying. Otherworldly to see, genuinely therapeutic to swim.' },
  { id: 'eg_shali', country: 'Egypt', flag: '🇪🇬', emoji: '🏯', name: 'Shali Fortress', area: 'Siwa Oasis',
    lat: 29.2032, lng: 25.5196, tags: ['Culture', 'Sunset'],
    desc: 'A melting salt-and-mud citadel rising from the oasis. Climb its winding paths at sunset for the full palm-grove panorama and real Siwan heritage.' },
  { id: 'eg_wadi_rayan', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Wadi El Rayan', area: 'Fayoum',
    lat: 29.2036, lng: 30.4106, tags: ['Camping', 'Hiking'],
    desc: 'Twin desert lakes wrapped in golden dunes. Vast open freedom — long walks, dune lines to the horizon, and pure escape from the city.' },
  { id: 'eg_rayan_falls', country: 'Egypt', flag: '🇪🇬', emoji: '💦', name: 'Wadi El Rayan Waterfalls', area: 'Fayoum',
    lat: 29.2069, lng: 30.4084, tags: ['Photo', 'Fun'],
    desc: 'Waterfalls in the middle of the desert — the water-on-sand contrast is unreal. Wooden boat rides between the lakes seal the day.' },
  { id: 'eg_magic_lake', country: 'Egypt', flag: '🇪🇬', emoji: '✨', name: 'Magic Lake Camp', area: 'Fayoum',
    lat: 29.2278, lng: 30.4438, tags: ['Camping', 'Adrenaline'],
    desc: 'The lake that changes colour with the sun. Sandboarding down the surrounding dunes by day, campfires under the stars by night.' },
  { id: 'eg_blue_hole', country: 'Egypt', flag: '🇪🇬', emoji: '🤿', name: 'The Blue Hole', area: 'Dahab',
    lat: 28.5720, lng: 34.5370, tags: ['Diving', 'Adrenaline'],
    desc: 'One of the most famous dive sites on Earth. Deep-blue abyss, world-class reef, and laid-back cliffside cafés full of divers swapping stories.' },
  { id: 'eg_nayzak', country: 'Egypt', flag: '🇪🇬', emoji: '💠', name: 'Al-Nayzak Pool', area: 'Marsa Alam',
    lat: 25.2494, lng: 34.7996, tags: ['Swim', 'Calm'],
    desc: 'A meteor-shaped natural rock pool open to the Red Sea — glass-clear turquoise water in untouched surroundings. Swim, float, reset.' },
  { id: 'eg_wadi_gemal', country: 'Egypt', flag: '🇪🇬', emoji: '🐪', name: 'Wadi el Gemal Reserve', area: 'Marsa Alam',
    lat: 24.6833, lng: 35.0833, tags: ['Safari', 'Culture'],
    desc: 'Mountains meeting mangrove beaches. Deep safari trails, migrating birds, hidden bays — and the living culture of the Ababda tribes.' },
  { id: 'eg_ras_mohamed', country: 'Egypt', flag: '🇪🇬', emoji: '🪸', name: 'Ras Mohamed', area: 'Sharm El-Sheikh',
    lat: 27.7373, lng: 34.2455, tags: ['Hiking', 'Diving'],
    desc: 'Where the two gulfs meet: cliff walks to hidden beaches, a mysterious salt lake, and reef walls with colours you won\'t believe from above.' },

  // ── 🇪🇬 CAIRO · historic streets (El-Moez energy) ──
  { id: 'eg_khan_khalili', country: 'Egypt', flag: '🇪🇬', emoji: '🏮', name: 'Khan el-Khalili', area: 'Historic Cairo',
    lat: 30.0477, lng: 31.2622, tags: ['Culture', 'Photo'],
    desc: 'One of the oldest bazaars on Earth — alleys of light, colour and craft. Cinematic at every corner, and every shopkeeper has a story.' },
  { id: 'eg_wekalet_ghouri', country: 'Egypt', flag: '🇪🇬', emoji: '🎭', name: 'Wekalet El-Ghouri', area: 'Al-Azhar, Cairo',
    lat: 30.0455, lng: 31.2610, tags: ['Culture', 'Shows'],
    desc: 'A jewel of Mamluk architecture steps from Al-Azhar — dramatic light and symmetry, home of the whirling Tanoura shows.' },
  { id: 'eg_azhar_park', country: 'Egypt', flag: '🇪🇬', emoji: '🌳', name: 'Al-Azhar Park', area: 'Cairo',
    lat: 30.0409, lng: 31.2657, tags: ['Calm', 'Sunset'],
    desc: 'A green hill above Historic Cairo\'s minarets. Wide lawns for unwinding, playing music, and the city\'s best sunset panorama.' },
  { id: 'eg_religions', country: 'Egypt', flag: '🇪🇬', emoji: '🕌', name: 'Religious Complex', area: 'Old Cairo',
    lat: 30.0059, lng: 31.2300, tags: ['Culture', 'Calm'],
    desc: 'Churches, mosques and a synagogue woven into narrow ancient stone lanes. Deeply spiritual, quiet, and made for slow exploration.' },
  { id: 'eg_pottery', country: 'Egypt', flag: '🇪🇬', emoji: '🏺', name: 'Fustat Pottery Village', area: 'Old Cairo',
    lat: 30.0089, lng: 31.2379, tags: ['Culture', 'Craft'],
    desc: 'Watch master potters shape clay with their hands. Warm earthy colours, real interaction with the makers — a content-creation goldmine.' },

  // ── 🇷🇴 ROMANIA · deep-nature hikes ──
  { id: 'ro_bucegi', country: 'Romania', flag: '🇷🇴', emoji: '🗻', name: 'Bucegi Mountains', area: 'Carpathians',
    lat: 45.4453, lng: 25.4567, tags: ['Hiking', 'Camping'],
    desc: 'A massive range with endless trails and wild camping in cool mountain air. Sweeping views at every ridge — made for crews who live outdoors.' },
  { id: 'ro_piatra', country: 'Romania', flag: '🇷🇴', emoji: '🌲', name: 'Piatra Craiului', area: 'National Park',
    lat: 45.5297, lng: 25.2320, tags: ['Climbing', 'Hiking'],
    desc: 'Romania\'s knife-edge ridge — rock climbing, narrow crest walks and dense forests full of wildlife. Teamwork territory, physically and mentally.' },
  { id: 'ro_piatra_visitor', country: 'Romania', flag: '🇷🇴', emoji: '🛖', name: 'Piatra Craiului Visitor Center', area: 'Zărnești',
    lat: 45.5665, lng: 25.3167, tags: ['Meet point'],
    desc: 'The first stop before the park — maps, wildlife info, safe camping zones, and the natural meetup spot before the group heads in.' },

  // ── 🇪🇸 SPAIN · mountain + spirit ──
  { id: 'es_picos', country: 'Spain', flag: '🇪🇸', emoji: '🏔️', name: 'Picos de Europa', area: 'Northern Spain',
    lat: 43.1938, lng: -4.8514, tags: ['Hiking', 'Culture'],
    desc: 'Deep gorges, dense forests and tiny mountain villages. Long trail days that end in rural Spanish culture — adventure with a soul.' },
  { id: 'es_montserrat', country: 'Spain', flag: '🇪🇸', emoji: '⛰️', name: 'Montserrat', area: 'near Barcelona',
    lat: 41.5955, lng: 1.8382, tags: ['Hiking', 'Wellbeing'],
    desc: 'Surreal sculpted rock spires an hour from Barcelona. Winding ascents, breath-stealing horizons, and a stillness that clears the head.' },

  // ── 🇪🇬 EGYPT · around Cairo + deep trails ──
  { id: 'eg_wadi_degla', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Wadi Degla', area: 'Maadi, Cairo',
    lat: 29.9494, lng: 31.3021, tags: ['Hiking', 'Camping'],
    desc: 'A deep desert canyon minutes from the city. Group hikes, trail runs, quick overnight camps — and acoustic circles between the rock walls.' },
  { id: 'eg_petrified_forest', country: 'Egypt', flag: '🇪🇬', emoji: '🪵', name: 'Petrified Forest', area: 'New Cairo',
    lat: 30.0167, lng: 31.4667, tags: ['Hiking', 'Photo'],
    desc: 'Million-year-old tree trunks turned to stone, right by the Fifth Settlement. The fastest real escape from east Cairo — strange geology, great frames.' },
  { id: 'eg_padel_east', country: 'Egypt', flag: '🇪🇬', emoji: '🎾', name: 'Padel Hubs · East Cairo', area: 'New Cairo',
    lat: 30.0270, lng: 31.4913, tags: ['Sport', 'Community'],
    desc: 'The open padel compounds of east Cairo — matches, lounges, and an energetic sports crowd. Play a set, meet your next crew.' },
  { id: 'eg_sinai_trail', country: 'Egypt', flag: '🇪🇬', emoji: '🥾', name: 'Sinai Trail (start)', area: 'Ras Shetan',
    lat: 29.0410, lng: 34.6250, tags: ['Hiking', 'Culture'],
    desc: 'Egypt\'s first long-distance hiking trail — days of walking with Bedouin guides through mountains, wadis and hidden oases. The deepest cultural exchange there is.' },
  { id: 'eg_ras_shetan', country: 'Egypt', flag: '🇪🇬', emoji: '⛺', name: 'Ras Shetan', area: 'Nuweiba',
    lat: 29.0480, lng: 34.6280, tags: ['Camping', 'Wellbeing'],
    desc: 'Eco-camps scattered between mountains and sea. Honest disconnection, starlit skies, workshop circles — positive solitude at its purest.' },
  { id: 'eg_tunis_village', country: 'Egypt', flag: '🇪🇬', emoji: '🏺', name: 'Tunis Village', area: 'Fayoum',
    lat: 29.4062, lng: 30.5288, tags: ['Culture', 'Craft'],
    desc: 'A whole village of potters and artists above Lake Qarun. Green countryside frames, hands-on ceramic workshops, and real exchange with local makers.' },
  { id: 'eg_tuwailat', country: 'Egypt', flag: '🇪🇬', emoji: '🎸', name: 'Jabal El-Tuwailat Camp', area: 'Dahab',
    lat: 28.5062, lng: 34.4826, tags: ['Camping', 'Music'],
    desc: 'A short evening trek into Dahab\'s mountains ending at an open Bedouin camp. Guitar around the fire, stories in the circle, stars everywhere.' },

  // ── 🇪🇬 WESTERN DESERT · another planet ──
  { id: 'eg_black_desert', country: 'Egypt', flag: '🇪🇬', emoji: '🌋', name: 'Black Desert', area: 'Bahariya',
    lat: 28.2000, lng: 28.8600, tags: ['Hiking', 'Photo'],
    desc: 'Volcanic hills dusted in black basalt. Climb the English Mountain at sunset for a gold-on-black panorama that looks unreal on camera.' },
  { id: 'eg_crystal_mountain', country: 'Egypt', flag: '🇪🇬', emoji: '💎', name: 'Crystal Mountain', area: 'Bahariya–Farafra road',
    lat: 27.3300, lng: 28.4200, tags: ['Photo', 'Geology'],
    desc: 'A ridge made of glittering quartz crystals catching the sun. One of the rarest formations anywhere — a five-minute stop you\'ll never forget.' },
  { id: 'eg_agabat', country: 'Egypt', flag: '🇪🇬', emoji: '🏂', name: 'Agabat Valley', area: 'Farafra',
    lat: 27.2600, lng: 28.1500, tags: ['Sandboard', 'Camping'],
    desc: 'Soft dunes against giant chalk sculptures — the Western Desert\'s best sandboarding, and a totally isolated evening camp spot.' },
  { id: 'eg_white_desert', country: 'Egypt', flag: '🇪🇬', emoji: '🍄', name: 'White Desert', area: 'National Park',
    lat: 27.1000, lng: 27.9700, tags: ['Camping', 'Stars'],
    desc: 'The crown jewel: wind-carved white chalk shapes (the Mushroom, the Chicken) glowing under moonlight like a frozen planet. Absolute silence, Milky Way overhead — Egypt\'s greatest campsite.' },
  { id: 'eg_great_sand_sea', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Great Sand Sea', area: 'near Siwa',
    lat: 29.0500, lng: 25.3500, tags: ['Adrenaline', 'Detox'],
    desc: 'The world\'s third-largest dune field. Dune bashing by 4x4, then camping with zero signal — the ultimate digital detox.' },
  { id: 'eg_bir_wahed', country: 'Egypt', flag: '🇪🇬', emoji: '♨️', name: 'Bir Wahed', area: 'Siwa',
    lat: 29.1300, lng: 25.4600, tags: ['Wellbeing', 'Swim'],
    desc: 'A hot sulphur spring and a cold lake in the middle of the sand sea. Swimming between golden dunes — surreal and deeply restorative.' },
  { id: 'eg_qasr_dakhla', country: 'Egypt', flag: '🇪🇬', emoji: '🏘️', name: 'Al-Qasr Village', area: 'Dakhla Oasis',
    lat: 25.6961, lng: 28.8843, tags: ['Culture', 'History'],
    desc: 'A living maze of Ayyubid-era mud-brick houses under palm-wood covered lanes. Walking it is time travel — dramatic visual storytelling material.' },
  { id: 'eg_hibis', country: 'Egypt', flag: '🇪🇬', emoji: '🏛️', name: 'Hibis Temple & Bagawat', area: 'Kharga Oasis',
    lat: 25.4740, lng: 30.5510, tags: ['Culture', 'History'],
    desc: 'Ancient Egyptian and early-Christian heritage side by side in the deep desert — a rarely-visited harmony of civilisations.' },
  { id: 'eg_gilf_kebir', country: 'Egypt', flag: '🇪🇬', emoji: '🧭', name: 'Gilf Kebir', area: 'far southwest',
    lat: 23.2500, lng: 25.8000, tags: ['Expedition', 'Extreme'],
    desc: 'The ultimate expedition: days of driving to the Cave of Swimmers and prehistoric rock art. A journey that changes how you see everything. Pros only.' },

  // ── 🕊️ THE HOLY LAND · الأرض المقدسة — heritage sacred to three
  //    faiths, grouped by its shared name (the owner's peaceful choice) ──
  { id: 'hl_jerusalem', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '✨', name: 'Old City of Jerusalem', area: 'Jerusalem',
    lat: 31.7767, lng: 35.2323, tags: ['Faith', 'Culture'],
    desc: 'Al-Aqsa Mosque — the first qibla — the Church of the Holy Sepulchre and the Western Wall, all inside one square kilometre of walled stone lanes. Sacred to three faiths; there is nowhere else like it on Earth.' },
  { id: 'ps_bethlehem', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '⛪', name: 'Bethlehem Old City', area: 'Bethlehem',
    lat: 31.7054, lng: 35.2024, tags: ['Culture', 'History'],
    desc: 'The Church of the Nativity and stone alleys layered with two thousand years of story. Craft workshops, olive-wood carvers, and a market that has never stopped.' },
  { id: 'ps_jericho', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '🏜️', name: 'Jericho & Mount of Temptation', area: 'Jordan Valley',
    lat: 31.8611, lng: 35.4444, tags: ['Hiking', 'History'],
    desc: 'One of the oldest cities on Earth, below sea level in the Jordan Valley. Cable car or hike up to the cliff monastery for the full valley panorama.' },
  { id: 'ps_battir', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '🌿', name: 'Battir Terraces', area: 'near Bethlehem',
    lat: 31.7275, lng: 35.1364, tags: ['Hiking', 'Culture'],
    desc: 'UNESCO-listed ancient irrigation terraces still farmed the same way after millennia. Green valley trails, spring water channels, and village hospitality.' },
  { id: 'ps_wadi_qelt', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '🏞️', name: 'Wadi Qelt · St. George Monastery', area: 'Jericho desert',
    lat: 31.8447, lng: 35.4139, tags: ['Hiking', 'Wellbeing'],
    desc: 'A dramatic desert canyon hike ending at a monastery carved into the cliff face. Silence, echoing rock walls, and one of the region\'s great walking routes.' },

  // ── 🇸🇦 SAUDI ARABIA ──
  { id: 'sa_wadi_disah', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🏞️', name: 'Wadi Disah', area: 'Tabuk',
    lat: 27.6414, lng: 36.5091, tags: ['Hiking', 'Camping'],
    desc: 'Towering sandstone pillars over freshwater streams and palms. Walking (and wading) through it feels like entering another world.' },
  { id: 'sa_edge_world', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🪨', name: 'Edge of the World', area: 'Riyadh',
    lat: 24.9500, lng: 45.9900, tags: ['Adrenaline', 'Hiking'],
    desc: 'The Tuwaiq cliffs ending in a sheer vertical drop over an endless valley. Standing on the rim is pure adrenaline and pure scale.' },
  { id: 'sa_alula', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🐘', name: 'AlUla · Elephant Rock', area: 'AlUla',
    lat: 26.6323, lng: 38.0294, tags: ['Culture', 'Wellbeing'],
    desc: 'A world capital of desert culture and arts. Trails between sculpted rocks, open-air meditation and yoga, heritage meeting modern festivals.' },
  { id: 'sa_rijal_almaa', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🏰', name: 'Rijal Almaa', area: 'Asir',
    lat: 18.2000, lng: 42.1560, tags: ['Culture', 'Photo'],
    desc: 'A stone-and-clay heritage village with painted windows, set in a green mountain valley. Every alley climb tells a visual story.' },
  { id: 'sa_soudah', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🌫️', name: 'Jabal Soudah', area: 'Abha',
    lat: 18.2731, lng: 42.3649, tags: ['Hiking', 'Wellbeing'],
    desc: 'The Kingdom\'s highest peak — juniper forests in the clouds. Cool misty air, long trails, and mindfulness weather all year.' },

  // ── 🌍 WORLD ──
  { id: 'jo_wadi_rum', country: 'Jordan', flag: '🇯🇴', emoji: '🌕', name: 'Wadi Rum', area: 'Jordan',
    lat: 29.5320, lng: 35.4190, tags: ['Camping', 'Culture'],
    desc: 'The Valley of the Moon — red sands and Mars-like massifs. One of Earth\'s greatest camps: Bedouin zarb dinners and stories around the fire.' },
  { id: 'tr_cappadocia', country: 'Türkiye', flag: '🇹🇷', emoji: '🎈', name: 'Cappadocia · Rose Valley', area: 'Göreme',
    lat: 38.6600, lng: 34.8500, tags: ['Hiking', 'Photo'],
    desc: 'Beyond the balloons: winding trails through fairy-chimney valleys and rock-carved churches. Dawn here is a filmmaker\'s dream.' },
  { id: 'id_batur', country: 'Indonesia', flag: '🇮🇩', emoji: '🌋', name: 'Mount Batur', area: 'Bali',
    lat: -8.2420, lng: 115.3750, tags: ['Hiking', 'Wellbeing'],
    desc: 'A pre-dawn volcano climb ending above the clouds at sunrise. Descend to natural hot springs — Bali\'s body-and-soul reset.' },
  { id: 'it_dolomites', country: 'Italy', flag: '🇮🇹', emoji: '🏔️', name: 'Dolomites · Tre Cime', area: 'Italy',
    lat: 46.6180, lng: 12.3020, tags: ['Climbing', 'Hiking'],
    desc: 'Via Ferrata country — hike-climbs on fixed cables between jagged peaks, nights in rifugio huts with adventurers from everywhere.' },
  { id: 'ma_chefchaouen', country: 'Morocco', flag: '🇲🇦', emoji: '🔵', name: 'Chefchaouen', area: 'Morocco',
    lat: 35.1714, lng: -5.2697, tags: ['Culture', 'Photo'],
    desc: 'The blue city — an open-air film set with unusual inner calm. Base camp for the Akchour falls hike nearby.' },
  { id: 'ma_akchour', country: 'Morocco', flag: '🇲🇦', emoji: '💧', name: 'Akchour Waterfalls', area: 'Rif Mountains',
    lat: 35.2432, lng: -5.1802, tags: ['Hiking', 'Swim'],
    desc: 'A mountain hike along turquoise pools ending at grand waterfalls — swim in the natural basins, full Rif-mountain culture around you.' },
  { id: 'es_tenerife', country: 'Spain', flag: '🇪🇸', emoji: '🌋', name: 'Tenerife · Mount Teide', area: 'Canary Islands',
    lat: 28.2720, lng: -16.6420, tags: ['Hiking', 'Sport'],
    desc: 'Volcano treks in the morning, world-class padel communities by evening. Black volcanic sands against green forests — striking content everywhere.' },
  { id: 'lk_ella', country: 'Sri Lanka', flag: '🇱🇰', emoji: '🚂', name: 'Ella · Nine Arches', area: 'Sri Lanka',
    lat: 6.8770, lng: 81.0610, tags: ['Hiking', 'Wellbeing'],
    desc: 'Tea-plantation trails (Little Adam\'s Peak) and the train crossing the Nine Arches Bridge through jungle — a classic cinematic moment. Travelers from everywhere, energy for days.' },
];
