/* ── CURATED DESTINATIONS · real places, real coordinates ──────────
   Hand-picked adventure & culture spots across Egypt, Romania, Spain
   and France. Every pin sits at the place's true GPS position; tapping
   one opens the guide sheet (description, community reviews, Uber,
   directions). */

export const DESTINATIONS = [
  // ── 🇵🇸 PALESTINE ──
  // Real places at their real coordinates, listed exactly the way every
  // other country here is listed. Nothing about this is decoration:
  // these are cities and sites people come from, live in and travel to,
  // and a map that claims to show the world has to show them.
  { id: 'ps_jerusalem_old', hero: true, country: 'Palestine', flag: '🇵🇸', emoji: '🕌', name: 'Old City of Jerusalem', area: 'Jerusalem · القدس',
    lat: 31.7767, lng: 35.2345, tags: ['Culture', 'Heritage'],
    desc: 'Walled streets barely three metres wide opening onto stone courtyards, markets and rooftops. A UNESCO World Heritage site and one of the oldest continuously inhabited quarters on earth.' },
  { id: 'ps_aqsa', country: 'Palestine', flag: '🇵🇸', emoji: '🕌', name: 'Al-Aqsa Compound', area: 'Jerusalem · القدس',
    lat: 31.7780, lng: 35.2354, tags: ['Culture', 'Heritage'],
    desc: 'The walled esplanade above the Old City, the Dome of the Rock at its centre — its gold catching the light across the whole skyline.' },
  { id: 'ps_bethlehem', country: 'Palestine', flag: '🇵🇸', emoji: '⛪', name: 'Bethlehem', area: 'West Bank · بيت لحم',
    lat: 31.7054, lng: 35.2024, tags: ['Culture', 'Heritage'],
    desc: 'Manger Square, the Church of the Nativity, and limestone streets full of workshops carving olive wood the way families here have for generations.' },
  { id: 'ps_nablus', country: 'Palestine', flag: '🇵🇸', emoji: '🍮', name: 'Nablus Old Town', area: 'Nablus · نابلس',
    lat: 32.2211, lng: 35.2544, tags: ['Food', 'Culture'],
    desc: 'The kunafa capital, and it earns the title — trays of it pulled hot from the oven all day. Ottoman soap factories, vaulted alleys, and one of the most alive old markets anywhere.' },
  { id: 'ps_jericho', country: 'Palestine', flag: '🇵🇸', emoji: '🌴', name: 'Jericho', area: 'Jordan Valley · أريحا',
    lat: 31.8667, lng: 35.4500, tags: ['Heritage', 'Hiking'],
    desc: 'One of the oldest cities on earth and the lowest on the planet, ringed by date palms. The cable car to the Mount of Temptation looks out over the whole valley.' },
  { id: 'ps_hebron', country: 'Palestine', flag: '🇵🇸', emoji: '🍇', name: 'Hebron Old City', area: 'Hebron · الخليل',
    lat: 31.5246, lng: 35.1100, tags: ['Culture', 'Heritage'],
    desc: 'Stone-vaulted markets with glassblowers and potters still working the way the city has for centuries, around the Ibrahimi Mosque.' },
  { id: 'ps_gaza_coast', country: 'Palestine', flag: '🇵🇸', emoji: '🌊', name: 'Gaza Coast', area: 'Gaza · غزة',
    lat: 31.5170, lng: 34.4400, tags: ['Sea', 'Calm'],
    desc: 'Forty kilometres of Mediterranean shoreline, fishing boats going out before dawn, and a coast people have lived and worked along for thousands of years.' },
  { id: 'ps_battir', country: 'Palestine', flag: '🇵🇸', emoji: '🌿', name: 'Battir Terraces', area: 'Bethlehem · بتير',
    lat: 31.7278, lng: 35.1372, tags: ['Hiking', 'Heritage'],
    desc: 'Stone farming terraces stepping down the hillsides, still watered by a Roman-era irrigation system that has never stopped running. UNESCO World Heritage, and one of the best walks in the region.' },
  { id: 'ps_ramallah', country: 'Palestine', flag: '🇵🇸', emoji: '🎭', name: 'Ramallah', area: 'West Bank · رام الله',
    lat: 31.8996, lng: 35.2042, tags: ['Nightlife', 'Culture'],
    desc: 'Cafés that stay full past midnight, live music, galleries and a young crowd — the most restless, most current city in the country.' },
  { id: 'ps_akka', country: 'Palestine', flag: '🇵🇸', emoji: '⚓', name: 'Akka Old Port', area: 'Acre · عكا',
    lat: 32.9219, lng: 35.0691, tags: ['Sea', 'Heritage'],
    desc: 'A walled Crusader-era port city on the Mediterranean — sea walls, a khan, an underground Templar tunnel, and fishing boats still tied up where they always were.' },
  // ── 🇪🇬 EGYPT ──
  { id: 'eg_cave_church', country: 'Egypt', flag: '🇪🇬', emoji: '⛪', name: 'St. Simon Cave Church', area: 'Mokattam, Cairo',
    lat: 30.0329, lng: 31.2757, tags: ['Culture', 'Calm'],
    desc: 'A breathtaking monastery carved straight into Mokattam mountain. Vast rock-hewn halls, a deeply peaceful vibe, and one of Cairo\'s most surreal escapes from the noise.' },
  { id: 'eg_mario_ropes', country: 'Egypt', flag: '🇪🇬', emoji: '🧗', name: 'Mario High Ropes', area: 'Mokattam, Cairo',
    lat: 30.0341, lng: 31.2744, tags: ['Adrenaline', 'Groups'],
    desc: 'Ropes courses and ziplines strung between the rocky heights next to the Cave Church. Physical challenges for every fitness level — perfect for a crew day out.' },
  { id: 'eg_giza_complex', hero: true, country: 'Egypt', flag: '🇪🇬', emoji: '🐫', name: 'Giza Pyramids Plateau', area: 'Giza',
    lat: 29.9773, lng: 31.1325, tags: ['Culture', 'Hiking'],
    desc: 'The legendary plateau — open desert paths for long walks between the monuments and panoramic views where ancient history meets the horizon.' },
  { id: 'eg_khufu', country: 'Egypt', flag: '🇪🇬', emoji: '🔺', name: 'Great Pyramid of Khufu', area: 'Giza',
    lat: 29.9792, lng: 31.1342, tags: ['Adventure', 'Culture'],
    desc: 'The last ancient wonder still standing. Descend through the narrow passages into its inner chambers — a real physical and mental mini-expedition.' },
  { id: 'eg_khafre', country: 'Egypt', flag: '🇪🇬', emoji: '⛰️', name: 'Pyramid of Khafre', area: 'Giza',
    lat: 29.9761, lng: 31.1308, tags: ['Culture', 'Photo'],
    desc: 'Second tallest, still crowned with its original casing stones. The most photogenic angle on the plateau and the visual anchor of the whole complex.' },
  { id: 'eg_queens', country: 'Egypt', flag: '🇪🇬', emoji: '👑', name: 'Queens\' Pyramids', area: 'Giza',
    lat: 29.9785, lng: 31.1365, tags: ['Calm', 'Culture'],
    desc: 'The smaller pyramids on the eastern side — quieter, less crowded, and perfect for slowly taking in the fine architectural details of the ancient necropolis.' },
  { id: 'eg_giza_pass', country: 'Egypt', flag: '🇪🇬', emoji: '🎫', name: 'Giza Pyramids Entrance', area: 'Giza',
    lat: 29.9814, lng: 31.1329, tags: ['Meet point'],
    desc: 'The official gate and ticket point — the natural meetup spot for your squad before heading into the plateau together.' },
  { id: 'eg_coloured_canyon', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Coloured Canyon', area: 'Nuweiba, Sinai',
    lat: 29.0400, lng: 34.5630, tags: ['Hiking', 'Wellbeing'],
    desc: 'Hike through winding rock corridors painted in unreal colours. Camping, silence, and the best kind of digital detox — Sinai at its most magical.' },

  // ── 🇷🇴 ROMANIA ──
  { id: 'ro_transfagarasan', country: 'Romania', flag: '🇷🇴', emoji: '🛣️', name: 'Transfăgărășan', area: 'Carpathians',
    lat: 45.6036, lng: 24.6173, tags: ['Adventure', 'Hiking'],
    desc: 'One of the most spectacular mountain roads on Earth, winding past glacial lakes and green cliffs. A paradise for camping and high-altitude trail days.' },
  { id: 'ro_cheile_turzii', country: 'Romania', flag: '🇷🇴', emoji: '🏞️', name: 'Cheile Turzii Gorge', area: 'Cluj',
    lat: 46.5628, lng: 23.6817, tags: ['Hiking', 'Adrenaline'],
    desc: 'A deep natural gorge with stream crossings, hanging bridges and cave detours. Intense, beautiful, and pure wild nature from start to finish.' },
  { id: 'ro_bran', hero: true, country: 'Romania', flag: '🇷🇴', emoji: '🏰', name: 'Bran Castle', area: 'Transylvania',
    lat: 45.5152, lng: 25.3672, tags: ['Culture', 'Mystery'],
    desc: 'The cliff-edge castle behind the Dracula legend. Secret passages, narrow stairways, and a panoramic view over Transylvania\'s dense forests.' },

  // ── 🇪🇸 SPAIN ──
  { id: 'es_caminito_north', hero: true, country: 'Spain', flag: '🇪🇸', emoji: '🥾', name: 'Caminito del Rey · North', area: 'Málaga',
    lat: 36.9370, lng: -4.8040, tags: ['Adrenaline', 'Hiking'],
    desc: 'The northern gateway to the world\'s most famous cliff-side walkway — boardwalks pinned to a sheer canyon wall. A serious adrenaline dose with jaw-dropping views.' },
  { id: 'es_caminito_tickets', country: 'Spain', flag: '🇪🇸', emoji: '🎟️', name: 'Caminito del Rey · Tickets', area: 'El Chorro',
    lat: 36.9155, lng: -4.7616, tags: ['Meet point'],
    desc: 'The visitor reception — tickets, safety briefing and gear. The meetup point for groups before the walkway adventure begins.' },
  { id: 'es_caminito_playa', country: 'Spain', flag: '🇪🇸', emoji: '🏖️', name: 'Caminito del Rey · Playa', area: 'Ardales',
    lat: 36.9430, lng: -4.8010, tags: ['Calm', 'Swim'],
    desc: 'A turquoise lake beach right by the trailheads — the perfect wind-down after the cliff walk. Balance the adrenaline with pure calm.' },
  { id: 'es_portaventura', country: 'Spain', flag: '🇪🇸', emoji: '🎢', name: 'PortAventura World', area: 'Tarragona',
    lat: 41.0870, lng: 1.1560, tags: ['Adrenaline', 'Fun'],
    desc: 'A massive theme park with some of Europe\'s fastest coasters, live shows and full-day energy. Maximum adrenaline, zero hiking boots required.' },

  // ── 🇫🇷 FRANCE ──
  { id: 'fr_verdon', country: 'France', flag: '🇫🇷', emoji: '🛶', name: 'Verdon Gorge', area: 'Provence',
    lat: 43.7496, lng: 6.3285, tags: ['Rafting', 'Hiking'],
    desc: '"Europe\'s Grand Canyon" — turquoise rapids between towering cliffs. Rafting, advanced trails and climbing routes for the truly brave.' },
  { id: 'fr_chamonix', country: 'France', flag: '🇫🇷', emoji: '🏔️', name: 'Chamonix', area: 'French Alps',
    lat: 45.9237, lng: 6.8694, tags: ['Climbing', 'Adventure'],
    desc: 'The iconic Alpine town at the foot of Mont Blanc. Cable cars, climbing routes and long-distance trails — the absolute dream base for mountain people.' },
  { id: 'fr_eiffel', hero: true, country: 'France', flag: '🇫🇷', emoji: '🗼', name: 'Eiffel Tower', area: 'Paris',
    lat: 48.8584, lng: 2.2945, tags: ['Culture', 'Photo'],
    desc: 'The classic — but take the stairs and it becomes a workout with the best panoramic reward in Paris. Iron-lattice engineering meets serious altitude.' },
  { id: 'fr_calanques', country: 'France', flag: '🇫🇷', emoji: '⛰️', name: 'Calanques National Park', area: 'Marseille',
    lat: 43.2100, lng: 5.4450, tags: ['Hiking', 'Swim'],
    desc: 'White limestone cliffs plunging into turquoise coves. Tough coastal hikes down to hidden bays — raw effort rewarded with the Mediterranean\'s best swim.' },
  { id: 'fr_gavarnie', country: 'France', flag: '🇫🇷', emoji: '🏞️', name: 'Cirque de Gavarnie', area: 'Pyrénées',
    lat: 42.6953, lng: -0.0113, tags: ['Hiking', 'Wellbeing'],
    desc: 'A colossal natural amphitheatre with towering waterfalls. The walk in puts you face-to-face with the mountains\' full scale — deep-recharge territory.' },

  // ── 🇪🇬 EGYPT · Sinai, Fayoum & Siwa (camping + culture) ──
  { id: 'eg_mount_sinai', country: 'Egypt', flag: '🇪🇬', emoji: '🌄', name: 'Mount Sinai (Jabal Musa)', area: 'Saint Catherine',
    lat: 28.5394, lng: 33.9750, tags: ['Hiking', 'Camping', 'Culture'],
    desc: 'The legendary night hike that ends with sunrise from the summit. Bedouin guides, campfire circles, and one of the most soul-resetting experiences in Egypt.' },
  { id: 'eg_wadi_hitan', country: 'Egypt', flag: '🇪🇬', emoji: '🐋', name: 'Wadi El-Hitan (Whale Valley)', area: 'Fayoum',
    lat: 29.2703, lng: 30.0410, tags: ['Camping', 'Calm'],
    desc: 'A UNESCO desert valley scattered with 40-million-year-old whale fossils. Walking trails between the rock formations and star-drenched camping silence.' },
  { id: 'eg_cleopatra_spring', country: 'Egypt', flag: '🇪🇬', emoji: '♨️', name: 'Cleopatra Spring', area: 'Siwa Oasis',
    lat: 29.2077, lng: 25.5528, tags: ['Swim', 'Culture'],
    desc: 'A natural stone spring in the heart of Siwa — warm water, palm groves, and eco-cafés where you actually talk with the locals. Healing in every sense.' },
  { id: 'eg_siwa_salt', country: 'Egypt', flag: '🇪🇬', emoji: '🧂', name: 'Siwa Salt Lakes', area: 'Siwa Oasis',
    lat: 29.2211, lng: 25.6390, tags: ['Wellbeing', 'Photo'],
    desc: 'Impossibly turquoise pools ringed by white salt crystals — so salty you float without trying. Otherworldly to see, genuinely therapeutic to swim.' },
  { id: 'eg_shali', country: 'Egypt', flag: '🇪🇬', emoji: '🏯', name: 'Shali Fortress', area: 'Siwa Oasis',
    lat: 29.2032, lng: 25.5196, tags: ['Culture', 'Sunset'],
    desc: 'A melting salt-and-mud citadel rising from the oasis. Climb its winding paths at sunset for the full palm-grove panorama and real Siwan heritage.' },
  { id: 'eg_wadi_rayan', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Wadi El Rayan', area: 'Fayoum',
    lat: 29.2036, lng: 30.4106, tags: ['Camping', 'Hiking'],
    desc: 'Twin desert lakes wrapped in golden dunes. Vast open freedom — long walks, dune lines to the horizon, and pure escape from the city.' },
  { id: 'eg_rayan_falls', country: 'Egypt', flag: '🇪🇬', emoji: '💦', name: 'Wadi El Rayan Waterfalls', area: 'Fayoum',
    lat: 29.2069, lng: 30.4084, tags: ['Photo', 'Fun'],
    desc: 'Waterfalls in the middle of the desert — the water-on-sand contrast is unreal. Wooden boat rides between the lakes seal the day.' },
  { id: 'eg_magic_lake', country: 'Egypt', flag: '🇪🇬', emoji: '✨', name: 'Magic Lake Camp', area: 'Fayoum',
    lat: 29.2278, lng: 30.4438, tags: ['Camping', 'Adrenaline'],
    desc: 'The lake that changes colour with the sun. Sandboarding down the surrounding dunes by day, campfires under the stars by night.' },
  { id: 'eg_blue_hole', country: 'Egypt', flag: '🇪🇬', emoji: '🤿', name: 'The Blue Hole', area: 'Dahab',
    lat: 28.5720, lng: 34.5370, tags: ['Diving', 'Adrenaline'],
    desc: 'One of the most famous dive sites on Earth. Deep-blue abyss, world-class reef, and laid-back cliffside cafés full of divers swapping stories.' },
  { id: 'eg_nayzak', country: 'Egypt', flag: '🇪🇬', emoji: '💠', name: 'Al-Nayzak Pool', area: 'Marsa Alam',
    lat: 25.2494, lng: 34.7996, tags: ['Swim', 'Calm'],
    desc: 'A meteor-shaped natural rock pool open to the Red Sea — glass-clear turquoise water in untouched surroundings. Swim, float, reset.' },
  { id: 'eg_wadi_gemal', country: 'Egypt', flag: '🇪🇬', emoji: '🐪', name: 'Wadi el Gemal Reserve', area: 'Marsa Alam',
    lat: 24.6833, lng: 35.0833, tags: ['Safari', 'Culture'],
    desc: 'Mountains meeting mangrove beaches. Deep safari trails, migrating birds, hidden bays — and the living culture of the Ababda tribes.' },
  { id: 'eg_ras_mohamed', country: 'Egypt', flag: '🇪🇬', emoji: '🪸', name: 'Ras Mohamed', area: 'Sharm El-Sheikh',
    lat: 27.7373, lng: 34.2455, tags: ['Hiking', 'Diving'],
    desc: 'Where the two gulfs meet: cliff walks to hidden beaches, a mysterious salt lake, and reef walls with colours you won\'t believe from above.' },

  // ── 🇪🇬 CAIRO · historic streets (El-Moez energy) ──
  { id: 'eg_khan_khalili', country: 'Egypt', flag: '🇪🇬', emoji: '🏮', name: 'Khan el-Khalili', area: 'Historic Cairo',
    lat: 30.0477, lng: 31.2622, tags: ['Culture', 'Photo'],
    desc: 'One of the oldest bazaars on Earth — alleys of light, colour and craft. Cinematic at every corner, and every shopkeeper has a story.' },
  { id: 'eg_wekalet_ghouri', country: 'Egypt', flag: '🇪🇬', emoji: '🎭', name: 'Wekalet El-Ghouri', area: 'Al-Azhar, Cairo',
    lat: 30.0455, lng: 31.2610, tags: ['Culture', 'Shows'],
    desc: 'A jewel of Mamluk architecture steps from Al-Azhar — dramatic light and symmetry, home of the whirling Tanoura shows.' },
  { id: 'eg_azhar_park', country: 'Egypt', flag: '🇪🇬', emoji: '🌳', name: 'Al-Azhar Park', area: 'Cairo',
    lat: 30.0409, lng: 31.2657, tags: ['Calm', 'Sunset'],
    desc: 'A green hill above Historic Cairo\'s minarets. Wide lawns for unwinding, playing music, and the city\'s best sunset panorama.' },
  { id: 'eg_religions', country: 'Egypt', flag: '🇪🇬', emoji: '🕌', name: 'Religious Complex', area: 'Old Cairo',
    lat: 30.0059, lng: 31.2300, tags: ['Culture', 'Calm'],
    desc: 'Churches, mosques and a synagogue woven into narrow ancient stone lanes. Deeply spiritual, quiet, and made for slow exploration.' },
  { id: 'eg_pottery', country: 'Egypt', flag: '🇪🇬', emoji: '🏺', name: 'Fustat Pottery Village', area: 'Old Cairo',
    lat: 30.0089, lng: 31.2379, tags: ['Culture', 'Craft'],
    desc: 'Watch master potters shape clay with their hands. Warm earthy colours, real interaction with the makers — a content-creation goldmine.' },

  // ── 🇷🇴 ROMANIA · deep-nature hikes ──
  { id: 'ro_bucegi', country: 'Romania', flag: '🇷🇴', emoji: '🗻', name: 'Bucegi Mountains', area: 'Carpathians',
    lat: 45.4453, lng: 25.4567, tags: ['Hiking', 'Camping'],
    desc: 'A massive range with endless trails and wild camping in cool mountain air. Sweeping views at every ridge — made for crews who live outdoors.' },
  { id: 'ro_piatra', country: 'Romania', flag: '🇷🇴', emoji: '🌲', name: 'Piatra Craiului', area: 'National Park',
    lat: 45.5297, lng: 25.2320, tags: ['Climbing', 'Hiking'],
    desc: 'Romania\'s knife-edge ridge — rock climbing, narrow crest walks and dense forests full of wildlife. Teamwork territory, physically and mentally.' },
  { id: 'ro_piatra_visitor', country: 'Romania', flag: '🇷🇴', emoji: '🛖', name: 'Piatra Craiului Visitor Center', area: 'Zărnești',
    lat: 45.5665, lng: 25.3167, tags: ['Meet point'],
    desc: 'The first stop before the park — maps, wildlife info, safe camping zones, and the natural meetup spot before the group heads in.' },

  // ── 🇪🇸 SPAIN · mountain + spirit ──
  { id: 'es_picos', country: 'Spain', flag: '🇪🇸', emoji: '🏔️', name: 'Picos de Europa', area: 'Northern Spain',
    lat: 43.1938, lng: -4.8514, tags: ['Hiking', 'Culture'],
    desc: 'Deep gorges, dense forests and tiny mountain villages. Long trail days that end in rural Spanish culture — adventure with a soul.' },
  { id: 'es_montserrat', country: 'Spain', flag: '🇪🇸', emoji: '⛰️', name: 'Montserrat', area: 'near Barcelona',
    lat: 41.5955, lng: 1.8382, tags: ['Hiking', 'Wellbeing'],
    desc: 'Surreal sculpted rock spires an hour from Barcelona. Winding ascents, breath-stealing horizons, and a stillness that clears the head.' },

  // ── 🇪🇬 EGYPT · around Cairo + deep trails ──
  { id: 'eg_wadi_degla', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Wadi Degla', area: 'Maadi, Cairo',
    lat: 29.9494, lng: 31.3021, tags: ['Hiking', 'Camping'],
    desc: 'A deep desert canyon minutes from the city. Group hikes, trail runs, quick overnight camps — and acoustic circles between the rock walls.' },
  { id: 'eg_petrified_forest', country: 'Egypt', flag: '🇪🇬', emoji: '🪵', name: 'Petrified Forest', area: 'New Cairo',
    lat: 30.0167, lng: 31.4667, tags: ['Hiking', 'Photo'],
    desc: 'Million-year-old tree trunks turned to stone, right by the Fifth Settlement. The fastest real escape from east Cairo — strange geology, great frames.' },
  { id: 'eg_padel_east', country: 'Egypt', flag: '🇪🇬', emoji: '🎾', name: 'Padel Hubs · East Cairo', area: 'New Cairo',
    lat: 30.0270, lng: 31.4913, tags: ['Sport', 'Community'],
    desc: 'The open padel compounds of east Cairo — matches, lounges, and an energetic sports crowd. Play a set, meet your next crew.' },
  { id: 'eg_sinai_trail', country: 'Egypt', flag: '🇪🇬', emoji: '🥾', name: 'Sinai Trail (start)', area: 'Ras Shetan',
    lat: 29.0410, lng: 34.6250, tags: ['Hiking', 'Culture'],
    desc: 'Egypt\'s first long-distance hiking trail — days of walking with Bedouin guides through mountains, wadis and hidden oases. The deepest cultural exchange there is.' },
  { id: 'eg_ras_shetan', country: 'Egypt', flag: '🇪🇬', emoji: '⛺', name: 'Ras Shetan', area: 'Nuweiba',
    lat: 29.0480, lng: 34.6280, tags: ['Camping', 'Wellbeing'],
    desc: 'Eco-camps scattered between mountains and sea. Honest disconnection, starlit skies, workshop circles — positive solitude at its purest.' },
  { id: 'eg_tunis_village', country: 'Egypt', flag: '🇪🇬', emoji: '🏺', name: 'Tunis Village', area: 'Fayoum',
    lat: 29.4062, lng: 30.5288, tags: ['Culture', 'Craft'],
    desc: 'A whole village of potters and artists above Lake Qarun. Green countryside frames, hands-on ceramic workshops, and real exchange with local makers.' },
  { id: 'eg_tuwailat', country: 'Egypt', flag: '🇪🇬', emoji: '🎸', name: 'Jabal El-Tuwailat Camp', area: 'Dahab',
    lat: 28.5062, lng: 34.4826, tags: ['Camping', 'Music'],
    desc: 'A short evening trek into Dahab\'s mountains ending at an open Bedouin camp. Guitar around the fire, stories in the circle, stars everywhere.' },

  // ── 🇪🇬 WESTERN DESERT · another planet ──
  { id: 'eg_black_desert', country: 'Egypt', flag: '🇪🇬', emoji: '🌋', name: 'Black Desert', area: 'Bahariya',
    lat: 28.2000, lng: 28.8600, tags: ['Hiking', 'Photo'],
    desc: 'Volcanic hills dusted in black basalt. Climb the English Mountain at sunset for a gold-on-black panorama that looks unreal on camera.' },
  { id: 'eg_crystal_mountain', country: 'Egypt', flag: '🇪🇬', emoji: '💎', name: 'Crystal Mountain', area: 'Bahariya–Farafra road',
    lat: 27.3300, lng: 28.4200, tags: ['Photo', 'Geology'],
    desc: 'A ridge made of glittering quartz crystals catching the sun. One of the rarest formations anywhere — a five-minute stop you\'ll never forget.' },
  { id: 'eg_agabat', country: 'Egypt', flag: '🇪🇬', emoji: '🏂', name: 'Agabat Valley', area: 'Farafra',
    lat: 27.2600, lng: 28.1500, tags: ['Sandboard', 'Camping'],
    desc: 'Soft dunes against giant chalk sculptures — the Western Desert\'s best sandboarding, and a totally isolated evening camp spot.' },
  { id: 'eg_white_desert', country: 'Egypt', flag: '🇪🇬', emoji: '🍄', name: 'White Desert', area: 'National Park',
    lat: 27.1000, lng: 27.9700, tags: ['Camping', 'Stars'],
    desc: 'The crown jewel: wind-carved white chalk shapes (the Mushroom, the Chicken) glowing under moonlight like a frozen planet. Absolute silence, Milky Way overhead — Egypt\'s greatest campsite.' },
  { id: 'eg_great_sand_sea', country: 'Egypt', flag: '🇪🇬', emoji: '🏜️', name: 'Great Sand Sea', area: 'near Siwa',
    lat: 29.0500, lng: 25.3500, tags: ['Adrenaline', 'Detox'],
    desc: 'The world\'s third-largest dune field. Dune bashing by 4x4, then camping with zero signal — the ultimate digital detox.' },
  { id: 'eg_bir_wahed', country: 'Egypt', flag: '🇪🇬', emoji: '♨️', name: 'Bir Wahed', area: 'Siwa',
    lat: 29.1300, lng: 25.4600, tags: ['Wellbeing', 'Swim'],
    desc: 'A hot sulphur spring and a cold lake in the middle of the sand sea. Swimming between golden dunes — surreal and deeply restorative.' },
  { id: 'eg_qasr_dakhla', country: 'Egypt', flag: '🇪🇬', emoji: '🏘️', name: 'Al-Qasr Village', area: 'Dakhla Oasis',
    lat: 25.6961, lng: 28.8843, tags: ['Culture', 'History'],
    desc: 'A living maze of Ayyubid-era mud-brick houses under palm-wood covered lanes. Walking it is time travel — dramatic visual storytelling material.' },
  { id: 'eg_hibis', country: 'Egypt', flag: '🇪🇬', emoji: '🏛️', name: 'Hibis Temple & Bagawat', area: 'Kharga Oasis',
    lat: 25.4740, lng: 30.5510, tags: ['Culture', 'History'],
    desc: 'Ancient Egyptian and early-Christian heritage side by side in the deep desert — a rarely-visited harmony of civilisations.' },
  { id: 'eg_gilf_kebir', country: 'Egypt', flag: '🇪🇬', emoji: '🧭', name: 'Gilf Kebir', area: 'far southwest',
    lat: 23.2500, lng: 25.8000, tags: ['Expedition', 'Extreme'],
    desc: 'The ultimate expedition: days of driving to the Cave of Swimmers and prehistoric rock art. A journey that changes how you see everything. Pros only.' },

  // ── 🕊️ THE HOLY LAND · الأرض المقدسة — heritage sacred to three
  //    faiths, grouped by its shared name (the owner's peaceful choice) ──
  //
  //    Three of these — Bethlehem, Jericho, Battir — are deliberately
  //    also in the Palestine block above, and both listings are wanted.
  //    What was not wanted is that they carried the SAME id, so the two
  //    entries were one thing as far as any keyed list, marker or
  //    review lookup was concerned: reviews left on one appeared on the
  //    other. The hl_ prefix makes them two entries, as they always
  //    were meant to be.
  { id: 'hl_jerusalem', hero: true, country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '✨', name: 'Old City of Jerusalem', area: 'Jerusalem',
    lat: 31.7767, lng: 35.2323, tags: ['Faith', 'Culture'],
    desc: 'Al-Aqsa Mosque — the first qibla — the Church of the Holy Sepulchre and the Western Wall, all inside one square kilometre of walled stone lanes. Sacred to three faiths; there is nowhere else like it on Earth.' },
  { id: 'hl_bethlehem', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '⛪', name: 'Bethlehem Old City', area: 'Bethlehem',
    lat: 31.7054, lng: 35.2024, tags: ['Culture', 'History'],
    desc: 'The Church of the Nativity and stone alleys layered with two thousand years of story. Craft workshops, olive-wood carvers, and a market that has never stopped.' },
  { id: 'hl_jericho', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '🏜️', name: 'Jericho & Mount of Temptation', area: 'Jordan Valley',
    lat: 31.8611, lng: 35.4444, tags: ['Hiking', 'History'],
    desc: 'One of the oldest cities on Earth, below sea level in the Jordan Valley. Cable car or hike up to the cliff monastery for the full valley panorama.' },
  { id: 'hl_battir', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '🌿', name: 'Battir Terraces', area: 'near Bethlehem',
    lat: 31.7275, lng: 35.1364, tags: ['Hiking', 'Culture'],
    desc: 'UNESCO-listed ancient irrigation terraces still farmed the same way after millennia. Green valley trails, spring water channels, and village hospitality.' },
  { id: 'ps_wadi_qelt', country: 'الأرض المقدسة · Holy Land', flag: '🕊️', emoji: '🏞️', name: 'Wadi Qelt · St. George Monastery', area: 'Jericho desert',
    lat: 31.8447, lng: 35.4139, tags: ['Hiking', 'Wellbeing'],
    desc: 'A dramatic desert canyon hike ending at a monastery carved into the cliff face. Silence, echoing rock walls, and one of the region\'s great walking routes.' },

  // ── 🇸🇦 SAUDI ARABIA ──
  { id: 'sa_wadi_disah', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🏞️', name: 'Wadi Disah', area: 'Tabuk',
    lat: 27.6414, lng: 36.5091, tags: ['Hiking', 'Camping'],
    desc: 'Towering sandstone pillars over freshwater streams and palms. Walking (and wading) through it feels like entering another world.' },
  { id: 'sa_edge_world', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🪨', name: 'Edge of the World', area: 'Riyadh',
    lat: 24.9500, lng: 45.9900, tags: ['Adrenaline', 'Hiking'],
    desc: 'The Tuwaiq cliffs ending in a sheer vertical drop over an endless valley. Standing on the rim is pure adrenaline and pure scale.' },
  { id: 'sa_alula', hero: true, country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🐘', name: 'AlUla · Elephant Rock', area: 'AlUla',
    lat: 26.6323, lng: 38.0294, tags: ['Culture', 'Wellbeing'],
    desc: 'A world capital of desert culture and arts. Trails between sculpted rocks, open-air meditation and yoga, heritage meeting modern festivals.' },
  { id: 'sa_rijal_almaa', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🏰', name: 'Rijal Almaa', area: 'Asir',
    lat: 18.2000, lng: 42.1560, tags: ['Culture', 'Photo'],
    desc: 'A stone-and-clay heritage village with painted windows, set in a green mountain valley. Every alley climb tells a visual story.' },
  { id: 'sa_soudah', country: 'Saudi Arabia', flag: '🇸🇦', emoji: '🌫️', name: 'Jabal Soudah', area: 'Abha',
    lat: 18.2731, lng: 42.3649, tags: ['Hiking', 'Wellbeing'],
    desc: 'The Kingdom\'s highest peak — juniper forests in the clouds. Cool misty air, long trails, and mindfulness weather all year.' },

  // ── 🌍 WORLD ──
  { id: 'jo_wadi_rum', hero: true, country: 'Jordan', flag: '🇯🇴', emoji: '🌕', name: 'Wadi Rum', area: 'Jordan',
    lat: 29.5320, lng: 35.4190, tags: ['Camping', 'Culture'],
    desc: 'The Valley of the Moon — red sands and Mars-like massifs. One of Earth\'s greatest camps: Bedouin zarb dinners and stories around the fire.' },
  { id: 'tr_cappadocia', hero: true, country: 'Türkiye', flag: '🇹🇷', emoji: '🎈', name: 'Cappadocia · Rose Valley', area: 'Göreme',
    lat: 38.6600, lng: 34.8500, tags: ['Hiking', 'Photo'],
    desc: 'Beyond the balloons: winding trails through fairy-chimney valleys and rock-carved churches. Dawn here is a filmmaker\'s dream.' },
  { id: 'id_batur', hero: true, country: 'Indonesia', flag: '🇮🇩', emoji: '🌋', name: 'Mount Batur', area: 'Bali',
    lat: -8.2420, lng: 115.3750, tags: ['Hiking', 'Wellbeing'],
    desc: 'A pre-dawn volcano climb ending above the clouds at sunrise. Descend to natural hot springs — Bali\'s body-and-soul reset.' },
  { id: 'it_dolomites', hero: true, country: 'Italy', flag: '🇮🇹', emoji: '🏔️', name: 'Dolomites · Tre Cime', area: 'Italy',
    lat: 46.6180, lng: 12.3020, tags: ['Climbing', 'Hiking'],
    desc: 'Via Ferrata country — hike-climbs on fixed cables between jagged peaks, nights in rifugio huts with adventurers from everywhere.' },
  { id: 'ma_chefchaouen', hero: true, country: 'Morocco', flag: '🇲🇦', emoji: '🔵', name: 'Chefchaouen', area: 'Morocco',
    lat: 35.1714, lng: -5.2697, tags: ['Culture', 'Photo'],
    desc: 'The blue city — an open-air film set with unusual inner calm. Base camp for the Akchour falls hike nearby.' },
  { id: 'ma_akchour', country: 'Morocco', flag: '🇲🇦', emoji: '💧', name: 'Akchour Waterfalls', area: 'Rif Mountains',
    lat: 35.2432, lng: -5.1802, tags: ['Hiking', 'Swim'],
    desc: 'A mountain hike along turquoise pools ending at grand waterfalls — swim in the natural basins, full Rif-mountain culture around you.' },
  { id: 'es_tenerife', country: 'Spain', flag: '🇪🇸', emoji: '🌋', name: 'Tenerife · Mount Teide', area: 'Canary Islands',
    lat: 28.2720, lng: -16.6420, tags: ['Hiking', 'Sport'],
    desc: 'Volcano treks in the morning, world-class padel communities by evening. Black volcanic sands against green forests — striking content everywhere.' },
  { id: 'lk_ella', hero: true, country: 'Sri Lanka', flag: '🇱🇰', emoji: '🚂', name: 'Ella · Nine Arches', area: 'Sri Lanka',
    lat: 6.8770, lng: 81.0610, tags: ['Hiking', 'Wellbeing'],
    desc: 'Tea-plantation trails (Little Adam\'s Peak) and the train crossing the Nine Arches Bridge through jungle — a classic cinematic moment. Travelers from everywhere, energy for days.' },

  /* ── 🇪🇺 THE REST OF EUROPE, AND MORE OF MOROCCO ────────────────────
     Ayser: "زود بقيت امكن في اوربا اثينا مغرب".

     Europe was seven places in Spain, six in Romania, five in France
     and one in Italy — a map of a continent with twenty-odd countries
     missing from it, which is a poor showing for an app applying to
     live there. Every entry below sits at its real coordinates, and
     `area` is the CITY wherever there is one, because that is the key
     the arrival guide is filed under: land at the Acropolis and the
     first thirty days you are offered are Athens's.                  */

  // ── 🇬🇷 GREECE ──
  { id: 'gr_acropolis', hero: true, country: 'Greece', flag: '🇬🇷', emoji: '🏛️', name: 'The Acropolis', area: 'Athens',
    lat: 37.9715, lng: 23.7257, tags: ['Culture', 'Heritage'],
    desc: 'The Parthenon on its limestone hill, above a city that has been living underneath it for two and a half thousand years. Go at opening or an hour before closing — the light is better and the crowd is thinner.' },
  { id: 'gr_plaka', country: 'Greece', flag: '🇬🇷', emoji: '🏘️', name: 'Plaka', area: 'Athens',
    lat: 37.9725, lng: 23.7300, tags: ['Culture', 'Food'],
    desc: 'The old quarter under the Acropolis: stepped lanes, tavernas and bougainvillea, and the only part of central Athens that is genuinely made for walking.' },
  { id: 'gr_meteora', country: 'Greece', flag: '🇬🇷', emoji: '⛰️', name: 'Meteora', area: 'Kalabaka',
    lat: 39.7217, lng: 21.6306, tags: ['Heritage', 'Hiking'],
    desc: 'Monasteries built on top of sandstone pillars hundreds of metres above the plain. A UNESCO site you can walk between on footpaths rather than the road.' },
  { id: 'gr_santorini', country: 'Greece', flag: '🇬🇷', emoji: '🌅', name: 'Oia', area: 'Santorini',
    lat: 36.4618, lng: 25.3753, tags: ['Photo', 'Sunset'],
    desc: 'White houses down the rim of a flooded volcanic caldera. Famous for the sunset, and famous for how many people come for it — the walk from Fira is the better half of the day.' },
  { id: 'gr_delphi', country: 'Greece', flag: '🇬🇷', emoji: '🏺', name: 'Delphi', area: 'Delphi',
    lat: 38.4824, lng: 22.5010, tags: ['Culture', 'Heritage'],
    desc: 'The oracle the ancient world came to ask, on the slope of Mount Parnassus. The stadium at the top of the site is usually empty and is worth the climb.' },

  // ── 🇮🇹 ITALY ──
  { id: 'it_colosseum', country: 'Italy', flag: '🇮🇹', emoji: '🏟️', name: 'The Colosseum', area: 'Rome',
    lat: 41.8902, lng: 12.4922, tags: ['Culture', 'Heritage'],
    desc: 'Fifty thousand people fitted in here, and the engineering that moved them still shows in the arches. The Forum next door is included on the same ticket and is where the city actually ran.' },
  { id: 'it_venice', country: 'Italy', flag: '🇮🇹', emoji: '🛶', name: 'Rialto & the Grand Canal', area: 'Venice',
    lat: 45.4380, lng: 12.3358, tags: ['Culture', 'Photo'],
    desc: 'A city with no roads. The vaporetto down the Grand Canal costs a fraction of a gondola and shows you the same palaces from the water.' },
  { id: 'it_florence', country: 'Italy', flag: '🇮🇹', emoji: '🎨', name: 'The Duomo', area: 'Florence',
    lat: 43.7731, lng: 11.2560, tags: ['Culture', 'Heritage'],
    desc: 'Brunelleschi built the dome without a supporting frame and nobody has fully explained how. Climbing inside it is a different experience from looking at it.' },
  { id: 'it_positano', country: 'Italy', flag: '🇮🇹', emoji: '🍋', name: 'Positano', area: 'Amalfi Coast',
    lat: 40.6281, lng: 14.4850, tags: ['Photo', 'Swim'],
    desc: 'A town poured down a cliff into the sea. The Path of the Gods above it is the walk people come back for, and it is free.' },
  { id: 'it_cinque', country: 'Italy', flag: '🇮🇹', emoji: '🏘️', name: 'Vernazza', area: 'Cinque Terre',
    lat: 44.1354, lng: 9.6845, tags: ['Hiking', 'Swim'],
    desc: 'One of five fishing villages linked by coastal footpaths and a train that stops at each. The trail between them is the point; the train is there when your legs are done.' },

  // ── 🇵🇹 PORTUGAL ──
  { id: 'pt_alfama', hero: true, country: 'Portugal', flag: '🇵🇹', emoji: '🎶', name: 'Alfama', area: 'Lisbon',
    lat: 38.7139, lng: -9.1300, tags: ['Culture', 'Food'],
    desc: 'The oldest quarter, and the one the 1755 earthquake left standing. Steep lanes, viewpoints, and fado coming out of doorways in the evening.' },
  { id: 'pt_sintra', country: 'Portugal', flag: '🇵🇹', emoji: '🏰', name: 'Pena Palace', area: 'Sintra',
    lat: 38.7876, lng: -9.3906, tags: ['Heritage', 'Photo'],
    desc: 'A romanticist palace painted red and yellow on a hilltop in the forest, half an hour by train from Lisbon. Go early — the hill fills up by mid-morning.' },
  { id: 'pt_porto', country: 'Portugal', flag: '🇵🇹', emoji: '🍷', name: 'Ribeira', area: 'Porto',
    lat: 41.1408, lng: -8.6130, tags: ['Culture', 'Food'],
    desc: 'Tiled houses stacked above the Douro, with the port cellars on the far bank. Cross the Dom Luís I bridge on the upper deck for the view everyone photographs.' },
  { id: 'pt_benagil', country: 'Portugal', flag: '🇵🇹', emoji: '🌊', name: 'Benagil Cave', area: 'Algarve',
    lat: 37.0855, lng: -8.4256, tags: ['Swim', 'Photo'],
    desc: 'A sea cave with a hole in its roof and a beach inside it. Reachable by kayak or a small boat; the cliff walk above it is spectacular and costs nothing.' },

  // ── 🇳🇱 NETHERLANDS ──
  { id: 'nl_jordaan', hero: true, country: 'Netherlands', flag: '🇳🇱', emoji: '🚲', name: 'The Jordaan', area: 'Amsterdam',
    lat: 52.3745, lng: 4.8836, tags: ['Culture', 'Food'],
    desc: 'Canals, narrow houses and courtyards, best seen from a bicycle like everybody else. The canal ring is a UNESCO site and was dug in the seventeenth century.' },
  { id: 'nl_kinderdijk', country: 'Netherlands', flag: '🇳🇱', emoji: '🌬️', name: 'Kinderdijk Windmills', area: 'Kinderdijk',
    lat: 51.8839, lng: 4.6350, tags: ['Heritage', 'Photo'],
    desc: 'Nineteen eighteenth-century windmills that kept a whole polder dry, still standing in a row. Flat, so the whole site is walkable or cyclable.' },

  // ── 🇩🇪 GERMANY ──
  { id: 'de_neuschwanstein', hero: true, country: 'Germany', flag: '🇩🇪', emoji: '🏰', name: 'Neuschwanstein', area: 'Schwangau',
    lat: 47.5576, lng: 10.7498, tags: ['Heritage', 'Photo'],
    desc: 'The castle Ludwig II built and barely lived in, in the Bavarian Alps. The Marienbrücke bridge behind it is where the photograph comes from.' },
  { id: 'de_eastside', country: 'Germany', flag: '🇩🇪', emoji: '🎨', name: 'East Side Gallery', area: 'Berlin',
    lat: 52.5050, lng: 13.4394, tags: ['Culture', 'Photo'],
    desc: 'The longest surviving stretch of the Berlin Wall, painted by artists from all over the world in 1990. Over a kilometre of it, along the Spree.' },
  { id: 'de_bastei', country: 'Germany', flag: '🇩🇪', emoji: '🪨', name: 'Bastei Bridge', area: 'Saxon Switzerland',
    lat: 50.9613, lng: 14.0736, tags: ['Hiking', 'Photo'],
    desc: 'A stone bridge threaded between sandstone towers 190 metres above the Elbe. The national park around it has some of the best short hikes in the country.' },

  // ── 🇨🇿 CZECHIA ──
  { id: 'cz_charles', hero: true, country: 'Czechia', flag: '🇨🇿', emoji: '🌉', name: 'Charles Bridge', area: 'Prague',
    lat: 50.0865, lng: 14.4114, tags: ['Culture', 'Heritage'],
    desc: 'Begun in 1357, lined with baroque statues, and completely different at six in the morning than at midday. The castle side is where the good views are.' },
  { id: 'cz_krumlov', country: 'Czechia', flag: '🇨🇿', emoji: '🏘️', name: 'Český Krumlov', area: 'Český Krumlov',
    lat: 48.8127, lng: 14.3175, tags: ['Heritage', 'Photo'],
    desc: 'A medieval town wrapped in a loop of the Vltava, with a castle above it and a rafting route straight through the middle in summer.' },

  // ── 🇵🇱 POLAND ──
  { id: 'pl_krakow', hero: true, country: 'Poland', flag: '🇵🇱', emoji: '🏙️', name: 'Main Market Square', area: 'Kraków',
    lat: 50.0619, lng: 19.9370, tags: ['Culture', 'Food'],
    desc: 'One of the largest medieval squares in Europe, and still the middle of the city rather than a museum of one. The Wawel castle and the Jewish quarter are both a short walk.' },
  { id: 'pl_morskie', country: 'Poland', flag: '🇵🇱', emoji: '🏔️', name: 'Morskie Oko', area: 'Zakopane',
    lat: 49.2015, lng: 20.0713, tags: ['Hiking', 'Photo'],
    desc: 'A glacial lake in the Tatras, reached by a nine-kilometre walk up a closed road. Busy in the afternoon, quiet if you start at dawn.' },
  { id: 'pl_gdansk', country: 'Poland', flag: '🇵🇱', emoji: '⚓', name: 'Long Market', area: 'Gdańsk',
    lat: 54.3489, lng: 18.6533, tags: ['Culture', 'Heritage'],
    desc: 'A Baltic merchant city rebuilt after the war from its own paintings and plans. The Solidarity museum at the shipyard is the other half of the story.' },

  // ── 🇭🇷 CROATIA ──
  { id: 'hr_dubrovnik', hero: true, country: 'Croatia', flag: '🇭🇷', emoji: '🧱', name: 'Dubrovnik Old Town', area: 'Dubrovnik',
    lat: 42.6407, lng: 18.1077, tags: ['Heritage', 'Swim'],
    desc: 'A walled city on the Adriatic you can walk the full circuit of, two kilometres of rampart above the roofs. Swim off the rocks outside the west wall afterwards.' },
  { id: 'hr_plitvice', country: 'Croatia', flag: '🇭🇷', emoji: '💧', name: 'Plitvice Lakes', area: 'Plitvice',
    lat: 44.8654, lng: 15.5820, tags: ['Hiking', 'Photo'],
    desc: 'Sixteen terraced lakes falling into one another over travertine, crossed on wooden walkways. A UNESCO site; swimming is not allowed anywhere in it.' },
  { id: 'hr_split', country: 'Croatia', flag: '🇭🇷', emoji: '🏛️', name: 'Diocletian\'s Palace', area: 'Split',
    lat: 43.5081, lng: 16.4402, tags: ['Heritage', 'Food'],
    desc: 'A Roman emperor\'s retirement palace that a whole town moved into and never left — the streets inside it are still lived in and full of bars.' },

  // ── 🇦🇹 AUSTRIA ──
  { id: 'at_hallstatt', hero: true, country: 'Austria', flag: '🇦🇹', emoji: '🏔️', name: 'Hallstatt', area: 'Hallstatt',
    lat: 47.5622, lng: 13.6493, tags: ['Photo', 'Heritage'],
    desc: 'A village on a lake under the Dachstein, with a salt mine above it that has been worked for three thousand years. Very small, and it knows it — come outside the middle of the day.' },
  { id: 'at_schonbrunn', country: 'Austria', flag: '🇦🇹', emoji: '🏰', name: 'Schönbrunn', area: 'Vienna',
    lat: 48.1858, lng: 16.3122, tags: ['Heritage', 'Culture'],
    desc: 'The Habsburgs\' summer palace and its gardens. The Gloriette at the top of the hill is free to walk to and gives you the whole city.' },

  // ── 🇭🇺 HUNGARY ──
  { id: 'hu_parliament', hero: true, country: 'Hungary', flag: '🇭🇺', emoji: '🏛️', name: 'The Parliament', area: 'Budapest',
    lat: 47.5072, lng: 19.0458, tags: ['Heritage', 'Photo'],
    desc: 'A neo-gothic building on the Danube with 691 rooms. Best seen from the Buda side at night, when the whole river front is lit.' },
  { id: 'hu_szechenyi', country: 'Hungary', flag: '🇭🇺', emoji: '♨️', name: 'Széchenyi Baths', area: 'Budapest',
    lat: 47.5188, lng: 19.0827, tags: ['Wellbeing', 'Culture'],
    desc: 'Thermal water at 38°C in an outdoor neo-baroque pool, in a city built on hot springs. Locals play chess in it. Bring flip-flops.' },
  { id: 'hu_balaton', country: 'Hungary', flag: '🇭🇺', emoji: '⛵', name: 'Tihany', area: 'Lake Balaton',
    lat: 46.9137, lng: 17.8894, tags: ['Swim', 'Photo'],
    desc: 'A peninsula of lavender fields and an abbey above the largest lake in central Europe. The water is shallow and warm all summer.' },

  // ── 🇱🇹 LITHUANIA ──
  { id: 'lt_vilnius', hero: true, country: 'Lithuania', flag: '🇱🇹', emoji: '🏘️', name: 'Vilnius Old Town', area: 'Vilnius',
    lat: 54.6800, lng: 25.2870, tags: ['Culture', 'Heritage'],
    desc: 'One of the largest surviving medieval old towns in northern Europe, and a genuinely cheap city to spend a week in. Užupis, the self-declared republic across the river, is ten minutes away.' },
  { id: 'lt_trakai', country: 'Lithuania', flag: '🇱🇹', emoji: '🏰', name: 'Trakai Island Castle', area: 'Trakai',
    lat: 54.6522, lng: 24.9330, tags: ['Heritage', 'Photo'],
    desc: 'A red-brick castle on an island in a lake, half an hour from Vilnius by train. Rent a kayak and look at it from the water.' },
  { id: 'lt_nida', country: 'Lithuania', flag: '🇱🇹', emoji: '🏜️', name: 'Curonian Spit', area: 'Nida',
    lat: 55.3033, lng: 21.0058, tags: ['Photo', 'Swim'],
    desc: 'A ninety-eight-kilometre sand bar between a lagoon and the Baltic, with dunes tall enough to be called mountains locally. A UNESCO site shared with Russia.' },
  { id: 'lt_crosses', country: 'Lithuania', flag: '🇱🇹', emoji: '✝️', name: 'Hill of Crosses', area: 'Šiauliai',
    lat: 56.0153, lng: 23.4167, tags: ['Heritage', 'Culture'],
    desc: 'A small hill covered in more than a hundred thousand crosses left by pilgrims. Bulldozed three times under Soviet rule and rebuilt each time overnight.' },

  // ── 🇪🇪 ESTONIA ──
  { id: 'ee_tallinn', hero: true, country: 'Estonia', flag: '🇪🇪', emoji: '🏰', name: 'Tallinn Old Town', area: 'Tallinn',
    lat: 59.4370, lng: 24.7454, tags: ['Culture', 'Heritage'],
    desc: 'A walled Hanseatic town that came through the war nearly intact, wrapped around a limestone hill. The whole country is famously online — the wifi in the medieval café will be better than yours.' },
  { id: 'ee_lahemaa', country: 'Estonia', flag: '🇪🇪', emoji: '🌲', name: 'Lahemaa National Park', area: 'Lahemaa',
    lat: 59.5333, lng: 25.8000, tags: ['Hiking', 'Photo'],
    desc: 'Bog boardwalks, pine forest and a Baltic coastline of glacial boulders, an hour east of Tallinn. The Viru bog trail is short, flat and unlike anywhere else.' },
  { id: 'ee_tartu', country: 'Estonia', flag: '🇪🇪', emoji: '🎓', name: 'Tartu', area: 'Tartu',
    lat: 58.3780, lng: 26.7290, tags: ['Culture', 'Food'],
    desc: 'The university town, and the reason Estonia has the student energy it does. Small, walkable, and cheaper than the capital.' },

  // ── 🇨🇭 SWITZERLAND ──
  { id: 'ch_lauterbrunnen', hero: true, country: 'Switzerland', flag: '🇨🇭', emoji: '💦', name: 'Lauterbrunnen', area: 'Lauterbrunnen',
    lat: 46.5936, lng: 7.9086, tags: ['Hiking', 'Photo'],
    desc: 'A valley with seventy-two waterfalls coming off vertical walls on both sides. Trains and cable cars go up from here into the whole Jungfrau region.' },
  { id: 'ch_zermatt', country: 'Switzerland', flag: '🇨🇭', emoji: '🏔️', name: 'The Matterhorn', area: 'Zermatt',
    lat: 45.9763, lng: 7.6586, tags: ['Hiking', 'Photo'],
    desc: 'The mountain on the chocolate. Zermatt below it has no petrol cars, so you arrive by train and the town is quiet.' },

  // ── 🇳🇴 NORWAY ──
  { id: 'no_lofoten', hero: true, country: 'Norway', flag: '🇳🇴', emoji: '🎣', name: 'Reine', area: 'Lofoten',
    lat: 67.9333, lng: 13.0833, tags: ['Photo', 'Hiking'],
    desc: 'Red fishing huts under granite peaks, inside the Arctic Circle. Midnight sun in summer, northern lights in winter, and hikes straight from the village.' },
  { id: 'no_geiranger', country: 'Norway', flag: '🇳🇴', emoji: '⛴️', name: 'Geirangerfjord', area: 'Geiranger',
    lat: 62.1010, lng: 7.0053, tags: ['Photo', 'Heritage'],
    desc: 'A UNESCO fjord with waterfalls falling straight into it from a kilometre up. The public ferry costs a fraction of the tourist cruise and takes the same route.' },

  // ── 🇮🇸 ICELAND ──
  { id: 'is_seljalandsfoss', hero: true, country: 'Iceland', flag: '🇮🇸', emoji: '💧', name: 'Seljalandsfoss', area: 'South Iceland',
    lat: 63.6156, lng: -19.9886, tags: ['Photo', 'Hiking'],
    desc: 'A sixty-metre waterfall with a path that goes behind the curtain of water. You will get wet; that is the whole idea.' },
  { id: 'is_reynisfjara', country: 'Iceland', flag: '🇮🇸', emoji: '🖤', name: 'Reynisfjara', area: 'Vík',
    lat: 63.4034, lng: -19.0448, tags: ['Photo'],
    desc: 'A black sand beach with basalt columns and sea stacks. The waves here are genuinely dangerous — stay well back from the water, every year somebody does not.' },

  // ── 🇸🇪 🇩🇰 🇫🇮 THE NORTH ──
  { id: 'se_gamlastan', hero: true, country: 'Sweden', flag: '🇸🇪', emoji: '🏘️', name: 'Gamla Stan', area: 'Stockholm',
    lat: 59.3251, lng: 18.0710, tags: ['Culture', 'Heritage'],
    desc: 'The old town on its own island, one of the best preserved in Europe. Stockholm is spread over fourteen islands and the ferries between them are ordinary public transport.' },
  { id: 'dk_nyhavn', hero: true, country: 'Denmark', flag: '🇩🇰', emoji: '⛵', name: 'Nyhavn', area: 'Copenhagen',
    lat: 55.6799, lng: 12.5913, tags: ['Photo', 'Food'],
    desc: 'The painted canal front, and the city that made cycling normal for everybody rather than for sport. Rent a bike on day one; it is faster than anything else here.' },
  { id: 'fi_suomenlinna', hero: true, country: 'Finland', flag: '🇫🇮', emoji: '🏝️', name: 'Suomenlinna', area: 'Helsinki',
    lat: 60.1454, lng: 24.9881, tags: ['Heritage', 'Hiking'],
    desc: 'A sea fortress across six islands, reached by the ordinary commuter ferry from the market square. People live on it; it is a neighbourhood as much as a monument.' },

  // ── 🇧🇪 BELGIUM · 🇮🇪 IRELAND ──
  { id: 'be_bruges', hero: true, country: 'Belgium', flag: '🇧🇪', emoji: '🍫', name: 'Bruges', area: 'Bruges',
    lat: 51.2085, lng: 3.2247, tags: ['Heritage', 'Food'],
    desc: 'A medieval trading city that stopped growing when its river silted up, and so stayed as it was. Small enough to cross on foot in twenty minutes.' },
  { id: 'ie_moher', hero: true, country: 'Ireland', flag: '🇮🇪', emoji: '🌊', name: 'Cliffs of Moher', area: 'County Clare',
    lat: 52.9715, lng: -9.4309, tags: ['Photo', 'Hiking'],
    desc: 'Fourteen kilometres of cliff up to 214 metres above the Atlantic. The coastal walk from Doolin arrives at them on foot and is the better way in.' },

  // ── 🇲🇦 MOROCCO ──
  { id: 'ma_jemaa', country: 'Morocco', flag: '🇲🇦', emoji: '🫖', name: 'Jemaa el-Fnaa', area: 'Marrakech',
    lat: 31.6258, lng: -7.9891, tags: ['Culture', 'Food'],
    desc: 'A square that is a market by day and an open-air kitchen with storytellers and musicians by night. UNESCO lists it for the performances, not the buildings.' },
  { id: 'ma_fes', country: 'Morocco', flag: '🇲🇦', emoji: '🧵', name: 'Fes el-Bali', area: 'Fes',
    lat: 34.0648, lng: -4.9739, tags: ['Culture', 'Heritage'],
    desc: 'The largest car-free urban area in the world — nine thousand lanes, and donkeys still doing the deliveries. The tanneries have been working the same way since the eleventh century.' },
  { id: 'ma_merzouga', country: 'Morocco', flag: '🇲🇦', emoji: '🐪', name: 'Erg Chebbi', area: 'Merzouga',
    lat: 31.0996, lng: -4.0119, tags: ['Photo', 'Hiking'],
    desc: 'Sahara dunes up to 150 metres high at the edge of the desert. Camps out in the sand are the reason to come; the sky at night is the reason people stay two.' },
  { id: 'ma_ait', country: 'Morocco', flag: '🇲🇦', emoji: '🏜️', name: 'Aït Benhaddou', area: 'Ouarzazate',
    lat: 31.0472, lng: -7.1318, tags: ['Heritage', 'Photo'],
    desc: 'A fortified earthen village on the old caravan route to Marrakech, and a UNESCO site. You have seen it in films; it is smaller and more astonishing in person.' },
  { id: 'ma_essaouira', country: 'Morocco', flag: '🇲🇦', emoji: '🪁', name: 'Essaouira', area: 'Essaouira',
    lat: 31.5085, lng: -9.7595, tags: ['Swim', 'Food'],
    desc: 'A walled Atlantic port with constant wind, which makes it hopeless for lying on the beach and excellent for kitesurfing. The fish is landed and grilled in the same hour.' },
  { id: 'ma_todra', country: 'Morocco', flag: '🇲🇦', emoji: '🧗', name: 'Todra Gorge', area: 'Tinghir',
    lat: 31.5897, lng: -5.5964, tags: ['Hiking', 'Photo'],
    desc: 'A canyon three hundred metres deep and, at its narrowest, ten metres wide, with a road and a stream running through the bottom of it.' },
];
